#config_version=6

mode:
  priority: 7888 #TODO
  start_events: mode_start_vuks_base
  stop_events: mode_stop_vuks_base, ball_will_end

event_player:
  activate_orbit_diverter:              [set_base_subway_capture_expected]
  activate_orbit_diverter_skillshot:    [set_base_subway_capture_expected]
  deactivate_orbit_diverter:            [set_base_subway_capture_unexpected]
  deactivate_orbit_diverter_skillshot:  [set_base_subway_capture_unexpected]
  base_vuk_group_hit:      [cheat_multiball_begin] #will not actually begin unless qualified
  base_subway_capture_hit: [cheat_multiball_begin]

variable_player:
  base_vuk_group_hit:
    score: 1500 * current_player.playfield_multiplier
    capture_hits: 1
  base_subway_capture_expected_hit:
    score: 5000 * current_player.playfield_multiplier
    capture_hits: 1
  base_subway_capture_unexpected_hit:
    score: 2000 * current_player.playfield_multiplier
    capture_hits: 0

shot_profiles:
  vuk_base_profile:
    advance_on_hit: False
    states:
      - name: singleton
  subway_base_profile:
    advance_on_hit: False
    states:
      - name: expected
      - name: unexpected

shots:
  base_left_vuk:
    profile: vuk_base_profile
    switch: s_subway_vuk_presence
    delay_switch:
      s_subway_entrance: 6s #TODO dial in speed.

  base_right_vuk:
    profile: vuk_base_profile
    switch: s_vuk_presence

  base_subway_capture:
    profile: subway_base_profile
    switch: s_subway_entrance
    control_events:
      - events: set_base_subway_capture_expected
        state: 0
      - events: set_base_subway_capture_unexpected
        state: 1

shot_groups:
  base_vuk_group:
    shots:
      - base_left_vuk
      - base_right_vuk
