#config_version=6

mode:
  start_events: mode_start_pops_burninated
  stop_events: mode_stop_pops_burninated, ball_will_end
  events_when_stopped: dj_stop_burnination_background
  priority: 2555

variable_player:
  burninated_pop_group_hit:
    score: 5000 * current_player.playfield_multiplier
    pop_hits: 1
    power_hits: 1

  burninated_pop_center_hit: #Center is worth 1k less. Hax
    score: -1 - (1000 * current_player.playfield_multiplier)

shot_profiles:
  burninated_pop_profile:
    advance_on_hit: False
    states:
      - name: singleton

shots:
  burninated_pop_left:
    profile: burninated_pop_profile
    switch: s_pop_left
  burninated_pop_right:
    profile: burninated_pop_profile
    switch: s_pop_right
  burninated_pop_center:
    profile: burninated_pop_profile
    switch: s_pop_center

shot_groups:
  burninated_pop_group:
    shots:
      - burninated_pop_left
      - burninated_pop_right
      - burninated_pop_center

event_player:
  mode_pops_burninated_started:
  - start_left_pop_burninated
  - start_right_pop_burninated
  - start_center_pop_burninated

show_player:
  burninated_pop_group_hit:
    pulse_pops:
      priority: 1
      loops: 2

  start_left_pop_burninated:
    fire_burninated_show:
      priority: 3
      key: pop_left_show
      sync_ms: 600
      start_step: 5
      show_tokens:
        light_prefix: l_pop_ring_a

  start_right_pop_burninated:
    fire_burninated_show:
      priority: 3
      key: pop_right_show
      sync_ms: 600
      start_step: 1
      show_tokens:
        light_prefix: l_pop_ring_b

  start_center_pop_burninated:
    fire_burninated_show:
      priority: 3
      key: pop_center_show
      sync_ms: 600
      start_step: 7
      show_tokens:
        light_prefix: l_pop_ring_c
