#config_version=6

high_score:
  _overwrite: true
  categories:
    score:
      - GRAND CHAMP
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
  defaults:
    score:
      - TRG: 999999
      - SB:  666666
      - HSR: 123456
      - AML: 98414
      - TST: 1

event_player:
  sw_text_input_left_active:
    text_input:
      action: left
  sw_text_input_right_active:
    text_input:
      action: right
  sw_text_input_select_active:
    text_input:
      action: select
