#config_version=6

high_score:
  _overwrite: true
  categories:
    score:
      - GRAND CHAMP
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
  defaults:
    score:
      - TRG: 999999
      - SB:  666666
      - HSR: 123456
      - AML: 98414
      - TST: 1

event_player:
  mode_high_score_started:
    - start_gi_highscore

show_player:
  start_gi_highscore:
    led_color:
      show_tokens:
        lights: lights_gi
        color: orange
