#config_version=6

high_score:
  _overwrite: true
  enter_initials_timeout: 60s
  categories:
    score:
      - GRAND CHAMP
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
    burnination_points:
      - BURNINATION CHAMP
  defaults:
    score:
      - TRG: 999999
      - SB:  666666
      - HSR: 123456
      - AML: 98414
      - TST: 1
    burnination_points:
      - BOSH: 23
  vars:
    score:
      - player: ball_end_time #TODO add support for game start and end instead

event_player:
  mode_high_score_started:
    - start_gi_highscore
  high_score_enter_initials:
    - dj_new_high_score

show_player:
  start_gi_highscore:
    led_color:
      show_tokens:
        lights: lights_gi
        color: orange

widget_player:
  text_input_high_score_complete:
    high_score_confirmation:
      slide: high_score

  high_score_enter_initials:
    high_score_confirmation:
      slide: high_score
      action: remove

  mode_high_score_ending:
    high_score_confirmation:
      slide: high_score
      action: remove
