#config_version=6

slide_player: #For GMC
  mode_attract_starting:
    attract:
      action: play

  mode_attract_started:
    startup:
      action: remove

show_player:
  mode_attract_started:
    attract_light_loop: play
    slots_spin_show:
      key: slots_grid_show
