#config_version=6

slide_player:
  mode_attract_started:
    attract:
      action: play
  mode_attract_started.1:
    startup:
      action: remove

sound_player:
  music_play_chiptune:
    theme_chiptune:
      bus: music
      fade_in: 500ms
      fade_out: 1s
  # music_stop_chiptune:
  #   theme_chiptune:
  #     action: stop
  #     ducking:
  #       bus: music
  #       attack: 0
  #       attenuation: 0
  #       release_point: 0
  #       release: 0s

event_player:
  mode_attract_started:
    - music_play_chiptune
  mode_attract_will_stop:
    - music_stop_chiptune

  s_mini_flipper_inactive:
    - music_play_chiptune
  s_mini_flipper_active:
    - music_stop_chiptune
