#config_version=6

config:
  - attract-media.yaml

mode_settings:
  selectable_items:
    - last_scores_1p{machine.player1_score and not machine.player2_score}
    - last_scores_2p{machine.player2_score and not machine.player3_score}
    - last_scores_3p{machine.player3_score and not machine.player4_score}
    - last_scores_4p{machine.player4_score}
    - title
    - byline
    - burnination_champ{machine.burnination_points1_value}
    - grand_champ{machine.score1_value}
    - high_score_1{machine.score2_value}
    - high_score_2{machine.score3_value}
    - high_score_3{machine.score4_value}
    - high_score_4{machine.score5_value}
    - logos
    - credits
  next_item_events: advance_attract_carousel
  previous_item_events: reverse_attract_carousel

timers:
  attract_carousel_timer:
    end_value: 1
    tick_interval: settings.attract_carousel_timer_tick
    start_running: true
    control_events:
      - event: item_highlighted
        action: restart
      - event: flipper_cradle
        action: stop
      - event: flipper_cradle_release
        action: restart

event_player:
  s_left_flipper_secondary_active: [reverse_attract_carousel]
  s_right_flipper_secondary_active: [advance_attract_carousel]
  timer_attract_carousel_timer_complete: [advance_attract_carousel]

  mode_attract_started:
    - main_show_reloop
    - slots_show_reloop
    - backbox_show_reloop

show_player:
  backbox_show_reloop:
    backbox_attract_loop:
      key: backbox_loop
      events_when_completed: backbox_show_reloop
      priority: 8

  main_show_reloop:
    light_test_loop:
      key: main_attract_show
      loops: 1
      events_when_completed: start_group2_color_dance
    target_dance:
      key: drop_bank_show
      loops: 1
      speed: 0.3
  start_group2_color_dance:
    group2_color_dance:
      key: main_attract_show
      loops: 2
      events_when_completed: start_group3_color_dance
  start_group3_color_dance:
    group3_color_dance:
      key: main_attract_show
      loops: 1
      events_when_completed: start_group4_color_dance
  start_group4_color_dance:
    group4_color_dance:
      key: main_attract_show
      loops: 0
      events_when_completed: start_group5_color_dance
  start_group5_color_dance:
    group5_color_dance:
      key: main_attract_show
      loops: 0
      events_when_completed: main_show_reloop

  start_slots_spin_show:
    slots_spin_show:
      key: slots_grid_show
      loops: 3
      events_when_completed: slots_show_reloop

  start_slots_party_show:
    slots_party_show:
      key: slots_grid_show
      loops: 2
      events_when_completed: slots_show_reloop

  start_slots_out_in_show:
    slots_out_in_in_out_show:
      key: slots_grid_show
      loops: 3
      events_when_completed: slots_show_reloop

  start_slots_spiral_in_show:
    slots_spiral_in:
      key: slots_grid_show
      loops: 1
      events_when_completed: slots_show_reloop

  start_slots_spiral_out_show:
    slots_spiral_out:
      key: slots_grid_show
      loops: 1
      events_when_completed: slots_show_reloop

  start_slots_stop_show:
    slots_stop:
      key: slots_grid_show
      loops: 3
      events_when_completed: slots_show_reloop

random_event_player:
  slots_show_reloop:
    scope: machine
    force_different: true
    events:
      - start_slots_spin_show
      - start_slots_party_show
      - start_slots_out_in_show
      - start_slots_spiral_in_show
      - start_slots_spiral_out_show
      - start_slots_stop_show
