#config_version=6

slide_player:
  mode_attract_started:
    attract:
      action: play
  mode_attract_started.1:
    startup:
      action: remove

event_player:
  mode_attract_started:
    - main_show_reloop
    - slots_show_reloop
    - backbox_show_reloop

show_player:
  backbox_show_reloop:
    backbox_attract_loop:
      key: backbox_loop
      events_when_completed: backbox_show_reloop
      priority: 8

  main_show_reloop:
    light_test_loop:
      key: main_attract_show
      loops: 1
      events_when_completed: start_group2_color_dance
  start_group2_color_dance:
    group2_color_dance:
      key: main_attract_show
      loops: 2
      events_when_completed: start_group3_color_dance
  start_group3_color_dance:
    group3_color_dance:
      key: main_attract_show
      loops: 1
      events_when_completed: start_group4_color_dance
  start_group4_color_dance:
    group4_color_dance:
      key: main_attract_show
      loops: 0
      events_when_completed: start_group5_color_dance
  start_group5_color_dance:
    group5_color_dance:
      key: main_attract_show
      loops: 0
      events_when_completed: main_show_reloop

  start_slots_spin_show:
    slots_spin_show:
      key: slots_grid_show
      loops: 3
      events_when_completed: slots_show_reloop

  start_slots_party_show:
    slots_party_show:
      key: slots_grid_show
      loops: 2
      events_when_completed: slots_show_reloop

  start_slots_out_in_show:
    slots_out_in_in_out_show:
      key: slots_grid_show
      loops: 3
      events_when_completed: slots_show_reloop

  start_slots_spiral_in_show:
    slots_spiral_in:
      key: slots_grid_show
      loops: 1
      events_when_completed: slots_show_reloop

  start_slots_spiral_out_show:
    slots_spiral_out:
      key: slots_grid_show
      loops: 1
      events_when_completed: slots_show_reloop

  start_slots_stop_show:
    slots_stop:
      key: slots_grid_show
      loops: 3
      events_when_completed: slots_show_reloop

random_event_player:
  slots_show_reloop:
    scope: machine
    force_different: true
    events:
      - start_slots_spin_show
      - start_slots_party_show
      - start_slots_out_in_show
      - start_slots_spiral_in_show
      - start_slots_spiral_out_show
      - start_slots_stop_show
