#config_version=6

slide_player: #For GMC
  mode_attract_starting:
    attract:
      action: play

  mode_attract_started:
    startup:
      action: remove

event_player:
  mode_attract_started: slots_show_reloop

show_player:
  mode_attract_started:
    attract_light_loop: play

  start_slots_spin_show:
    slots_spin_show:
      key: slots_grid_show
      loops: 3
      events_when_completed: slots_show_reloop

  start_slots_party_show:
    slots_party_show:
      key: slots_grid_show
      loops: 2
      events_when_completed: slots_show_reloop

  start_slots_out_in_show:
    slots_out_in_in_out_show:
      key: slots_grid_show
      loops: 3
      events_when_completed: slots_show_reloop

  start_slots_spiral_in_show:
    slots_spiral_in:
      key: slots_grid_show
      loops: 1
      events_when_completed: slots_show_reloop

  start_slots_spiral_out_show:
    slots_spiral_out:
      key: slots_grid_show
      loops: 1
      events_when_completed: slots_show_reloop

  start_slots_stop_show:
    slots_stop:
      key: slots_grid_show
      loops: 3
      events_when_completed: slots_show_reloop

random_event_player:
  slots_show_reloop:
    scope: machine
    force_different: true
    events:
      - start_slots_spin_show
      - start_slots_party_show
      - start_slots_out_in_show
      - start_slots_spiral_in_show
      - start_slots_spiral_out_show
      - start_slots_stop_show
