#config_version=6

slide_player:
  mode_attract_started.1:
    attract:
      action: play
  mode_attract_started.0:
    startup:
      action: remove

event_player:
  mode_attract_started:
    - dj_attract_music_pool
  flipper_cancel: #Does not actually happen in attract it seems
    - dj_attract_music_pool
  mode_attract_will_stop:
    - dj_music_stop
