#config_version=6

slide_player: #For GMC
  mode_attract_starting:
    attract:
      action: play

  mode_attract_started:
    startup:
      action: remove

show_player:
  mode_attract_started:
    attract_light_loop: play
    light_ring_spinner: play
  mode_attract_will_stop: #TODO these stops may be unnecessary if mode stopping turns them off
    attract_light_loop: stop
    light_ring_spinner: stop

light_player:
  mode_attract_stopping: #Clear lights after light loop stop
    "*": off #TODO Ernie says this shouldnt be necessary
