#config_version=6

slide_player: #For GMC
  mode_attract_starting:
    attract:
      action: play

  mode_attract_started:
    startup:
      action: remove

show_player:
  mode_attract_started:
    attract_light_loop: play
  mode_attract_will_stop:
    attract_light_loop: stop

light_player:
  mode_attract_stopping: #Clear lights after light loop stop
    "*": off #TODO Ernie says this shouldnt be necessary
