#config_version=6

show_player:
  mode_attract_started:
    on:
      show_tokens:
        led: l_start
  play_secret_lightshow:
    flash_color:
      priority: 10
      loops: 8
      speed: 7
      show_tokens:
        lights: "*"
        color: red

slide_player:
  mode_attract_started.1:
    attract:
      action: play
  mode_attract_started.0:
    startup:
      action: remove

event_player:
  # Play pool music on start, flipper cancel, or when a track finishes
  mode_attract_started:
    - dj_attract_music_pool
  flipper_cancel:
    - dj_attract_music_pool
  music_track_finished:
    - dj_attract_music_pool|1000ms

  # Stop music when flipper cradle (as a manual override) and on mode end
  flipper_cradle:
    - dj_music_stop
  mode_attract_will_stop:
    - dj_music_stop

  super_secret_sequence_hit:
    - dj_secret_quip
    - play_secret_lightshow

  special_music_finished:
    - dj_attract_music_pool|1000ms

sequence_shots:
  super_secret_sequence:
    switch_sequence:
      - s_left_flipper
      - s_left_flipper
      - s_left_flipper
      - s_right_flipper
      - s_left_flipper
      - s_left_flipper
      - s_left_flipper
      - s_right_flipper
      - s_left_flipper
      - s_left_flipper
      - s_left_flipper
      - s_right_flipper
      - s_left_flipper
      - s_right_flipper
      - s_left_flipper
      - s_right_flipper
      - s_right_flipper
    cancel_switches:
      - s_start
      - s_plunger
