#config_version=6

mode:
  start_events: mode_start_pops_burnination
  stop_events: mode_complete_pops_burnination, mode_fail_pops_burnination, ball_will_end
  priority: 2550

slide_player:
  mode_pops_burnination_started:
    burnination:
      action: play
  mode_pops_burnination_will_stop:
    burnination:
      action: remove

timers:
  # Each burndown on a separate timer
  pop_left_burndown:
    start_value: 0
    end_value: settings.burnination_pop_countdown_seconds
    direction: up
    start_running: true
    restart_on_complete: true
    control_events:
      - action: start
        event: pop_left_burndown_start
      - action: stop
        event: pop_left_burndown_stop
      - action: reset
        event: pop_left_burndown_reset

  pop_right_burndown:
    start_value: 0
    end_value: settings.burnination_pop_countdown_seconds
    direction: up
    start_running: true
    restart_on_complete: true
    control_events:
      - action: start
        event: pop_right_burndown_start
      - action: stop
        event: pop_right_burndown_stop
      - action: reset
        event: pop_right_burndown_reset

  pop_center_burndown:
    start_value: 0
    end_value: settings.burnination_pop_countdown_seconds
    direction: up
    start_running: true
    restart_on_complete: true
    control_events:
      - action: start
        event: pop_center_burndown_start
      - action: stop
        event: pop_center_burndown_stop
      - action: reset
        event: pop_center_burndown_reset

shot_profiles:
  burnination_pop_profile:
    advance_on_hit: True
    states:
      - name: 'base'
        show: 'off'
      - name: 'low'
        show: 'fire_low_level_show'
      - name: 'medium'
        show: 'fire_medium_level_show'
      - name: 'high'
        show: 'fire_high_level_show'
      - name: 'extreme'
        show: 'fire_extreme_level_show'

shots:
  shot_burnination_pop_left:
    profile: burnination_pop_profile
    switch: s_pop_left
    show_tokens:
      light_prefix: l_pop_ring_a
    control_events:
      - events: set_burnination_pop_left_extreme
        state: 4
      - events: set_burnination_pop_left_high
        state: 3
      - events: set_burnination_pop_left_medium
        state: 2
      - events: set_burnination_pop_left_low
        state: 1
      - events: set_burnination_pop_left_base
        state: 0
  shot_burnination_pop_right:
    profile: burnination_pop_profile
    switch: s_pop_right
    show_tokens:
      light_prefix: l_pop_ring_b
    control_events:
      - events: set_burnination_pop_right_extreme
        state: 4
      - events: set_burnination_pop_right_high
        state: 3
      - events: set_burnination_pop_right_medium
        state: 2
      - events: set_burnination_pop_right_low
        state: 1
      - events: set_burnination_pop_right_base
        state: 0
  shot_burnination_pop_center:
    profile: burnination_pop_profile
    switch: s_pop_center
    show_tokens:
      light_prefix: l_pop_ring_c
    control_events:
      - events: set_burnination_pop_center_extreme
        state: 4
      - events: set_burnination_pop_center_high
        state: 3
      - events: set_burnination_pop_center_medium
        state: 2
      - events: set_burnination_pop_center_low
        state: 1
      - events: set_burnination_pop_center_base
        state: 0

shot_groups:
  burnination_pop_group:
    shots:
      - shot_burnination_pop_left
      - shot_burnination_pop_right
      - shot_burnination_pop_center

state_machines:
  highest_burnination_achieved:
    persist_state: false
    starting_state: base
    states:
      base:
        label: Simmering
      low:
        label: Slow burn
      medium:
        label: Getting warmer
      high:
        label: Flame on
      extreme:
        label: Burnination!
      complete:
        label: TOTAL BURNINATION

    transitions:
      - source: base
        target: low
        events: set_burnination_pop_left_low, set_burnination_pop_right_low, set_burnination_pop_center_low
        events_when_transitioning: dj_burnination_pop_up_1
      - source: low
        target: medium
        events: set_burnination_pop_left_medium, set_burnination_pop_right_medium, set_burnination_pop_center_medium
        events_when_transitioning: dj_burnination_pop_up_2
      - source: medium
        target: high
        events: set_burnination_pop_left_high, set_burnination_pop_right_high, set_burnination_pop_center_high
        events_when_transitioning: dj_burnination_pop_up_3
      - source: high
        target: extreme
        events: set_burnination_pop_left_extreme, set_burnination_pop_right_extreme, set_burnination_pop_center_extreme
        events_when_transitioning: dj_burnination_pop_up_4
      - source: extreme
        target: complete
        events: set_burnination_pops_all_complete
        events_when_transitioning: dj_burnination_pop_up_5


variable_player:
  mode_pops_burnination_started:
    pop_left_fire_level:
      int: 0
      action: set
    pop_right_fire_level:
      int: 0
      action: set
    pop_center_fire_level:
      int: 0
      action: set

  # Increment fire level by three on bumper hit
  shot_burnination_pop_left_hit:
    pop_left_fire_level: settings.burnination_pop_hit_increment

  shot_burnination_pop_right_hit:
    pop_right_fire_level: settings.burnination_pop_hit_increment

  shot_burnination_pop_center_hit:
    pop_center_fire_level: settings.burnination_pop_hit_increment

  burnination_pop_group_hit:
    points: 1000
    pop_hits: 1
    power_hits: 1
    burnination_points: 1

  timer_pop_left_burndown_complete{current_player.pop_left_fire_level > 0}:
    pop_left_fire_level: -1
  timer_pop_right_burndown_complete{current_player.pop_right_fire_level > 0}:
    pop_right_fire_level: -1
  timer_pop_center_burndown_complete{current_player.pop_center_fire_level > 0}:
    pop_center_fire_level: -1

event_player:
  # Reset the specific pop timer when pop is hit
  shot_burnination_pop_left_hit:
    - pop_left_burndown_reset
  shot_burnination_pop_right_hit:
    - pop_right_burndown_reset
  shot_burnination_pop_center_hit:
    - pop_center_burndown_reset

  burnination_pop_group_hit:
    - dj_burnination_pop_hit_pool
    - increment_burnination_time_remaining

  # Stop timers on mode exit process starting
  mode_pops_burnination_will_stop:
    - pop_left_burndown_stop
    - pop_right_burndown_stop
    - pop_center_burndown_stop

  # When player variables change, update shot state
  player_pop_left_fire_level:
    - update_pop_left_state
  player_pop_right_fire_level:
    - update_pop_right_state
  player_pop_center_fire_level:
    - update_pop_center_state

  update_pop_left_state{current_player.pop_left_fire_level <= 0}: [set_burnination_pop_left_base]
  update_pop_left_state{current_player.pop_left_fire_level > 0 and current_player.pop_left_fire_level < settings.burnination_fire_level_one}: [set_burnination_pop_left_low]
  update_pop_left_state{current_player.pop_left_fire_level >= settings.burnination_fire_level_one and current_player.pop_left_fire_level < settings.burnination_fire_level_two}: [set_burnination_pop_left_medium]
  update_pop_left_state{current_player.pop_left_fire_level >= settings.burnination_fire_level_two and current_player.pop_left_fire_level < settings.burnination_fire_level_goal}: [set_burnination_pop_left_high]
  update_pop_left_state{current_player.pop_left_fire_level >= settings.burnination_fire_level_goal}: [set_burnination_pop_left_extreme]

  update_pop_right_state{current_player.pop_right_fire_level <= 0}: [set_burnination_pop_right_base]
  update_pop_right_state{current_player.pop_right_fire_level > 0 and current_player.pop_right_fire_level < settings.burnination_fire_level_one}: [set_burnination_pop_right_low]
  update_pop_right_state{current_player.pop_right_fire_level >= settings.burnination_fire_level_one and current_player.pop_right_fire_level < settings.burnination_fire_level_two}: [set_burnination_pop_right_medium]
  update_pop_right_state{current_player.pop_right_fire_level >= settings.burnination_fire_level_two and current_player.pop_right_fire_level < settings.burnination_fire_level_goal}: [set_burnination_pop_right_high]
  update_pop_right_state{current_player.pop_right_fire_level >= settings.burnination_fire_level_goal}: [set_burnination_pop_right_extreme]

  update_pop_center_state{current_player.pop_center_fire_level <= 0}: [set_burnination_pop_center_base]
  update_pop_center_state{current_player.pop_center_fire_level > 0 and current_player.pop_center_fire_level < settings.burnination_fire_level_one}: [set_burnination_pop_center_low]
  update_pop_center_state{current_player.pop_center_fire_level >= settings.burnination_fire_level_one and current_player.pop_center_fire_level < settings.burnination_fire_level_two}: [set_burnination_pop_center_medium]
  update_pop_center_state{current_player.pop_center_fire_level >= settings.burnination_fire_level_two and current_player.pop_center_fire_level < settings.burnination_fire_level_goal}: [set_burnination_pop_center_high]
  update_pop_center_state{current_player.pop_center_fire_level >= settings.burnination_fire_level_goal}: [set_burnination_pop_center_extreme]

  update_pop_left_state{current_player.pop_left_fire_level > settings.burnination_fire_level_goal and current_player.pop_right_fire_level > settings.burnination_fire_level_goal and current_player.pop_center_fire_level > settings.burnination_fire_level_goal}: [set_burnination_pops_all_complete]
  update_pop_right_state{current_player.pop_left_fire_level > settings.burnination_fire_level_goal and current_player.pop_right_fire_level > settings.burnination_fire_level_goal and current_player.pop_center_fire_level > settings.burnination_fire_level_goal}: [set_burnination_pops_all_complete]
  update_pop_center_state{current_player.pop_left_fire_level > settings.burnination_fire_level_goal and current_player.pop_right_fire_level > settings.burnination_fire_level_goal and current_player.pop_center_fire_level > settings.burnination_fire_level_goal}: [set_burnination_pops_all_complete]
