#config_version=6
# Majesty Achievements!

---
mode:
  priority: 1090
  start_events: ball_started
  stop_events: mode_stop_generated_achievements, ball_will_end
show_player:
  celebrate_achievement:
    majesty_rainbow_loop:
      action: play
      loops: 2
achievements:
  burnination:
    start_enabled: true
    show_tokens:
      light: l_majesty_1
    show_when_started: flash
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: burnination_controller_begin
    stop_events: burnination_controller_fail
    complete_events: burnination_controller_complete
  a2:
    start_enabled: true
    show_tokens:
      light: l_majesty_2
    show_when_started: flash
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: mode_start_achievement_a2
    stop_events: mode_fail_achievement_a2
    complete_events: mode_complete_achievement_a2
  a3:
    start_enabled: true
    show_tokens:
      light: l_majesty_3
    show_when_started: flash
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: mode_start_achievement_a3
    stop_events: mode_fail_achievement_a3
    complete_events: mode_complete_achievement_a3
  a4:
    start_enabled: true
    show_tokens:
      light: l_majesty_4
    show_when_started: flash
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: mode_start_achievement_a4
    stop_events: mode_fail_achievement_a4
    complete_events: mode_complete_achievement_a4
  a5:
    start_enabled: true
    show_tokens:
      light: l_majesty_5
    show_when_started: flash
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: mode_start_achievement_a5
    stop_events: mode_fail_achievement_a5
    complete_events: mode_complete_achievement_a5
  a6:
    start_enabled: true
    show_tokens:
      light: l_majesty_6
    show_when_started: flash
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: mode_start_achievement_a6
    stop_events: mode_fail_achievement_a6
    complete_events: mode_complete_achievement_a6

