#config_version=6
# Majesty Achievements!

---
mode:
  priority: 2075
  start_events: ball_started
  stop_events: mode_stop_generated_achievements, ball_will_end
show_player:
  celebrate_achievement{restore == False}:
    majesty_rainbow_loop:
      action: play
      loops: 2
achievements:
  burnination:
    start_enabled: true
    show_tokens:
      light: l_majesty_1
    show_when_started:
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: mode_generated_achievements_started
    stop_events:
    complete_events: burnination_controller_complete
  power_puncher:
    start_enabled: true
    show_tokens:
      light: l_majesty_2
    show_when_started:
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: mode_generated_achievements_started
    stop_events:
    complete_events: achievement_pp_complete
  capture_capturerer:
    start_enabled: true
    show_tokens:
      light: l_majesty_3
    show_when_started:
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: mode_generated_achievements_started
    stop_events:
    complete_events: achievement_qq_complete
  ramp_rider:
    start_enabled: true
    show_tokens:
      light: l_majesty_4
    show_when_started:
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: mode_generated_achievements_started
    stop_events:
    complete_events: achievement_rr_complete
  spinner_spinner:
    start_enabled: true
    show_tokens:
      light: l_majesty_5
    show_when_started:
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: mode_generated_achievements_started
    stop_events:
    complete_events: achievement_ss_complete
  target_targeter:
    start_enabled: true
    show_tokens:
      light: l_majesty_6
    show_when_started:
    show_when_completed: 'on'
    restart_after_stop_possible: true
    events_when_completed: celebrate_achievement
    start_events: mode_generated_achievements_started
    stop_events:
    complete_events: achievement_tt_complete

