#config_version=6

mode:
  start_events: ball_started
  priority: 100

variable_player:
  #Simple lane scoring
  s_left_outer_lane_active:
    score: 999 #Outers score more because ball ends
  s_left_inner_lane_active:
    score: 100

  s_right_inner_lane_active:
    score: 100
  s_right_outer_lane_active:
    score: 999

  #Simple sling scoring with sling counter
  s_left_sling_active:
    score: 25 #Left scores less because plunge to left is common
    sling_hits: 1
  s_right_sling_active:
    score: 50
    sling_hits: 1

  #Hooks for sling sequence pairs
  slings_l2r_hit:
    score: 250 #Sequence starting with left scores less because plunge start

  slings_r2l_hit:
    score: 555


sequence_shots:
  slings_l2r:
    switch_sequence: s_left_sling, s_right_sling
    sequence_timeout: 300ms
  slings_r2l:
    switch_sequence: s_right_sling, s_left_sling
    sequence_timeout: 300ms

light_player:
  # Sequence: flipper button, flipper coil to EOS, flipper button release
  s_left_flipper_active:
    l_mini_cab_left: 000099
  s_left_flipper_eos_active:
    l_mini_cab_left: 0000ff
  s_left_flipper_inactive:
    l_mini_cab_left: off

  # Sequence: flipper button, flipper coil to EOS, flipper button release
  s_right_flipper_active:
    l_mini_cab_right: 000099
  s_right_flipper_eos_active:
    l_mini_cab_right: 0000ff
  s_right_flipper_inactive:
    l_mini_cab_right: off

  # Sequence: ball sent to plunge lane, flipper button, no EOS, (clear lane), flipper button release
  s_plunger_active:
    l_mini_cab_mini: 00ff00
  s_mini_flipper_active:
    l_mini_cab_mini: 0000ff
  s_mini_flipper_inactive:
    l_mini_cab_mini: off

combo_switches:
  cab_two_button_reset: # Press both cab buttons to max for 2.5s to trigger multiball
    events_when_both: mini_cabinet_multiball_qualified
    switches_1: s_mini_flipper
    switches_2: s_right_flipper
    hold_time: 2500ms
    max_offset_time: 200ms

show_player:
  mini_cabinet_multiball_qualified:
    cabinet_multiball_flash:
      loops: 1 # Should play TWICE

multiballs:
  cabinet_multiball:
    ball_count: 3
    ball_count_type: total
    enable_events: playfield_active
    disable_events: ball_ending
    start_events: mini_cabinet_multiball_qualified
    shoot_again: 7000ms

ball_saves:
  default:
    active_time: 5s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    auto_launch: true
    balls_to_save: 1
    debug: true
