#config_version=6

config:
  - light_player.yaml
  - mini_cab_multiball.yaml
  - virtual_hooks.yaml

mode:
  start_events: ball_started
  priority: 100

event_player:
  mode_base_started:
    - mode_start_priority_shows
    - mode_start_skillshot_base
    - mode_start_pops_base
    - mode_start_slings_base
    - mode_start_lower_lanes_base
    - mode_start_burn_rollovers

variable_player:
  #Playfield multiplier always back down to 1 on new ball
  mode_base_started:
    playfield_multiplier:
      action: set
      int: 1

  #indirection so players can hook onto increment instead of the player var event
  increment_playfield_multiplier{current_player.playfield_multiplier < 5}:
    playfield_multiplier:
      action: add
      int: 1

ball_saves:
  default:
    active_time: 5s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    auto_launch: true
    balls_to_save: 1
    early_ball_save_events: s_right_outer_lane_active, s_right_inner_lane_active

timed_switches:
  ts_start_button:
    time: 3000ms
    switches:
      - s_start
