#config_version=6

config:
  - light_player.yaml
  - mini_cab_multiball.yaml

mode:
  start_events: ball_started
  priority: 100

event_player:
  mode_base_started:
    # - qualify_pops_burnination #Off for now to reduce log spam

variable_player:
  #Simple lane scoring
  s_left_outer_lane_active:
    score: 999 #Outers score more because ball ends
  s_left_inner_lane_active:
    score: 100

  s_right_inner_lane_active:
    score: 100
  s_right_outer_lane_active:
    score: 999

  #Simple sling scoring with sling counter
  s_left_sling_active:
    score: 25 #Left scores less because plunge to left is common
    sling_hits: 1
  s_right_sling_active:
    score: 50
    sling_hits: 1

  #Hooks for sling sequence pairs
  slings_l2r_hit:
    score: 250 #Sequence starting with left scores less because plunge start

  slings_r2l_hit:
    score: 555


sequence_shots:
  slings_l2r:
    switch_sequence: s_left_sling, s_right_sling
    sequence_timeout: 300ms
  slings_r2l:
    switch_sequence: s_right_sling, s_left_sling
    sequence_timeout: 300ms

ball_saves:
  default:
    active_time: 5s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    auto_launch: true
    balls_to_save: 1

timed_switches:
  ts_start_button:
    time: 3000ms
    switches:
      - s_start
