#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ending
  priority: 1000

config:
  - light_player.yaml
  - multiballs.yaml
  - virtual_hooks.yaml
  - achievement_hooks.yaml

slide_player:
  mode_base_started:
    base:
      action: play
    attract:
      action: remove

widget_player:
  mode_base_started:
    info_overlay:
      slide: _overlay
  mode_base_stopping:
    info_overlay:
      slide: _overlay
      action: remove
  player_playfield_multiplier:
    info_overlay:
      slide: _overlay
      action: update

event_player:
  mode_base_started:
    - flap_gates
    - manage_ball_scores
    - mode_start_backbox_controller
    - mode_start_scoring_mode_controller
    - mode_start_code_base
    - mode_start_priority_shows
    - mode_start_ball_saves
    - mode_start_loops_base
    - mode_start_orbits_base
    - mode_start_ramps_base
    - mode_start_skillshot_base
    - mode_start_slings_base
    - mode_start_lower_lanes_base
    - mode_start_vuks_base
    - mode_start_targets_base
    - mode_start_burnination_controller
    - mode_start_slots_controller
    - mode_start_spinners_base
    - mode_start_single_ball_combos # This will move out to the scoring controller when ball count matters
    # - dj_game_start|1800ms # BUG? it seems like it plays twice? Is the delay echoing?

  tilt_warning_1: [dj_tilt_warning_pool]
  tilt_warning_2: [dj_tilt_warning_pool]
  tilt: [dj_tilted]

  s_plunger_active: [dj_ball_at_launcher]
  increment_playfield_multiplier{current_player.playfield_multiplier < 5}: [dj_multiplier_added_pool]
  increment_bonus_multiplier{current_player.bonus_multiplier < 10}: [dj_bonus_multiplier_added_pool]

  manage_ball_scores:
    - update_previous_ball_score_from_current
    - reset_current_ball_score|1ms
  player_score: #subscribe to var updates
    - sync_ball_score

variable_player:
  player_points:
    score: change * current_player.playfield_multiplier

  update_player_ball_start:
    ball_start_time:
      float: timestamp
      action: set
    ball_end_time:
      float: -1
      action: set
  update_player_ball_end:
    ball_end_time:
      float: timestamp
      action: set

  update_previous_ball_score_from_current:
    previous_ball_score:
      action: set
      int: current_player.score
  reset_current_ball_score:
    ball_score:
      action: set
      int: 0
  sync_ball_score:
    ball_score:
      action: set
      int: current_player.score - current_player.previous_ball_score #TODO maybe can just use change to add it

  #Playfield multiplier always back down to 1 on new ball
  mode_base_started:
    playfield_multiplier:
      action: set
      int: 1
    bonus_multiplier:
      action: set
      int: 1
    half_spinner_spins:
      action: set
      int: 0

  #indirection so players can hook onto increment instead of the player var event
  increment_playfield_multiplier{current_player.playfield_multiplier < 5}:
    playfield_multiplier:
      action: add
      int: 1

  increment_bonus_multiplier{current_player.bonus_multiplier < 10}:
    bonus_multiplier:
      action: add
      int: 1

timed_switches:
  ts_start_button:
    time: 3000ms
    switches:
      - s_start
