#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_will_end
  priority: 1000

config:
  - light_player.yaml
  - mini_cab_multiball.yaml
  - virtual_hooks.yaml

slide_player:
  mode_base_started:
    base:
      action: play
  mode_base_started.1:
    attract:
      action: remove

event_player:
  s_start_active: [dj_cash]
  s_plunger_active: [dj_ball_at_launcher]
  increment_playfield_multiplier{current_player.playfield_multiplier < 5}: [dj_multiplier_added_pool]

  mode_base_started:
    - mode_start_backbox_controller
    - mode_start_code_base
    - mode_start_priority_shows
    - mode_start_ball_saves
    - mode_start_skillshot_base
    - mode_start_slings_base
    - mode_start_lower_lanes_base
    - mode_start_burnination_controller
    - mode_start_slots_controller
    - dj_game_start|1650ms

variable_player:
  #Playfield multiplier always back down to 1 on new ball
  mode_base_started:
    playfield_multiplier:
      action: set
      int: 1

  #indirection so players can hook onto increment instead of the player var event
  increment_playfield_multiplier{current_player.playfield_multiplier < 5}:
    playfield_multiplier:
      action: add
      int: 1

timed_switches:
  ts_start_button:
    time: 3000ms
    switches:
      - s_start
