#config_version=6

mode:
  start_events: ball_started
  priority: 100

variable_player:

  s_left_outer_lane_active:
    score: 999
  s_left_inner_lane_active:
    score: 100

  s_right_inner_lane_active:
    score: 100
  s_right_outer_lane_active:
    score: 999


  s_left_sling_active:
    score: 25
    sling_hits: 1
  s_right_sling_active:
    score: 50
    sling_hits: 1

accruals:
  cab_three_button_reset:
    events:
      - s_left_flipper_active
      - s_right_flipper_active
      - s_start_active
    disable_events:
      - s_left_flipper_inactive
      - s_right_flipper_inactive
      - s_start_inactive
    disable_on_complete: false
    events_when_complete: mini_cabinet_multiball_qualified

show_player:
  mini_cabinet_multiball_qualified:
    cabinet_multiball_flash:
      loops: 1

multiballs:
  cabinet_multiball:
    ball_count: 3
    ball_count_type: total
    enable_events: playfield_active
    disable_events: ball_ending
    start_events: mini_cabinet_multiball_qualified
    shoot_again: 7000ms
