#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ending
  priority: 1000

config:
  - light_player.yaml
  - mini_cab_multiball.yaml
  - virtual_hooks.yaml

slide_player:
  mode_base_started:
    base:
      action: play
    attract:
      action: remove
    tilt:
      action: remove
    tilt_warning_1:
      action: remove
    tilt_warning_2:
      action: remove

event_player:
  mode_base_started:
    - manage_ball_scores
    - mode_start_backbox_controller
    - mode_start_code_base
    - mode_start_priority_shows
    - mode_start_ball_saves
    - mode_start_skillshot_base
    - mode_start_slings_base
    - mode_start_lower_lanes_base
    - mode_start_burnination_controller
    - mode_start_slots_controller
    - mode_start_spinners_base
    - dj_game_start|1800ms

  tilt_warning: [dj_tilt_warning_pool]
  tilt: [dj_tilted]

  s_start_active: [dj_cash]
  s_plunger_active: [dj_ball_at_launcher]
  increment_playfield_multiplier{current_player.playfield_multiplier < 5}: [dj_multiplier_added_pool]

  manage_ball_scores:
    - update_previous_ball_score_from_current
    - reset_current_ball_score|1ms
  player_score: #subscribe to var updates
    - sync_ball_score

variable_player:
  update_previous_ball_score_from_current:
    previous_ball_score:
      action: set
      int: current_player.score
  reset_current_ball_score:
    ball_score:
      action: set
      int: 0
  sync_ball_score:
    ball_score:
      action: set
      int: current_player.score - current_player.previous_ball_score

  #Playfield multiplier always back down to 1 on new ball
  mode_base_started:
    playfield_multiplier:
      action: set
      int: 1
    half_spinner_spins:
      action: set
      int: 0

  #indirection so players can hook onto increment instead of the player var event
  increment_playfield_multiplier{current_player.playfield_multiplier < 5}:
    playfield_multiplier:
      action: add
      int: 1

timed_switches:
  ts_start_button:
    time: 3000ms
    switches:
      - s_start
