#config_version=6

show_player:
  mode_base_started:
    tokenized_ring_spin:
      show_tokens:
        l1: l_pop_ring_a_1
        l2: l_pop_ring_a_2
        l3: l_pop_ring_a_3
        l4: l_pop_ring_a_4
        l5: l_pop_ring_a_5
        l6: l_pop_ring_a_6
        l7: l_pop_ring_a_7
        l8: l_pop_ring_a_8
        level1: 0a0000
        level2: 1a0000
        level3: 220000
        level4: 441000
        level5: 662a10
        level6: 883333
  mode_base_will_stop:
    tokenized_ring_spin: stop

light_player:

  # High voltage status warn LED
  "{device.switches.s_high_voltage_status.state == 0}":
    l_pf_1: eee000
  "{device.switches.s_high_voltage_status.state == 1}":
    l_pf_1: ff0000


  #Minicab left status LED tracking button and EOS
  "{device.switches.s_left_flipper.state == 0 and device.switches.s_left_flipper_eos.state == 0}":
    l_mini_cab_left: off
  "{device.switches.s_left_flipper.state == 1 and device.switches.s_left_flipper_eos.state == 0}":
    l_mini_cab_left: "000099"
  "{device.switches.s_left_flipper.state == 0 and device.switches.s_left_flipper_eos.state == 1}":
    l_mini_cab_left: 990000
  "{device.switches.s_left_flipper.state == 1 and device.switches.s_left_flipper_eos.state == 1}":
    l_mini_cab_left: cc00cc

  #Minicab right status LED tracking button and EOS
  "{device.switches.s_right_flipper.state == 0 and device.switches.s_right_flipper_eos.state == 0}":
    l_mini_cab_right: off
  "{device.switches.s_right_flipper.state == 1 and device.switches.s_right_flipper_eos.state == 0}":
    l_mini_cab_right: "000099"
  "{device.switches.s_right_flipper.state == 0 and device.switches.s_right_flipper_eos.state == 1}":
    l_mini_cab_right: 990000
  "{device.switches.s_right_flipper.state == 1 and device.switches.s_right_flipper_eos.state == 1}":
    l_mini_cab_right: cc00cc

  #Minicab trough status LED tracking plunger switch and mini flip button
  "{device.switches.s_plunger.state == 0 and device.switches.s_mini_flipper.state == 0}":
    l_mini_cab_mini: off
  "{device.switches.s_plunger.state == 1 and device.switches.s_mini_flipper.state == 0}":
    l_mini_cab_mini: "009900"
  "{device.switches.s_plunger.state == 0 and device.switches.s_mini_flipper.state == 1}":
    l_mini_cab_mini: 990000
  "{device.switches.s_plunger.state == 1 and device.switches.s_mini_flipper.state == 1}":
    l_mini_cab_mini: cccc00


  # Trough status GI light
  "{device.switches.s_trough_ball_jam.state == 1}":
    l_pf_2: cc3333
  "{device.switches.s_trough_ball_jam.state == 0 and device.switches.s_trough_ball_1.state + device.switches.s_trough_ball_2.state + device.switches.s_trough_ball_3.state + device.switches.s_trough_ball_4.state + device.switches.s_trough_ball_5.state == 0}":
    l_pf_2: ff0000 #Empty is red
  "{device.switches.s_trough_ball_jam.state == 0 and device.switches.s_trough_ball_1.state + device.switches.s_trough_ball_2.state + device.switches.s_trough_ball_3.state + device.switches.s_trough_ball_4.state + device.switches.s_trough_ball_5.state == 1}":
    l_pf_2: 994400
  "{device.switches.s_trough_ball_jam.state == 0 and device.switches.s_trough_ball_1.state + device.switches.s_trough_ball_2.state + device.switches.s_trough_ball_3.state + device.switches.s_trough_ball_4.state + device.switches.s_trough_ball_5.state == 2}":
    l_pf_2: 557700
  "{device.switches.s_trough_ball_jam.state == 0 and device.switches.s_trough_ball_1.state + device.switches.s_trough_ball_2.state + device.switches.s_trough_ball_3.state + device.switches.s_trough_ball_4.state + device.switches.s_trough_ball_5.state == 3}":
    l_pf_2: 33aa00
  "{device.switches.s_trough_ball_jam.state == 0 and device.switches.s_trough_ball_1.state + device.switches.s_trough_ball_2.state + device.switches.s_trough_ball_3.state + device.switches.s_trough_ball_4.state + device.switches.s_trough_ball_5.state > 3}":
    l_pf_2: 0066ff #intended for 3 balls, so 4+ is unexpected blue state

