#config_version=6

event_player:
  mode_base_started:
    - start_post_ring_right_spin_red
    - start_post_ring_left_spin_blue
    - start_gi_base
  s_start_active:
    - stop_post_ring_right_spin_red
    - stop_post_ring_left_spin_blue
  s_start_inactive:
    - start_post_ring_right_spin_red
    - start_post_ring_left_spin_blue

show_player:
  start_gi_base:
    led_color:
      show_tokens:
        lights: lights_gi
        color: aaaaaa

  ts_start_button_active:
    light_ring_flash:
      key: post_ring_right_a_menu_flash_x3
      action: play
      speed: 2
      loops: 2
      show_tokens:
        lights: lights_sling_post_ring_right, lights_sling_post_ring_left
        color: orange

  stop_post_ring_right_spin_red:
    post_ring_right_red_spin:
      action: stop

  start_post_ring_right_spin_red:
    tokenized_ring_spin:
      action: play
      key: post_ring_right_red_spin
      show_tokens:
        # Asc order should spin CCW
        l1: l_sling_post_ring_right_1
        l2: l_sling_post_ring_right_2
        l3: l_sling_post_ring_right_3
        l4: l_sling_post_ring_right_4
        l5: l_sling_post_ring_right_5
        l6: l_sling_post_ring_right_6
        l7: l_sling_post_ring_right_7
        l8: l_sling_post_ring_right_8
        level1: 0a0000
        level2: 1a0000
        level3: 220000
        level4: 441000
        level5: 662a10
        level6: 883333
        level7: "000000"
        level8: "000000"

  stop_post_ring_left_spin_blue:
    post_ring_left_blue_spin:
      action: stop

  start_post_ring_left_spin_blue:
    tokenized_ring_spin:
      action: play
      key: post_ring_left_blue_spin
      show_tokens:
        # Reverse order should spin CW
        l1: l_sling_post_ring_left_8
        l2: l_sling_post_ring_left_7
        l3: l_sling_post_ring_left_6
        l4: l_sling_post_ring_left_5
        l5: l_sling_post_ring_left_4
        l6: l_sling_post_ring_left_3
        l7: l_sling_post_ring_left_2
        l8: l_sling_post_ring_left_1
        level1: 00000a
        level2: 00001a
        level3: "000022"
        level4: 100044
        level5: 2a1066
        level6: 333388
        level7: "000000"
        level8: "000000"

light_player:
  # Disabled due to no good light to choose for show
  # # High voltage status warn LED
  # "{device.switches.s_coin_door.state == 0}":
  #   gi_left_flipper_bottom: eee000
  # "{device.switches.s_coin_door.state == 1}":
  #   gi_left_flipper_bottom: ff0000

  #Minicab left status LED tracking button and EOS
  "{device.switches.s_left_flipper.state == 0 and device.switches.s_left_flipper_eos.state == 0}":
    l_mini_cab_left: off
  "{device.switches.s_left_flipper.state == 1 and device.switches.s_left_flipper_eos.state == 0}":
    l_mini_cab_left: "000099"
  "{device.switches.s_left_flipper.state == 0 and device.switches.s_left_flipper_eos.state == 1}":
    l_mini_cab_left: 990000
  "{device.switches.s_left_flipper.state == 1 and device.switches.s_left_flipper_eos.state == 1}":
    l_mini_cab_left: cc00cc

  #Minicab right status LED tracking button and EOS
  "{device.switches.s_right_flipper.state == 0 and device.switches.s_right_flipper_eos.state == 0}":
    l_mini_cab_right: off
  "{device.switches.s_right_flipper.state == 1 and device.switches.s_right_flipper_eos.state == 0}":
    l_mini_cab_right: "000099"
  "{device.switches.s_right_flipper.state == 0 and device.switches.s_right_flipper_eos.state == 1}":
    l_mini_cab_right: 990000
  "{device.switches.s_right_flipper.state == 1 and device.switches.s_right_flipper_eos.state == 1}":
    l_mini_cab_right: cc00cc

  #Minicab trough status LED tracking plunger switch and mini flip button
  "{device.switches.s_plunger.state == 0 and device.switches.s_left_flipper_secondary.state == 0}":
    l_mini_cab_left_secondary: off
  "{device.switches.s_plunger.state == 1 and device.switches.s_left_flipper_secondary.state == 0}":
    l_mini_cab_left_secondary: "009900"
  "{device.switches.s_plunger.state == 0 and device.switches.s_left_flipper_secondary.state == 1}":
    l_mini_cab_left_secondary: 990000
  "{device.switches.s_plunger.state == 1 and device.switches.s_left_flipper_secondary.state == 1}":
    l_mini_cab_left_secondary: cccc00

  #Minicab right secondary status LED tracking button and EOS
  "{device.switches.s_right_flipper_secondary.state == 0}":
    l_mini_cab_right_secondary: off
  "{device.switches.s_right_flipper_secondary.state == 1}":
    l_mini_cab_right_secondary: cc00cc

  #Start button lights by default and turns off when pressed
  "{device.switches.s_start.state == 0}":
    l_start: on
  "{device.switches.s_start.state == 1}":
    l_start: off

  # Disabled due to no good light to choose for show
  # # Trough status GI light
  # "{device.switches.s_trough_ball_jam.state == 1}":
  #   gi_sling_left_bottom: cc3333
  # "{device.switches.s_trough_ball_jam.state == 0 and device.switches.s_trough_ball_1.state + device.switches.s_trough_ball_2.state + device.switches.s_trough_ball_3.state + device.switches.s_trough_ball_4.state + device.switches.s_trough_ball_5.state == 0}":
  #   gi_sling_left_bottom: ff0000 #Empty is red
  # "{device.switches.s_trough_ball_jam.state == 0 and device.switches.s_trough_ball_1.state + device.switches.s_trough_ball_2.state + device.switches.s_trough_ball_3.state + device.switches.s_trough_ball_4.state + device.switches.s_trough_ball_5.state == 1}":
  #   gi_sling_left_bottom: 994400
  # "{device.switches.s_trough_ball_jam.state == 0 and device.switches.s_trough_ball_1.state + device.switches.s_trough_ball_2.state + device.switches.s_trough_ball_3.state + device.switches.s_trough_ball_4.state + device.switches.s_trough_ball_5.state == 2}":
  #   gi_sling_left_bottom: 557700
  # "{device.switches.s_trough_ball_jam.state == 0 and device.switches.s_trough_ball_1.state + device.switches.s_trough_ball_2.state + device.switches.s_trough_ball_3.state + device.switches.s_trough_ball_4.state + device.switches.s_trough_ball_5.state == 3}":
  #   gi_sling_left_bottom: 33aa00
  # "{device.switches.s_trough_ball_jam.state == 0 and device.switches.s_trough_ball_1.state + device.switches.s_trough_ball_2.state + device.switches.s_trough_ball_3.state + device.switches.s_trough_ball_4.state + device.switches.s_trough_ball_5.state > 3}":
  #   gi_sling_left_bottom: 0066ff #intended for 3 balls, so 4+ is unexpected blue state

  # Playfield Multiplier
  "{current_player.playfield_multiplier == 2}":
    l_pf_x2: ff0000
  "{current_player.playfield_multiplier != 2}":
    l_pf_x2: off
  "{current_player.playfield_multiplier == 3}":
    l_pf_x3: ff0000
  "{current_player.playfield_multiplier != 3}":
    l_pf_x3: off
  "{current_player.playfield_multiplier == 4}":
    l_pf_x4: ff0000
  "{current_player.playfield_multiplier != 4}":
    l_pf_x4: off
  "{current_player.playfield_multiplier == 5}":
    l_pf_x5: ff0000
  "{current_player.playfield_multiplier != 5}":
    l_pf_x5: off
