#config_version=6

multiballs:
  cabinet_multiball:
    ball_count: 3
    ball_count_type: total
    enable_events: playfield_active
    disable_events: ball_ending
    start_events: mini_cabinet_multiball_qualified
    shoot_again: 7000ms

  burnination_multiball:
    ball_count: 3
    ball_count_type: total
    enable_events: playfield_active, burnination_controller_begin
    disable_events: ball_ending, mode_stop_burnination_rollovers
    start_events: burnination_multiball_qualified
    shoot_again: settings.burnination_timer_seconds*1000 #Uses the base setting but does not increment like the overall timer does

  skillshot_addaball:
    ball_count: 1
    ball_count_type: add
    enable_events: ball_starting
    disable_events: ball_ending
    start_events: skillshot_addaball_qualified
    shoot_again: 5000ms

  cheat_multiball:
    ball_count: 1
    ball_count_type: add
    enable_events: cheat_multiball_qualified
    start_events: cheat_multiball_begin
    shoot_again: 3000ms #only intended to save the captured ball

combo_switches:
  cab_two_button_reset: # Press both cab buttons to max for 2.5s to trigger multiball
    # events_when_both: mini_cabinet_multiball_qualified # Disable the cheat multiball lol
    switches_1: s_left_flipper_secondary
    switches_2: s_right_flipper_secondary
    hold_time: 2500ms
    max_offset_time: 200ms

show_player:
  mini_cabinet_multiball_qualified:
    cabinet_multiball_flash:
      loops: 1 # Should play TWICE

event_player:
  cheat_multiball_qualified:
    - show_cheat_multiball_qualified_overlay
    - dj_special_cheat_multiball_qualified
    - hide_cheat_multiball_qualified_overlay|4000ms
  multiball_cheat_multiball_started:
    - hide_cheat_multiball_qualified_overlay
    - show_cheat_multiball_started_overlay
    - hide_cheat_multiball_started_overlay|4000ms
    - dj_special_cheat_multiball
#     - flash gi and backbox all yellow

  multiball_cheat_multiball_ended:
    - reset_cheat_multiball_qualifying_spins

widget_player:
  show_cheat_multiball_qualified_overlay: cheat_multiball_qualified_overlay
  hide_cheat_multiball_qualified_overlay:
    cheat_multiball_qualified_overlay:
      action: remove
  show_cheat_multiball_started_overlay: cheat_multiball_started_overlay
  hide_cheat_multiball_started_overlay:
    cheat_multiball_started_overlay:
      action: remove
