#config_version=6

event_player:
  vswitch_end_game_active:
    - end_game

  vswitch_qualify_burnination_active:
    - burn_group_lit_complete

  vswitch_add_fire_level_active:
    - virtual_add_10_fire_all

  vswitch_qualify_burninated_active:
    - mode_complete_pops_burnination

  vswitch_qualify_left_outlane_save_active:
    - qualify_left_outlane_save


variable_player:
  virtual_add_10_fire_all:
    pop_right_fire_level:
      int: 10
      action: add
    pop_left_fire_level:
      int: 10
      action: add
    pop_center_fire_level:
      int: 10
      action: add
