#config_version=6

#Native cabinet switches on 0024 Cabinet IO board
switches:
## J1 Cabinet Left
  s_start:
    number: 0024-8
    tags: start

  s_left_flipper:
    number: 0024-10
    tags: left_flipper
  s_left_flipper_secondary:
    number: 0024-11
    tags: mini_flipper

  s_tilt_bob:
    number: 0024-15
    tags: tilt_warning

## J9 Cabinet Right
  s_right_flipper:
    number: 0024-16
    tags: right_flipper
  s_right_flipper_secondary:
    number: 0024-17

## J4 Coin Door # NOTE: not actually connected yet
  s_coin_door:
    number: 0024-0
    tags: service_door_open
  s_coin_door_service_1:
    number: 0024-7
    tags: service_esc
  s_coin_door_service_2:
    number: 0024-6
    tags: service_down
  s_coin_door_service_3:
    number: 0024-5
    tags: service_up
  s_coin_door_service_4:
    number: 0024-4
    tags: service_enter
