#config_version=6

# Switches that exist in the plan but are not yet physically installed

switches:
  #Targets
  s_drop_left_down: #TODO likely remove
    number: 807
    platform: smart_virtual

  #Passthrough optos
  s_left_orbit:
    number: 814
    platform: smart_virtual
    tags: playfield_active
  s_right_orbit:
    number: 815
    platform: smart_virtual
    tags: playfield_active
  s_horseshoe:
    number: 816
    platform: smart_virtual
    tags: playfield_active

  s_wireform_s_entry:
    number: 817
    platform: smart_virtual
    tags: playfield_active
  s_wireform_s_exit:
    number: 818
    platform: smart_virtual
    tags: playfield_active
  s_wireform_left_top:
    number: 819
    platform: smart_virtual
    tags: playfield_active
  s_wireform_right_top:
    number: 820
    platform: smart_virtual
    tags: playfield_active

  s_captive_ball_target:
    number: 824
    platform: smart_virtual
    tags: playfield_active
  s_captive_ball_presence: #Opto, normally blocked when undisturbed
    number: 825
    platform: smart_virtual
