#config_version=6

# Switches that exist in the plan but are not yet physically installed

switches:
  s_orbit_diverter_eos:
    number: 801
    platform: virtual
    type: 'NO'

  s_left_orbit_inner:
    number: 802
    platform: virtual
    tags: playfield_active
  s_right_orbit_inner:
    number: 803
    platform: virtual
    tags: playfield_active

  # Right wireform proxy entrance
  s_wireform_right_entrance:
    number: 804
    platform: virtual
    tags: playfield_active

  # Other proxy switches
  s_right_outlane_lower:
    number: 806
    platform: virtual

  s_drop_bank_stuck_ball_detector:
    number: 888
    platform: virtual
