#config_version=6

#Cabinet switches WHILE ON 3208!
switches:
## J8
  s_left_flipper_secondary:
    number: 3208-0
    tags: mini_flipper

  s_left_flipper:
    number: 3208-1
    tags: left_flipper

  s_right_flipper:
    number: 3208-3
    tags: right_flipper

  s_start:
    number: 3208-4
    tags: start

## Unsupported in minicab:
  s_right_flipper_secondary:
    number: 850
    platform: smart_virtual
  s_tilt_bob:
    number: 851
    platform: smart_virtual
    tags: tilt_warning

