#config_version=6

#Cabinet switches WHILE ON 3208!
switches:
## 3208:J8
  s_left_flipper_secondary:
    number: 3208-0
    tags: mini_flipper

  s_left_flipper:
    number: 3208-1
    tags: left_flipper

  s_right_flipper:
    number: 3208-3
    tags: right_flipper

  s_start:
    number: 3208-4
    tags: start

## 3208:J3
  s_coin_door:
    number: 3208-8

## Unsupported in minicab:
  s_right_flipper_secondary:
    number: 850
    platform: smart_virtual
  s_tilt_bob:
    number: 851
    platform: smart_virtual
    tags: tilt_warning

  s_coin_door_service_1:
    number: 852
    platform: smart_virtual
    tags: service_esc
  s_coin_door_service_2:
    number: 853
    platform: smart_virtual
    tags: service_down
  s_coin_door_service_3:
    number: 854
    platform: smart_virtual
    tags: service_up
  s_coin_door_service_4:
    number: 855
    platform: smart_virtual
    tags: service_enter
