#config_version=6

switches:

#IO 3208
## J8
  s_vuk_presence:
    number: 3208-0
    type: 'NC'
    # tags: playfield_active #TODO maybe needed

  s_spinner_right:
    number: 3208-1
    tags: playfield_active

  s_wireform_right_top:
    number: 3208-2
    type: 'NC'
    tags: playfield_active

  # 3 4 5 6 available

  s_spinner_left:
    number: 3208-7
    tags: playfield_active

## J3
  # s_coin_door:
  #   number: 3208-8 # Disconnect provided on J3 header, but declared in cabinet or minicab switch configs

  # s_proximity_test:
  #   number: 3208-8
  #   tags: playfield_active # Also used switch 8 as an easy disconnect test input

  s_upper_flipper_eos:
    number: 3208-9
    type: 'NC'

  # 10 available

  s_left_outer_lane:
    number: 3208-11
    tags: playfield_active

  s_left_inner_lane:
    number: 3208-12
    tags: playfield_active

  s_left_flipper_eos:
    number: 3208-13
    type: 'NC'

  # 14 available

  s_left_sling: # Parallel switch pair
    number: 3208-15

## J6
  s_trough_ball_1:
    number: 3208-16
    type: 'NC'

  s_trough_ball_jam:
    number: 3208-17
    type: 'NC'

  s_trough_ball_2:
    number: 3208-18

  s_trough_ball_3:
    number: 3208-19

  s_trough_ball_4:
    number: 3208-20

  s_trough_ball_5:
    number: 3208-21

  # 22 23 available

## J9
  # 24 available

  s_right_outer_lane:
    number: 3208-25
    tags: playfield_active

  s_right_inner_lane:
    number: 3208-26
    tags: playfield_active

  # 27 available

  s_right_flipper_eos:
    number: 3208-28
    type: 'NC'

  s_right_sling: # Parallel switch pair
    number: 3208-29

  s_plunger: # shooter lane presence
    number: 3208-31


#IO 1616
## J7
  s_burn_n:
    number: 1616-0
    tags: playfield_active
  s_burn_r:
    number: 1616-1
    tags: playfield_active
  s_burn_u:
    number: 1616-2
    tags: playfield_active
  s_burn_b:
    number: 1616-3
    tags: playfield_active
  s_burn_standup:
    number: 1616-4
    tags: playfield_active
  # 5 6 7 available

## J8
  s_pop_left:
    number: 1616-8
  s_pop_center:
    number: 1616-9
  s_pop_right:
    number: 1616-10

  # 11 available

  s_orbit_diverter_eos:
    number: 1616-12
    type: 'NO'

  s_drop_bank_right:
    number: 1616-13
    type: 'NC'
  s_drop_bank_center:
    number: 1616-14
    type: 'NC'
  s_drop_bank_left:
    number: 1616-15
    type: 'NC'

# Starting balls when virtual
virtual_platform_start_active_switches:
  - s_trough_ball_1
  - s_trough_ball_2
  - s_trough_ball_3

# Audio warning on coin door open/close
event_player:
  s_coin_door_active: [dj_high_voltage_enabled]
  s_coin_door_inactive: [dj_high_voltage_disabled]
