#config_version=6

switches:

#IO 3208
## J9
  s_right_outer_lane:
    number: 3208-25
    tags: playfield_active

  s_right_inner_lane:
    number: 3208-26
    tags: playfield_active

  s_right_flipper_eos:
    number: 3208-28
    type: 'NC'

  s_right_sling: # Parallel switch pair
    number: 3208-29

  s_plunger: # shooter lane presence
    number: 3208-31

## J3
  s_high_voltage_status:
    number: 3208-8

  s_left_outer_lane:
    number: 3208-11
    tags: playfield_active

  s_left_inner_lane:
    number: 3208-12
    tags: playfield_active

  s_left_flipper_eos:
    number: 3208-13
    type: 'NC'

  s_left_sling: # Parallel switch pair
    number: 3208-15

## J6
  s_trough_ball_jam:
    number: 3208-17
    type: 'NC'

  s_trough_ball_1:
    number: 3208-16
    type: 'NC'

  s_trough_ball_2:
    number: 3208-18

  s_trough_ball_3:
    number: 3208-19

  s_trough_ball_4:
    number: 3208-20

  s_trough_ball_5:
    number: 3208-21

#IO 1616
## J7
  s_burn_standup:
    number: 1616-4
    tags: playfield_active
  s_burn_b:
    number: 1616-3
    tags: playfield_active
  s_burn_u:
    number: 1616-2
    tags: playfield_active
  s_burn_r:
    number: 1616-1
    tags: playfield_active
  s_burn_n:
    number: 1616-0
    tags: playfield_active
  s_spinner_left:
    number: 1616-15
    tags: playfield_active


# Starting balls when virtual
virtual_platform_start_active_switches:
  - s_trough_ball_1
  - s_trough_ball_2
  - s_trough_ball_3

# Audio warning on coin door open/close
event_player:
  s_high_voltage_status_active: [dj_high_voltage_enabled]
  s_high_voltage_status_inactive: [dj_high_voltage_disabled]
