#config_version=6

# Switches used in mpf monitor to issue artificial mode qualification events

switches:
  vswitch_end_game:
    platform: smart_virtual
    number: 901

  vswitch_qualify_burnination:
    platform: smart_virtual
    number: 902

  vswitch_add_fire_level:
    platform: smart_virtual
    number: 903

  vswitch_qualify_burninated:
    platform: smart_virtual
    number: 904

  vswitch_qualify_left_outlane_save:
    platform: smart_virtual
    number: 905

  vswitch_qualify_right_outlane_save:
    platform: smart_virtual
    number: 906

  vswitch_reset_inlane_detector:
    platform: smart_virtual
    number: 907

  vswitch_toggle_slings_dead:
    platform: smart_virtual
    number: 908

  vswitch_toggle_slots:
    platform: smart_virtual
    number: 909

  vswitch_plunger_power_1:
    platform: smart_virtual
    number: 991
  vswitch_plunger_power_2:
    platform: smart_virtual
    number: 992
  vswitch_plunger_power_3:
    platform: smart_virtual
    number: 993
  vswitch_plunger_power_4:
    platform: smart_virtual
    number: 994
  vswitch_plunger_power_5:
    platform: smart_virtual
    number: 995
  vswitch_plunger_power_6:
    platform: smart_virtual
    number: 996

  vswitch_enable_left_cbg:
    platform: smart_virtual
    number: 920
  vswitch_disable_left_cbg:
    platform: smart_virtual
    number: 921
  vswitch_enable_right_cbg:
    platform: smart_virtual
    number: 922
  vswitch_disable_right_cbg:
    platform: smart_virtual
    number: 923
  vswitch_enable_right_cbg_alt:
    platform: smart_virtual
    number: 926
  vswitch_disable_right_cbg_alt:
    platform: smart_virtual
    number: 927

  vswitch_enable_spinner_targets:
    platform: smart_virtual
    number: 950
  vswitch_disable_spinner_targets:
    platform: smart_virtual
    number: 951

  vswitch_test_coils:
    platform: smart_virtual
    number: 999


event_player:
  vswitch_enable_left_cbg_active: [enable_left_controlled_ball_gate]
  vswitch_disable_left_cbg_active: [disable_left_controlled_ball_gate]
  vswitch_enable_right_cbg_active: [enable_right_controlled_ball_gate]
  vswitch_disable_right_cbg_active: [disable_right_controlled_ball_gate]
  vswitch_enable_right_cbg_alt_active: [enable_right_controlled_ball_gate_alternative_profile]
  vswitch_disable_right_cbg_alt_active: [disable_right_controlled_ball_gate_alternative_profile]
  vswitch_disable_spinner_targets_active: [spinner_controller_unset_left_target, spinner_controller_unset_right_target]
  vswitch_enable_spinner_targets_active: [spinner_controller_set_left_target, spinner_controller_set_right_target]

coil_player:
  vswitch_plunger_power_1_active:
    c_auto_plunger:
      pulse_ms: 6
  vswitch_plunger_power_2_active:
    c_auto_plunger:
      pulse_ms: 9
  vswitch_plunger_power_3_active:
    c_auto_plunger:
      pulse_ms: 15
  vswitch_plunger_power_4_active:
    c_auto_plunger:
      pulse_ms: 21
  vswitch_plunger_power_5_active:
    c_auto_plunger:
      pulse_ms: 28
  vswitch_plunger_power_6_active:
    c_auto_plunger:
      pulse_ms: 36

show_player:
  vswitch_test_coils_active:
    coil_cycle_test:
      loops: 1

plugins: switch_player
switch_player:
  start_event: vswitch_end_game_active
  steps:
    # Clear plunger lane and space in back of trough
    - time: 1ms
      switch: s_plunger
      action: deactivate
    - time: 1ms
      switch: s_trough_ball_5
      action: deactivate
    - time: 1ms
      switch: s_trough_ball_4
      action: deactivate
    - time: 1ms
      switch: s_trough_ball_3
      action: deactivate

    # Ensure trough start is prepared
    - time: 1ms
      switch: s_trough_ball_2
      action: activate
    - time: 1ms
      switch: s_trough_ball_1
      action: activate

    # Send a fake ball through the trough to trick ball detection, resting at 3
    - time: 10ms
      switch: s_trough_ball_5
      action: activate
    - time: 1ms
      switch: s_trough_ball_5
      action: deactivate
    - time: 1ms
      switch: s_trough_ball_3
      action: activate
