#config_version=6

mode:
  start_events: mode_start_lower_lanes_base
  stop_events: mode_cancel_lower_lanes_base
  priority: 1110

variable_player:
  inlane_detector_shot_off_hit:
    score: 100 * current_player.playfield_multiplier
  inlane_detector_shot_qualified_hit: # Probable schatz
    score: 2000 * current_player.playfield_multiplier

shot_profiles:
  inlane_detector_profile:
    advance_on_hit: true
    block: false
    states:
      - name: 'off'
        show: 'off'
      - name: 'qualified'
        show: on_color
        show_tokens:
          color: green

shots:
  inlane_detector_shot:
    profile: inlane_detector_profile
    switches: s_left_inner_lane, s_right_inner_lane
    reset_events: reset_inlane_detector
#    show_tokens:
#      light: vlight_inlane_qualified

event_player:
  vswitch_reset_inlane_detector_active:
    - reset_inlane_detector
