#config_version=6

mode:
  start_events: mode_start_lower_lanes_base
  stop_events: mode_stop_lower_lanes_base, ball_will_end
  priority: 1510

variable_player:
  inlane_detector_shot_off_hit:
    points: 100
    rollover_hits: 1
  inlane_detector_shot_qualified_hit: # Probable schatz
    points: 750
    rollover_hits: 1

shot_profiles:
  inlane_detector_profile:
    advance_on_hit: True
    block: False
    states:
      - name: 'off'
        show: 'off'
      - name: 'qualified'
        show: on_color
        show_tokens:
          color: green

shots:
  left_inlane_detector_shot:
    profile: inlane_detector_profile
    switches: s_left_inner_lane
    reset_events: reset_inlane_detectors
    show_tokens:
      light: vlight_left_inlane_qualified
  right_inlane_detector_shot:
    profile: inlane_detector_profile
    switches: s_right_inner_lane
    reset_events: reset_inlane_detectors
    show_tokens:
      light: vlight_right_inlane_qualified

event_player:
  vswitch_reset_inlane_detector_active:
    - reset_inlane_detectors

  inlane_detector_shot_off_hit:       [dj_TODO]
  inlane_detector_shot_qualified_hit: [dj_TODO]

  # Basic implementation of lane qual rollover opening upper gate for loop shot
  # Should become a state machine (elsewhere) to manage gate state and a request to the machine from here
  left_inlane_detector_shot_qualified_hit:
    - enable_left_controlled_ball_gate
    - activate_left_controlled_ball_gate|10ms
  right_inlane_detector_shot_qualified_hit:
    - enable_right_controlled_ball_gate
    - activate_right_controlled_ball_gate|10ms
