#config_version=6

mode:
  start_events: mode_start_priority_shows
  priority: 1000

show_player:
  priority_show_skillshot_success:
    skillshot_success:
      action: play
      loops: 2

  ball_save_default_timer_start:
    ball_save_on:
      action: play
      key: ball_save_show
  ball_save_default_hurry_up:
    ball_save_flash:
      action: play
      key: ball_save_show
  ball_save_default_disabled:
    ball_save_show:
      action: stop

