#config_version=6

mode:
  start_events: mode_start_priority_shows
  priority: 9000

show_player:
  priority_show_skillshot_success:
    skillshot_success:
      loops: 2

#  ball_save_default_timer_start:
#    ball_save_on:
#      key: center_ball_save_show
#      show_tokens:
#        color: blue
#  ball_save_default_hurry_up:
#    ball_save_flash:
#      key: center_ball_save_show
#      show_tokens:
#        color: blue
  # ball_save_default_disabled:
  #   center_ball_save_show:
  #     action: stop
  ball_save_default_timer_complete:
    center_ball_save_show:
      action: stop

  ball_save_short_timer_start:
    ball_save_on:
      key: center_ball_save_show
      show_tokens:
        color: yellow
  ball_save_short_hurry_up:
    ball_save_flash:
      key: center_ball_save_show
      show_tokens:
        color: yellow
  ball_save_short_disabled:
    center_ball_save_show:
      action: stop

  ball_save_left_outlane_saver_timer_start:
    ball_save_on:
      key: center_ball_save_show
      show_tokens:
        color: orange
  ball_save_left_outlane_saver_hurry_up:
    ball_save_flash:
      key: center_ball_save_show
      show_tokens:
        color: orange
  ball_save_left_outlane_saver_disabled:
    center_ball_save_show:
      action: stop

  ball_save_right_outlane_saver_timer_start:
    ball_save_on:
      key: center_ball_save_show
      show_tokens:
        color: purple
  ball_save_right_outlane_saver_hurry_up:
    ball_save_flash:
      key: center_ball_save_show
      show_tokens:
        color: purple
  ball_save_right_outlane_saver_disabled:
    center_ball_save_show:
      action: stop

  slots_party_time:
    slots_party_show:
      key: slots_grid_show
      loops: 3

  slots_celebrate_diagonal:
    slots_diagonal_result_show:
      key: slots_grid_show
      loops: 2

  slots_celebrate_row:
    slots_row_result_show:
      key: slots_grid_show
      loops: 2

  slots_celebrate_pair:
    slots_pair_result_show:
      key: slots_grid_show
      loops: 1

  slots_celebrate_split_pair:
    slots_split_pair_result_show:
      key: slots_grid_show
      loops: 1

  slots_celebrate_single:
    slots_single_result_show:
      key: slots_grid_show
      loops: 1

  slots_stop_show:
    slots_grid_show:
      action: stop
