#config_version=6

mode:
  priority: 7788 #TODO
  start_events: mode_start_orbits_base
  stop_events: mode_stop_orbits_base, ball_will_end

event_player:
  base_right_orbit_open_hit: [deactivate_orbit_diverter, deactivate_orbit_diverter_skillshot]

variable_player:
  base_orbit_open_group_hit:
    score: 2000 * current_player.playfield_multiplier
    orbit_hits: 1
  base_orbit_closed_group_hit:
    score: 1000 * current_player.playfield_multiplier
    orbit_hits: 1

shot_profiles:
  orbit_base_profile:
    advance_on_hit: False
    states:
      - name: singleton

shots:
  base_left_orbit_open:
    profile: orbit_base_profile
    hit_events: ss_left_orbit_open_hit
  base_left_orbit_closed:
    profile: orbit_base_profile
    hit_events: ss_left_orbit_closed_hit
  base_right_orbit_open:
    profile: orbit_base_profile
    hit_events: ss_right_orbit_open_hit
  base_right_orbit_closed:
    profile: orbit_base_profile
    hit_events: ss_right_orbit_closed_hit

shot_groups:
  base_orbit_open_group:
    shots:
      - base_left_orbit_open
      - base_right_orbit_open
  base_orbit_closed_group:
    shots:
      - base_left_orbit_closed
      - base_right_orbit_closed
