#config_version=6

mode:
  priority: 7777 #TODO
  start_events: mode_start_loops_base
  stop_events: mode_stop_loops_base, ball_will_end

event_player:
  mode_loops_base_started: [enable_orbit_diverter]
  base_left_uturn_hit:  [activate_orbit_diverter] # combo from upper loop
  upper_elbow_hit:      [activate_orbit_diverter] # rare occasion to open diverter
  ss_subway_travel_hit: [activate_orbit_diverter] # VUK eject loop combo
  base_loop_group_hit:  [dj_TODO]

variable_player:
  left_uturn_hit:
    points: 2000
  right_uturn_hit:
    points: 1000
  lower_elbow_hit:
    points: 1500
  upper_elbow_hit:
    points: 2222

  base_loop_group_hit:
    loop_hits: 1

shot_profiles:
  loop_base_profile:
    advance_on_hit: False
    states:
      - name: singleton

shots:
  base_left_uturn:
    profile: loop_base_profile
    hit_events: ss_horseshoe_clockwise_hit
  base_right_uturn:
    profile: loop_base_profile
    hit_events: ss_horseshoe_widdershins_hit
  base_lower_elbow:
    profile: loop_base_profile
    hit_events: ss_elbow_upwards_hit
  base_upper_elbow:
    profile: loop_base_profile
    hit_events: ss_elbow_downwards_hit

shot_groups:
  base_loop_group:
    shots:
      - base_left_uturn
      - base_right_uturn
      - base_lower_elbow
      - base_upper_elbow
