#config_version=6

mode:
  start_events: mode_start_targets_base
  stop_events: mode_stop_targets_base, ball_will_end
  priority: 1570

variable_player:
  sw_blue_standup:
    target_hits: 1
    score: 100 * current_player.playfield_multiplier
