#config_version=6

mode:
  start_events: mode_start_targets_base
  stop_events: mode_stop_targets_base, ball_will_end
  priority: 1570

event_player:
  sw_blue_standup: [dj_peasant_hit_pool]
  s_burn_standup_active: [dj_TODO]

variable_player:
  sw_blue_standup:
    target_hits: 1
    points: 100
  s_burn_standup_active:
    target_hits: 1
    score: 5000 # Hopefully it can score and get multiplied points in one
    points: 1000
