#config_version=6

mode:
  start_events: mode_start_slings_dead
  stop_events: mode_stop_slings_dead
  priority: 1250
  events_when_started: disable_slings
  events_when_stopped: enable_slings

variable_player:
  s_left_sling_active:
    score: 999|block
    sling_hits: 0|block
  s_right_sling_active:
    score: 999|block
    sling_hits: 0|block

event_player:
  mode_slings_dead_started: [enable_right_outlane_post, enable_saver_post]
  mode_slings_dead_will_stop: [disable_right_outlane_post, disable_saver_post]
  s_left_sling_active: [activate_right_outlane_post]
  s_right_sling_active: [activate_saver_post]
