#config_version=6

# Just putting one light per entire section for now,
# as the code will generally just use tags to set
# entire sections at once instead of individuall addressing

lights:
  # Test strip on neuron:
  l_test_1:
    number: neuron-4-1
    type: rgb
    tags: lights_bb, lights_bb_trogdor, lights_2a

  l_test_2:
    number: neuron-4-2
    type: rgb
    tags: lights_bb, lights_bb_flames, lights_2b

  l_test_3:
    number: neuron-4-3
    type: rgb
    tags: lights_bb, lights_bb_characters, lights_2a

  # Letters: TROGDOR! - note two O's and R's
  l_bb_trogdor_t_1:
    number: 7700
    platform: smart_virtual
    type: rgb
    tags: lights_bb, lights_bb_trogdor, lights_bb_trogdor_t

  l_bb_trogdor_r_1:
    number: 7702
    platform: smart_virtual
    type: rgb
    tags: lights_bb, lights_bb_trogdor, lights_bb_trogdor_r

  l_bb_trogdor_o_1:
    number: 7704
    platform: smart_virtual
    type: rgb
    tags: lights_bb, lights_bb_trogdor, lights_bb_trogdor_o

  l_bb_trogdor_g_1:
    number: 7706
    platform: smart_virtual
    type: rgb
    tags: lights_bb, lights_bb_trogdor, lights_bb_trogdor_g

  l_bb_trogdor_d_1:
    number: 7708
    platform: smart_virtual
    type: rgb
    tags: lights_bb, lights_bb_trogdor, lights_bb_trogdor_d

  l_bb_trogdor_o2_1:
    number: 7710
    platform: smart_virtual
    type: rgb
    tags: lights_bb, lights_bb_trogdor, lights_bb_trogdor_o2

  l_bb_trogdor_r2_1:
    number: 7712
    platform: smart_virtual
    type: rgb
    tags: lights_bb, lights_bb_trogdor, lights_bb_trogdor_r2

  l_bb_trogdor_!_1:
    number: 7714
    platform: smart_virtual
    type: rgb
    tags: lights_bb, lights_bb_trogdor, lights_bb_trogdor_bang

  # Characters: Trogdor, Knight, Peasant
  l_bb_character_trogdor_1: #5-10?
    number: 7720
    platform: smart_virtual
    type: rgb
    default_on_color: green
    tags: lights_bb, lights_bb_characters, lights_bb_char_trogdor

  l_bb_character_knight_1: #3-8?
    number: 7730
    platform: smart_virtual
    type: rgb
    default_on_color: blue
    tags: lights_bb, lights_bb_characters, lights_bb_char_knight

  l_bb_character_peasant_1: #3-8?
    number: 7740
    platform: smart_virtual
    type: rgb
    default_on_color: tan
    tags: lights_bb, lights_bb_characters, lights_bb_char_peasant

  # Flames: Trog breath, peasant head, background
  l_bb_flame_trogdor_outer_1: #2-5?
    number: 7750
    platform: smart_virtual
    type: rgb
    default_on_color: yellow
    tags: lights_bb, lights_bb_flames, lights_bb_flames_trogdor, lights_bb_flames_trogdor_outer

  l_bb_flame_trogdor_inner_1: #2-4?
    number: 7755
    platform: smart_virtual
    type: rgb
    default_on_color: orange
    tags: lights_bb, lights_bb_flames, lights_bb_flames_trogdor, lights_bb_flames_trogdor_inner

  l_bb_flame_peasant_1: #2-4?
    number: 7760
    platform: smart_virtual
    type: rgb
    default_on_color: yellow
    tags: lights_bb, lights_bb_flames, lights_bb_flames_peasant

  l_bb_flame_background_bottom_1: #7-14?
    number: 7770
    platform: smart_virtual
    type: rgb
    default_on_color: red
    tags: lights_bb, lights_bb_flames, lights_bb_flames_background, lights_bb_flames_background_bottom

  l_bb_flame_background_top_1: #5-10?
    number: 7790
    platform: smart_virtual
    type: rgb
    default_on_color: red
    tags: lights_bb, lights_bb_flames, lights_bb_flames_background, lights_bb_flames_background_top

  # Backbox GI
  l_bb_gi_1: #5-32?
    number: 7800
    platform: smart_virtual
    type: rgb
    tags: lights_bb, lights_bb_gi, lights_gi

  # full strip, top
  l_bb_edge_top_1:
    number: neuron-1-1
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_2:
    number: neuron-1-2
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_3:
    number: neuron-1-3
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_4:
    number: neuron-1-4
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_5:
    number: neuron-1-5
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_6:
    number: neuron-1-6
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_7:
    number: neuron-1-7
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_8:
    number: neuron-1-8
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_9:
    number: neuron-1-9
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_10:
    number: neuron-1-10
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_11:
    number: neuron-1-11
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_12:
    number: neuron-1-12
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_13:
    number: neuron-1-13
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_14:
    number: neuron-1-14
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_15:
    number: neuron-1-15
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_16:
    number: neuron-1-16
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_17:
    number: neuron-1-17
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_18:
    number: neuron-1-18
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_top
  l_bb_edge_top_19:
    number: neuron-1-19
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_top

  l_bb_edge_right_1:
    number: neuron-1-20
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_2:
    number: neuron-1-21
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_3:
    number: neuron-1-22
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_4:
    number: neuron-1-23
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_5:
    number: neuron-1-24
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_6:
    number: neuron-1-25
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_7:
    number: neuron-1-26
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_8:
    number: neuron-1-27
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_9:
    number: neuron-1-28
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_10:
    number: neuron-1-29
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_11:
    number: neuron-1-30
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_12:
    number: neuron-1-31
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_right
  l_bb_edge_right_13:
    number: neuron-1-32
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_right

  l_bb_edge_left_1:
    number: neuron-2-1
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_2:
    number: neuron-2-2
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_3:
    number: neuron-2-3
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_4:
    number: neuron-2-4
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_5:
    number: neuron-2-5
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_6:
    number: neuron-2-6
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_7:
    number: neuron-2-7
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_8:
    number: neuron-2-8
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_9:
    number: neuron-2-9
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_10:
    number: neuron-2-10
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_11:
    number: neuron-2-11
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_12:
    number: neuron-2-12
    type: rgb
    tags: lights_2a, lights_3a, lights_4a, lights_bb_edge, lights_bb_edge_left
  l_bb_edge_left_13:
    number: neuron-2-13
    type: rgb
    tags: lights_2b, lights_3b, lights_4b, lights_bb_edge, lights_bb_edge_left
