#config_version=6

lights:
  # playfield multipliers
  l_pf_x2:
    number: 9001
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_multipliers
  l_pf_x3:
    number: 9002
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_multipliers
  l_pf_x4:
    number: 9003
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_multipliers
  l_pf_x5:
    number: 9004
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_lights_multipliersburn

  # MAJESTY counters (from 12:00 clockwise rotating)
  l_majesty_1: #Consider splitting into R G and B channels to separately light colors without mounting multiple LED packages into one insert
    number: 9005
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_majesty
  l_majesty_2:
    number: 9006
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_majesty
  l_majesty_3:
    number: 9007
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_majesty
  l_majesty_4:
    number: 9008
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_majesty
  l_majesty_5:
    number: 9009
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_majesty
  l_majesty_6:
    number: 9010
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_majesty

  # B U R N rollovers
  l_burn_b:
    number: 9011
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_burn
  l_burn_u:
    number: 9012
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_burn
  l_burn_r:
    number: 9013
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_burn
  l_burn_n:
    number: 9014
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_burn

  # Inlanes and Outlanes
  l_left_outlane:
    number: 9015
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_lanes, lights_outlanes, lights_lower_third
  l_left_inlane:
    number: 9016
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_lanes, lights_inlanes, lights_lower_third
  l_right_inlane:
    number: 9017
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_lanes, lights_inlanes, lights_lower_third
  l_right_outlane:
    number: 9018
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_lanes, lights_outlanes, lights_lower_third

  l_drain:
    number: 9019
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_lower_third

  # Minicab: Cobrapin dome post ring - RGB
  l_dome_ring_a_1:
    number: 9020
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_cab, lights_dome_ring_a
  l_dome_ring_a_2:
    number: 9021
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_cab, lights_dome_ring_a
  l_dome_ring_a_3:
    number: 9022
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_cab, lights_dome_ring_a
  l_dome_ring_a_4:
    number: 9023
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_cab, lights_dome_ring_a
  l_dome_ring_a_5:
    number: 9024
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_cab, lights_dome_ring_a
  l_dome_ring_a_6:
    number: 9025
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_cab, lights_dome_ring_a
  l_dome_ring_a_7:
    number: 9026
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_cab, lights_dome_ring_a
  l_dome_ring_a_8:
    number: 9027
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_cab, lights_dome_ring_a

  l_captive_ball_single:
    number: 9028
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf
  l_captive_ball_ring_1:
    number: 9029
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_captive_ring
  l_captive_ball_ring_2:
    number: 9030
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_captive_ring
  l_captive_ball_ring_3:
    number: 9031
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_captive_ring
  l_captive_ball_ring_4:
    number: 9032
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_captive_ring
  l_captive_ball_ring_5:
    number: 9033
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_captive_ring
  l_captive_ball_ring_6:
    number: 9034
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_captive_ring
  l_captive_ball_ring_7:
    number: 9035
    platform: smart_virtual
    type: rgb
    tags: lights_2a, lights_pf, lights_captive_ring
  l_captive_ball_ring_8:
    number: 9036
    platform: smart_virtual
    type: rgb
    tags: lights_2b, lights_pf, lights_captive_ring
