#config_version=6

lights:
  # B U R N rollovers
  l_burn_b:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_burn
  l_burn_u:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_burn
  l_burn_r:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_burn
  l_burn_n:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_burn

  # Playfield: 3x Cobrapin pop bumper ring - RGBW...
  l_pop_ring_b_1:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_pop_ring_b
  l_pop_ring_b_2:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_pop_ring_b
  l_pop_ring_b_3:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_pop_ring_b
  l_pop_ring_b_4:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_pop_ring_b
  l_pop_ring_b_5:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_pop_ring_b
  l_pop_ring_b_6:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_pop_ring_b
  l_pop_ring_b_7:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_pop_ring_b
  l_pop_ring_b_8:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_pop_ring_b

  l_pop_ring_c_1:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_pop_ring_c
  l_pop_ring_c_2:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_pop_ring_c
  l_pop_ring_c_3:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_pop_ring_c
  l_pop_ring_c_4:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_pop_ring_c
  l_pop_ring_c_5:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_pop_ring_c
  l_pop_ring_c_6:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_pop_ring_c
  l_pop_ring_c_7:
    number:
    type: rgb
    tags: lights_a, lights_pf, lights_pop_ring_c
  l_pop_ring_c_8:
    number:
    type: rgb
    tags: lights_b, lights_pf, lights_pop_ring_c

  # Minicab: Cobrapin dome post ring - RGB
  l_dome_ring_a_1:
    number:
    type: rgb
    tags: lights_a, lights_cab, lights_dome_ring_a
  l_dome_ring_a_2:
    number:
    type: rgb
    tags: lights_b, lights_cab, lights_dome_ring_a
  l_dome_ring_a_3:
    number:
    type: rgb
    tags: lights_a, lights_cab, lights_dome_ring_a
  l_dome_ring_a_4:
    number:
    type: rgb
    tags: lights_b, lights_cab, lights_dome_ring_a
  l_dome_ring_a_5:
    number:
    type: rgb
    tags: lights_a, lights_cab, lights_dome_ring_a
  l_dome_ring_a_6:
    number:
    type: rgb
    tags: lights_b, lights_cab, lights_dome_ring_a
  l_dome_ring_a_7:
    number:
    type: rgb
    tags: lights_a, lights_cab, lights_dome_ring_a
  l_dome_ring_a_8:
    number:
    type: rgb
    tags: lights_b, lights_cab, lights_dome_ring_a