#config_version=6
# Generated lights!

---
lights:
  generated_light_1:
    number: 11001
    platform: smart_virtual
    type: rgb
  gl_ring_a_1:
    tags: lights_generated,lights_a,lights_gl_ring_a
    type: rgb
    number: 11002
    platform: smart_virtual
  gl_ring_a_2:
    tags: lights_generated,lights_b,lights_gl_ring_a
    type: rgb
    number: 11003
    platform: smart_virtual
  gl_ring_a_3:
    tags: lights_generated,lights_a,lights_gl_ring_a
    type: rgb
    number: 11004
    platform: smart_virtual
  gl_ring_a_4:
    tags: lights_generated,lights_b,lights_gl_ring_a
    type: rgb
    number: 11005
    platform: smart_virtual
  gl_ring_a_5:
    tags: lights_generated,lights_a,lights_gl_ring_a
    type: rgb
    number: 11006
    platform: smart_virtual
  gl_ring_a_6:
    tags: lights_generated,lights_b,lights_gl_ring_a
    type: rgb
    number: 11007
    platform: smart_virtual
  gl_ring_a_7:
    tags: lights_generated,lights_a,lights_gl_ring_a
    type: rgb
    number: 11008
    platform: smart_virtual
  gl_ring_a_8:
    tags: lights_generated,lights_b,lights_gl_ring_a
    type: rgb
    number: 11009
    platform: smart_virtual
  gl_grid_1:
    number: 1001
    tags: lights_generated,lights_a,grid_lights,grid_lights_a
    type: rgb
    platform: smart_virtual
  gl_grid_2:
    number: 1002
    tags: lights_generated,lights_b,grid_lights,grid_lights_b
    type: rgb
    platform: smart_virtual
  gl_grid_3:
    number: 1003
    tags: lights_generated,lights_a,grid_lights,grid_lights_a
    type: rgb
    platform: smart_virtual
  gl_grid_4:
    number: 1004
    tags: lights_generated,lights_b,grid_lights,grid_lights_b
    type: rgb
    platform: smart_virtual
  gl_grid_5:
    number: 1005
    tags: lights_generated,lights_a,grid_lights,grid_lights_a
    type: rgb
    platform: smart_virtual
  gl_grid_6:
    number: 1006
    tags: lights_generated,lights_b,grid_lights,grid_lights_b
    type: rgb
    platform: smart_virtual
  gl_grid_7:
    number: 1007
    tags: lights_generated,lights_a,grid_lights,grid_lights_a
    type: rgb
    platform: smart_virtual
  gl_grid_8:
    number: 1008
    tags: lights_generated,lights_b,grid_lights,grid_lights_b
    type: rgb
    platform: smart_virtual
  gl_grid_9:
    number: 1009
    tags: lights_generated,lights_a,grid_lights,grid_lights_a
    type: rgb
    platform: smart_virtual
