#config_version=6
# Generated lights!

---
lights:
  generated_light_1:
    number: 8801
    platform: smart_virtual
    type: rgb
  gl_ring_a_1:
    tags: lights_generated,lights_2a,lights_3a,lights_4a,lights_5a,lights_gl_ring_a
    type: rgb
    number: 8802
    platform: smart_virtual
  gl_ring_a_2:
    tags: lights_generated,lights_2b,lights_3b,lights_4a,lights_5e,lights_gl_ring_a
    type: rgb
    number: 8803
    platform: smart_virtual
  gl_ring_a_3:
    tags: lights_generated,lights_2a,lights_3c,lights_4b,lights_5b,lights_gl_ring_a
    type: rgb
    number: 8804
    platform: smart_virtual
  gl_ring_a_4:
    tags: lights_generated,lights_2b,lights_3a,lights_4b,lights_5e,lights_gl_ring_a
    type: rgb
    number: 8805
    platform: smart_virtual
  gl_ring_a_5:
    tags: lights_generated,lights_2a,lights_3b,lights_4c,lights_5c,lights_gl_ring_a
    type: rgb
    number: 8806
    platform: smart_virtual
  gl_ring_a_6:
    tags: lights_generated,lights_2b,lights_3c,lights_4c,lights_5e,lights_gl_ring_a
    type: rgb
    number: 8807
    platform: smart_virtual
  gl_ring_a_7:
    tags: lights_generated,lights_2a,lights_3a,lights_4d,lights_5d,lights_gl_ring_a
    type: rgb
    number: 8808
    platform: smart_virtual
  gl_ring_a_8:
    tags: lights_generated,lights_2b,lights_3b,lights_4d,lights_5e,lights_gl_ring_a
    type: rgb
    number: 8809
    platform: smart_virtual
  gl_grid_1:
    tags: lights_generated,lights_2a,lights_3a,lights_4a,lights_5a,grid_lights
    type: rgb
    number: 8810
    platform: smart_virtual
  gl_grid_2:
    tags: lights_generated,lights_2b,lights_3b,lights_4b,lights_5b,grid_lights
    type: rgb
    number: 8811
    platform: smart_virtual
  gl_grid_3:
    tags: lights_generated,lights_2a,lights_3c,lights_4c,lights_5c,grid_lights
    type: rgb
    number: 8812
    platform: smart_virtual
  gl_grid_4:
    tags: lights_generated,lights_2b,lights_3a,lights_4d,lights_5d,grid_lights
    type: rgb
    number: 8813
    platform: smart_virtual
  gl_grid_5:
    tags: lights_generated,lights_2a,lights_3b,lights_4a,lights_5e,grid_lights
    type: rgb
    number: 8814
    platform: smart_virtual
  gl_grid_6:
    tags: lights_generated,lights_2b,lights_3c,lights_4b,lights_5a,grid_lights
    type: rgb
    number: 8815
    platform: smart_virtual
  gl_grid_7:
    tags: lights_generated,lights_2a,lights_3a,lights_4c,lights_5b,grid_lights
    type: rgb
    number: 8816
    platform: smart_virtual
  gl_grid_8:
    tags: lights_generated,lights_2b,lights_3b,lights_4d,lights_5c,grid_lights
    type: rgb
    number: 8817
    platform: smart_virtual
  gl_grid_9:
    tags: lights_generated,lights_2a,lights_3c,lights_4a,lights_5d,grid_lights
    type: rgb
    number: 8818
    platform: smart_virtual
  gl_cobra_ring_a_1:
    tags: lights_generated,lights_2a,lights_3a,lights_4a,lights_5a,lights_rings,lights_pf,lights_cobra_ring_a
    type: rgb
    platform: fast
    number: exp_playfield-3-1
  gl_cobra_ring_a_2:
    tags: lights_generated,lights_2b,lights_3b,lights_4a,lights_5e,lights_rings,lights_pf,lights_cobra_ring_a
    type: rgb
    platform: fast
    number: exp_playfield-3-2
  gl_cobra_ring_a_3:
    tags: lights_generated,lights_2a,lights_3c,lights_4b,lights_5b,lights_rings,lights_pf,lights_cobra_ring_a
    type: rgb
    platform: fast
    number: exp_playfield-3-3
  gl_cobra_ring_a_4:
    tags: lights_generated,lights_2b,lights_3a,lights_4b,lights_5e,lights_rings,lights_pf,lights_cobra_ring_a
    type: rgb
    platform: fast
    number: exp_playfield-3-4
  gl_cobra_ring_a_5:
    tags: lights_generated,lights_2a,lights_3b,lights_4c,lights_5c,lights_rings,lights_pf,lights_cobra_ring_a
    type: rgb
    platform: fast
    number: exp_playfield-3-5
  gl_cobra_ring_a_6:
    tags: lights_generated,lights_2b,lights_3c,lights_4c,lights_5e,lights_rings,lights_pf,lights_cobra_ring_a
    type: rgb
    platform: fast
    number: exp_playfield-3-6
  gl_cobra_ring_a_7:
    tags: lights_generated,lights_2a,lights_3a,lights_4d,lights_5d,lights_rings,lights_pf,lights_cobra_ring_a
    type: rgb
    platform: fast
    number: exp_playfield-3-7
  gl_cobra_ring_a_8:
    tags: lights_generated,lights_2b,lights_3b,lights_4d,lights_5e,lights_rings,lights_pf,lights_cobra_ring_a
    type: rgb
    platform: fast
    number: exp_playfield-3-8
  gl_cobra_ring_b_1:
    tags: lights_generated,lights_2a,lights_3a,lights_4a,lights_5a,lights_rings,lights_pf,lights_cobra_ring_b
    type: rgb
    platform: fast
    number: exp_playfield-3-9
  gl_cobra_ring_b_2:
    tags: lights_generated,lights_2b,lights_3b,lights_4a,lights_5e,lights_rings,lights_pf,lights_cobra_ring_b
    type: rgb
    platform: fast
    number: exp_playfield-3-10
  gl_cobra_ring_b_3:
    tags: lights_generated,lights_2a,lights_3c,lights_4b,lights_5b,lights_rings,lights_pf,lights_cobra_ring_b
    type: rgb
    platform: fast
    number: exp_playfield-3-11
  gl_cobra_ring_b_4:
    tags: lights_generated,lights_2b,lights_3a,lights_4b,lights_5e,lights_rings,lights_pf,lights_cobra_ring_b
    type: rgb
    platform: fast
    number: exp_playfield-3-12
  gl_cobra_ring_b_5:
    tags: lights_generated,lights_2a,lights_3b,lights_4c,lights_5c,lights_rings,lights_pf,lights_cobra_ring_b
    type: rgb
    platform: fast
    number: exp_playfield-3-13
  gl_cobra_ring_b_6:
    tags: lights_generated,lights_2b,lights_3c,lights_4c,lights_5e,lights_rings,lights_pf,lights_cobra_ring_b
    type: rgb
    platform: fast
    number: exp_playfield-3-14
  gl_cobra_ring_b_7:
    tags: lights_generated,lights_2a,lights_3a,lights_4d,lights_5d,lights_rings,lights_pf,lights_cobra_ring_b
    type: rgb
    platform: fast
    number: exp_playfield-3-15
  gl_cobra_ring_b_8:
    tags: lights_generated,lights_2b,lights_3b,lights_4d,lights_5e,lights_rings,lights_pf,lights_cobra_ring_b
    type: rgb
    platform: fast
    number: exp_playfield-3-16
  gl_cobra_ring_c_1:
    tags: lights_generated,lights_2a,lights_3a,lights_4a,lights_5a,lights_rings,lights_pf,lights_cobra_ring_c
    type: rgb
    platform: fast
    number: exp_playfield-3-17
  gl_cobra_ring_c_2:
    tags: lights_generated,lights_2b,lights_3b,lights_4a,lights_5e,lights_rings,lights_pf,lights_cobra_ring_c
    type: rgb
    platform: fast
    number: exp_playfield-3-18
  gl_cobra_ring_c_3:
    tags: lights_generated,lights_2a,lights_3c,lights_4b,lights_5b,lights_rings,lights_pf,lights_cobra_ring_c
    type: rgb
    platform: fast
    number: exp_playfield-3-19
  gl_cobra_ring_c_4:
    tags: lights_generated,lights_2b,lights_3a,lights_4b,lights_5e,lights_rings,lights_pf,lights_cobra_ring_c
    type: rgb
    platform: fast
    number: exp_playfield-3-20
  gl_cobra_ring_c_5:
    tags: lights_generated,lights_2a,lights_3b,lights_4c,lights_5c,lights_rings,lights_pf,lights_cobra_ring_c
    type: rgb
    platform: fast
    number: exp_playfield-3-21
  gl_cobra_ring_c_6:
    tags: lights_generated,lights_2b,lights_3c,lights_4c,lights_5e,lights_rings,lights_pf,lights_cobra_ring_c
    type: rgb
    platform: fast
    number: exp_playfield-3-22
  gl_cobra_ring_c_7:
    tags: lights_generated,lights_2a,lights_3a,lights_4d,lights_5d,lights_rings,lights_pf,lights_cobra_ring_c
    type: rgb
    platform: fast
    number: exp_playfield-3-23
  gl_cobra_ring_c_8:
    tags: lights_generated,lights_2b,lights_3b,lights_4d,lights_5e,lights_rings,lights_pf,lights_cobra_ring_c
    type: rgb
    platform: fast
    number: exp_playfield-3-24
  gl_cobra_ring_d_1:
    tags: lights_generated,lights_2a,lights_3a,lights_4a,lights_5a,lights_rings,lights_pf,lights_cobra_ring_d
    type: rgb
    platform: fast
    number: exp_playfield-3-25
  gl_cobra_ring_d_2:
    tags: lights_generated,lights_2b,lights_3b,lights_4a,lights_5e,lights_rings,lights_pf,lights_cobra_ring_d
    type: rgb
    platform: fast
    number: exp_playfield-3-26
  gl_cobra_ring_d_3:
    tags: lights_generated,lights_2a,lights_3c,lights_4b,lights_5b,lights_rings,lights_pf,lights_cobra_ring_d
    type: rgb
    platform: fast
    number: exp_playfield-3-27
  gl_cobra_ring_d_4:
    tags: lights_generated,lights_2b,lights_3a,lights_4b,lights_5e,lights_rings,lights_pf,lights_cobra_ring_d
    type: rgb
    platform: fast
    number: exp_playfield-3-28
  gl_cobra_ring_d_5:
    tags: lights_generated,lights_2a,lights_3b,lights_4c,lights_5c,lights_rings,lights_pf,lights_cobra_ring_d
    type: rgb
    platform: fast
    number: exp_playfield-3-29
  gl_cobra_ring_d_6:
    tags: lights_generated,lights_2b,lights_3c,lights_4c,lights_5e,lights_rings,lights_pf,lights_cobra_ring_d
    type: rgb
    platform: fast
    number: exp_playfield-3-30
  gl_cobra_ring_d_7:
    tags: lights_generated,lights_2a,lights_3a,lights_4d,lights_5d,lights_rings,lights_pf,lights_cobra_ring_d
    type: rgb
    platform: fast
    number: exp_playfield-3-31
  gl_cobra_ring_d_8:
    tags: lights_generated,lights_2b,lights_3b,lights_4d,lights_5e,lights_rings,lights_pf,lights_cobra_ring_d
    type: rgb
    platform: fast
    number: exp_playfield-3-32
  gl_ss_elbow_downwards:
    tags: lights_generated,lights_sequence_shots
    number: 8819
    platform: smart_virtual
    type: rgb
  gl_ss_elbow_upwards:
    tags: lights_generated,lights_sequence_shots
    number: 8820
    platform: smart_virtual
    type: rgb
  gl_ss_horseshoe_clockwise:
    tags: lights_generated,lights_sequence_shots
    number: 8821
    platform: smart_virtual
    type: rgb
  gl_ss_horseshoe_widdershins:
    tags: lights_generated,lights_sequence_shots
    number: 8822
    platform: smart_virtual
    type: rgb
  gl_ss_left_orbit_open:
    tags: lights_generated,lights_sequence_shots
    number: 8823
    platform: smart_virtual
    type: rgb
  gl_ss_left_orbit_closed:
    tags: lights_generated,lights_sequence_shots
    number: 8824
    platform: smart_virtual
    type: rgb
  gl_ss_right_orbit_open:
    tags: lights_generated,lights_sequence_shots
    number: 8825
    platform: smart_virtual
    type: rgb
  gl_ss_right_orbit_closed:
    tags: lights_generated,lights_sequence_shots
    number: 8826
    platform: smart_virtual
    type: rgb
  gl_ss_right_ramp_summit:
    tags: lights_generated,lights_sequence_shots
    number: 8827
    platform: smart_virtual
    type: rgb
  gl_ss_right_ramp_travel:
    tags: lights_generated,lights_sequence_shots
    number: 8828
    platform: smart_virtual
    type: rgb
  gl_ss_right_outlane_escape:
    tags: lights_generated,lights_sequence_shots
    number: 8829
    platform: smart_virtual
    type: rgb
  gl_ss_s_ramp_summit:
    tags: lights_generated,lights_sequence_shots
    number: 8830
    platform: smart_virtual
    type: rgb
  gl_ss_s_ramp_travel:
    tags: lights_generated,lights_sequence_shots
    number: 8831
    platform: smart_virtual
    type: rgb
  gl_ss_subway_travel:
    tags: lights_generated,lights_sequence_shots
    number: 8832
    platform: smart_virtual
    type: rgb
