#config_version=6
# Generated lights!

---
lights:
  generated_light_1:
    number:
    type: rgb
  gl_ring_a_0:
    tags: lights_generated,lights_a
    type: rgb
    number:
  gl_ring_a_1:
    tags: lights_generated,lights_b
    type: rgb
    number:
  gl_ring_a_2:
    tags: lights_generated,lights_a
    type: rgb
    number:
  gl_ring_a_3:
    tags: lights_generated,lights_b
    type: rgb
    number:
  gl_ring_a_4:
    tags: lights_generated,lights_a
    type: rgb
    number:
  gl_ring_a_5:
    tags: lights_generated,lights_b
    type: rgb
    number:
  gl_ring_a_6:
    tags: lights_generated,lights_a
    type: rgb
    number:
  gl_ring_a_7:
    tags: lights_generated,lights_b
    type: rgb
    number:
