#config_version=6
# Generated lights!

---
lights:
  generated_light_1:
    number: 8801
    platform: smart_virtual
    type: rgb
  gl_ring_a_1:
    tags: lights_generated,lights_a,lights_gl_ring_a
    type: rgb
    number: 8802
    platform: smart_virtual
  gl_ring_a_2:
    tags: lights_generated,lights_b,lights_gl_ring_a
    type: rgb
    number: 8803
    platform: smart_virtual
  gl_ring_a_3:
    tags: lights_generated,lights_a,lights_gl_ring_a
    type: rgb
    number: 8804
    platform: smart_virtual
  gl_ring_a_4:
    tags: lights_generated,lights_b,lights_gl_ring_a
    type: rgb
    number: 8805
    platform: smart_virtual
  gl_ring_a_5:
    tags: lights_generated,lights_a,lights_gl_ring_a
    type: rgb
    number: 8806
    platform: smart_virtual
  gl_ring_a_6:
    tags: lights_generated,lights_b,lights_gl_ring_a
    type: rgb
    number: 8807
    platform: smart_virtual
  gl_ring_a_7:
    tags: lights_generated,lights_a,lights_gl_ring_a
    type: rgb
    number: 8808
    platform: smart_virtual
  gl_ring_a_8:
    tags: lights_generated,lights_b,lights_gl_ring_a
    type: rgb
    number: 8809
    platform: smart_virtual
  gl_grid_1:
    tags: lights_generated,lights_a,grid_lights,grid_lights_a
    type: rgb
    number: 8810
    platform: smart_virtual
  gl_grid_2:
    tags: lights_generated,lights_b,grid_lights,grid_lights_b
    type: rgb
    number: 8811
    platform: smart_virtual
  gl_grid_3:
    tags: lights_generated,lights_a,grid_lights,grid_lights_a
    type: rgb
    number: 8812
    platform: smart_virtual
  gl_grid_4:
    tags: lights_generated,lights_b,grid_lights,grid_lights_b
    type: rgb
    number: 8813
    platform: smart_virtual
  gl_grid_5:
    tags: lights_generated,lights_a,grid_lights,grid_lights_a
    type: rgb
    number: 8814
    platform: smart_virtual
  gl_grid_6:
    tags: lights_generated,lights_b,grid_lights,grid_lights_b
    type: rgb
    number: 8815
    platform: smart_virtual
  gl_grid_7:
    tags: lights_generated,lights_a,grid_lights,grid_lights_a
    type: rgb
    number: 8816
    platform: smart_virtual
  gl_grid_8:
    tags: lights_generated,lights_b,grid_lights,grid_lights_b
    type: rgb
    number: 8817
    platform: smart_virtual
  gl_grid_9:
    tags: lights_generated,lights_a,grid_lights,grid_lights_a
    type: rgb
    number: 8818
    platform: smart_virtual
