#config_version=6

light_settings:
  default_fade_ms: 40

# led name can be anything you want, 
# the number is the board its on playfield,
# port 1, led 1 in the chain.
# For the 2nd led, it would be number: playfield-1-2

lights:
  # EXP String 2 - mini cab
  l_mini_cab_mini:
    number: exp_playfield-2-1
    type: rgb
    tags: lights_a, lights_cab

  l_mini_cab_left:
    number: exp_playfield-2-2
    type: rgb
    tags: lights_b, lights_cab

  l_mini_cab_right:
    number: exp_playfield-2-3
    type: rgb
    tags: lights_a, lights_cab

  # Cobrapin star post ring - RGB, no hax needed
  l_star_ring_a_1:
    number: exp_playfield-1-3
    type: rgb
    tags: lights_a, lights_cab, lights_star_ring_a
  l_star_ring_a_2:
    number: exp_playfield-1-4
    type: rgb
    tags: lights_b, lights_cab, lights_star_ring_a
  l_star_ring_a_3:
    number: exp_playfield-1-5
    type: rgb
    tags: lights_a, lights_cab, lights_star_ring_a
  l_star_ring_a_4:
    number: exp_playfield-1-6
    type: rgb
    tags: lights_b, lights_cab, lights_star_ring_a
  l_star_ring_a_5:
    number: exp_playfield-1-7
    type: rgb
    tags: lights_a, lights_cab, lights_star_ring_a
  l_star_ring_a_6:
    number: exp_playfield-1-8
    type: rgb
    tags: lights_b, lights_cab, lights_star_ring_a
  l_star_ring_a_7:
    number: exp_playfield-1-9
    type: rgb
    tags: lights_a, lights_cab, lights_star_ring_a
  l_star_ring_a_8:
    number: exp_playfield-1-10
    type: rgb
    tags: lights_b, lights_cab, lights_star_ring_a
