#config_version=6

lights:
  # EXP String 2 - mini cab
  l_mini_cab_left_secondary:
    number: exp_playfield-2-1
    tags: lights_2a, lights_3a, lights_4a, lights_5a, lights_cab

  l_mini_cab_left:
    number: exp_playfield-2-2
    tags: lights_2b, lights_3b, lights_4b, lights_5b, lights_cab

  l_mini_cab_right:
    number: exp_playfield-2-3
    tags: lights_2a, lights_3c, lights_4c, lights_5d, lights_cab

  l_mini_cab_right_secondary: #virtual, for completeness
    platform: smart_virtual
    tags: lights_2b, lights_3b, lights_4d, lights_5e, lights_cab
