#config_version=6

light_settings:
  default_fade_ms: 40

# led name can be anything you want, 
# the number is the board its on playfield,
# port 1, led 1 in the chain.
# For the 2nd led, it would be number: playfield-1-2

lights:
  # EXP String 2 - mini cab
  l_mini_cab_mini:
    number: neuron-1-1
    type: rgb
    tags: lights_2a, lights_3a, lights_4x, lights_5x, lights_cab

  l_mini_cab_left:
    number: neuron-1-2
    type: rgb
    tags: lights_2b, lights_3b, lights_4x, lights_5x, lights_cab

  l_mini_cab_right:
    number: neuron-1-3
    type: rgb
    tags: lights_2a, lights_3c, lights_4x, lights_5x, lights_cab

# Cobrapin Pop bumpers require manual channeling due to RGBW configuration
# Don't add more lights after them in a chain

# The pattern appears to be as follows, repeating after 12 channels
# 0-0 0-1 0-2 1-1
# 1-2 1-0 2-1 2-0
# 3-1 2-2 3-0 3-2

# in four channel counting it would be
# 0-0 0-1 0-2 1-0
# 1-1 0-3 1-3 1-2
# 2-2 2-0 2-1 2-3
# which doesn't really help at all

# Pattern is RGBGWRWBGBRW
# Thats, starting from the last available channel, 
#  R   G   B   W
# +1, +1, +1, +2
# +1, -2, +4, -1
# +4, -2, +1, +2
# repeat

# For some reason this pattern does not reset at the start of every
# ring, so each set of 8 starts with the four channel pattern
# offset by 1 from the previous round

  # Ring A
  l_pop_ring_a_1:
    tags: lights_2a, lights_3a, lights_4a, lights_5a, lights_pf, lights_pop_ring_a, lights_pops
    channels:
      red:
        number: neuron-1-4-0 #+1
      green:
        number: neuron-1-4-1 #+1
      blue:
        number: neuron-1-4-2 #+1
      white:
        number: neuron-1-5-1 #+2

  l_pop_ring_a_2:
    tags: lights_2b, lights_3b, lights_4a, lights_5e, lights_pf, lights_pop_ring_a, lights_pops
    channels:
      red:
        number: neuron-1-5-2 #+1
      green:
        number: neuron-1-5-0 #-2
      blue:
        number: neuron-1-6-1 #+4
      white:
        number: neuron-1-6-0 #-1

  l_pop_ring_a_3:
    tags: lights_2a, lights_3c, lights_4b, lights_5b, lights_pf, lights_pop_ring_a, lights_pops
    channels:
      red:
        number: neuron-1-7-1 #+4
      green:
        number: neuron-1-6-2 #-2
      blue:
        number: neuron-1-7-0 #+1
      white:
        number: neuron-1-7-2 #+2

  l_pop_ring_a_4:
    tags: lights_2b, lights_3a, lights_4b, lights_5e, lights_pf, lights_pop_ring_a, lights_pops
    channels:
      red:
        number: neuron-1-8-0 #+1
      green:
        number: neuron-1-8-1 #+1
      blue:
        number: neuron-1-8-2 #+1
      white:
        number: neuron-1-9-1 #+2

  l_pop_ring_a_5:
    tags: lights_2a, lights_3b, lights_4c, lights_5c, lights_pf, lights_pop_ring_a, lights_pops
    channels:
      red:
        number: neuron-1-9-2 #+1
      green:
        number: neuron-1-9-0 #-2
      blue:
        number: neuron-1-10-1 #+4
      white:
        number: neuron-1-10-0 #-1

  l_pop_ring_a_6:
    tags: lights_2b, lights_3c, lights_4c, lights_5e, lights_pf, lights_pop_ring_a, lights_pops
    channels:
      red:
        number: neuron-1-11-1 #+4
      green:
        number: neuron-1-10-2 #-2
      blue:
        number: neuron-1-11-0 #+1
      white:
        number: neuron-1-11-2 #+2

  l_pop_ring_a_7:
    tags: lights_2a, lights_3a, lights_4d, lights_5d, lights_pf, lights_pop_ring_a, lights_pops
    channels:
      red:
        number: neuron-1-12-0 #+1
      green:
        number: neuron-1-12-1 #+1
      blue:
        number: neuron-1-12-2 #+1
      white:
        number: neuron-1-13-1 #+2

  l_pop_ring_a_8:
    tags: lights_2b, lights_3b, lights_4d, lights_5e, lights_pf, lights_pop_ring_a, lights_pops
    channels:
      red:
        number: neuron-1-13-2 #+1
      green:
        number: neuron-1-13-0 #-2
      blue:
        number: neuron-1-14-1 #+4
      white:
        number: neuron-1-14-0 #-1

  # Ring B
  l_pop_ring_b_1:
    tags: lights_2a, lights_3c, lights_4a, lights_5a, lights_pf, lights_pop_ring_b, lights_pops
    channels:
      red:
        number: neuron-1-15-1 #+4
      green:
        number: neuron-1-14-2 #-2
      blue:
        number: neuron-1-15-0 #+1
      white:
        number: neuron-1-15-2 #+2

  l_pop_ring_b_2:
    tags: lights_2b, lights_3a, lights_4a, lights_5e, lights_pf, lights_pop_ring_b, lights_pops
    channels:
      red:
        number: neuron-1-16-0 #+1
      green:
        number: neuron-1-16-1 #+1
      blue:
        number: neuron-1-16-2 #+1
      white:
        number: neuron-1-17-1 #+2

  l_pop_ring_b_3:
    tags: lights_2a, lights_3b, lights_4b, lights_5b, lights_pf, lights_pop_ring_b, lights_pops
    channels:
      red:
        number: neuron-1-17-2 #+1
      green:
        number: neuron-1-17-0 #-2
      blue:
        number: neuron-1-18-1 #+4
      white:
        number: neuron-1-18-0 #-1

  l_pop_ring_b_4:
    tags: lights_2b, lights_3c, lights_4b, lights_5e, lights_pf, lights_pop_ring_b, lights_pops
    channels:
      red:
        number: neuron-1-19-1 #+4
      green:
        number: neuron-1-18-2 #-2
      blue:
        number: neuron-1-19-0 #+1
      white:
        number: neuron-1-19-2 #+2

  l_pop_ring_b_5:
    tags: lights_2a, lights_3a, lights_4c, lights_5c, lights_pf, lights_pop_ring_b, lights_pops
    channels:
      red:
        number: neuron-1-20-0 #+1
      green:
        number: neuron-1-20-1 #+1
      blue:
        number: neuron-1-20-2 #+1
      white:
        number: neuron-1-21-1 #+2

  l_pop_ring_b_6:
    tags: lights_2b, lights_3b, lights_4c, lights_5e, lights_pf, lights_pop_ring_b, lights_pops
    channels:
      red:
        number: neuron-1-21-2 #+1
      green:
        number: neuron-1-21-0 #-2
      blue:
        number: neuron-1-22-1 #+4
      white:
        number: neuron-1-22-0 #-1

  l_pop_ring_b_7:
    tags: lights_2a, lights_3c, lights_4d, lights_5d, lights_pf, lights_pop_ring_b, lights_pops
    channels:
      red:
        number: neuron-1-23-1 #+4
      green:
        number: neuron-1-22-2 #-2
      blue:
        number: neuron-1-23-0 #+1
      white:
        number: neuron-1-23-2 #+2

  l_pop_ring_b_8:
    tags: lights_2b, lights_3a, lights_4d, lights_5e, lights_pf, lights_pop_ring_b, lights_pops
    channels:
      red:
        number: neuron-1-24-0 #+1
      green:
        number: neuron-1-24-1 #+1
      blue:
        number: neuron-1-24-2 #+1
      white:
        number: neuron-1-25-1 #+2

  # Ring C
  l_pop_ring_c_1:
    tags: lights_2a, lights_3b, lights_4a, lights_5a, lights_pf, lights_pop_ring_c, lights_pops
    channels:
      red:
        number: neuron-1-25-2 #+1
      green:
        number: neuron-1-25-0 #-2
      blue:
        number: neuron-1-26-1 #+4
      white:
        number: neuron-1-26-0 #-1

  l_pop_ring_c_2:
    tags: lights_2b, lights_3c, lights_4a, lights_5e, lights_pf, lights_pop_ring_c, lights_pops
    channels:
      red:
        number: neuron-1-27-1 #+4
      green:
        number: neuron-1-26-2 #-2
      blue:
        number: neuron-1-27-0 #+1
      white:
        number: neuron-1-27-2 #+2

  l_pop_ring_c_3:
    tags: lights_2a, lights_3a, lights_4b, lights_5b, lights_pf, lights_pop_ring_c, lights_pops
    channels:
      red:
        number: neuron-1-28-0 #+1
      green:
        number: neuron-1-28-1 #+1
      blue:
        number: neuron-1-28-2 #+1
      white:
        number: neuron-1-29-1 #+2

  l_pop_ring_c_4:
    tags: lights_2b, lights_3b, lights_4b, lights_5e, lights_pf, lights_pop_ring_c, lights_pops
    channels:
      red:
        number: neuron-1-29-2 #+1
      green:
        number: neuron-1-29-0 #-2
      blue:
        number: neuron-1-30-1 #+4
      white:
        number: neuron-1-30-0 #-1

  l_pop_ring_c_5:
    tags: lights_2a, lights_3c, lights_4c, lights_5c, lights_pf, lights_pop_ring_c, lights_pops
    channels:
      red:
        number: neuron-1-31-1 #+4
      green:
        number: neuron-1-30-2 #-2
      blue:
        number: neuron-1-31-0 #+1
      white:
        number: neuron-1-31-2 #+2

  l_pop_ring_c_6:
    tags: lights_2b, lights_3a, lights_4c, lights_5e, lights_pf, lights_pop_ring_c, lights_pops
    channels:
      red:
        number: neuron-1-32-0 #+1
      green:
        number: neuron-1-32-1 #+1
      blue:
        number: neuron-1-32-2 #+1
#      white:
#        number: neuron-1-33-1 #+2 too high

  l_pop_ring_c_7:
    tags: lights_2a, lights_3b, lights_4d, lights_5d, lights_pf, lights_pop_ring_c, lights_pops
    platform: smart_virtual
    # channels:
    #   red:
    #     number: neuron-1-33-2 #+1
    #   green:
    #     number: neuron-1-33-0 #-2
    #   blue:
    #     number: neuron-1-34-1 #+4
    #   white:
    #     number: neuron-1-34-0 #-1

  l_pop_ring_c_8:
    tags: lights_2b, lights_3c, lights_4d, lights_5e, lights_pf, lights_pop_ring_c, lights_pops
    platform: smart_virtual
    # channels:
    #   red:
    #     number: neuron-1-35-1 #+4
    #   green:
    #     number: neuron-1-34-2 #-2
    #   blue:
    #     number: neuron-1-35-0 #+1
    #   white:
    #     number: neuron-1-35-2 #+2
