#config_version=6

lights:
# Cobrapin Pop bumper light ring A - RGBW four channel requires manual channeling
# Don't add more lights after it in a chain

# The pattern appears to be as follows, repeating after 12 channels
# 0-0 0-1 0-2 1-1
# 1-2 1-0 2-1 2-0
# 3-1 2-2 3-0 3-2

# 4-0 4-1 4-2 5-1
# 5-2 5-0 6-1 6-0
# 7-1 6-2 7-0 7-2

  # Ring A
  l_pop_ring_a_1:
    tags: lights_a, lights_pf, lights_pop_ring_a
    channels:
      red:
        number: exp_playfield-2-4-0
      green:
        number: exp_playfield-2-4-1
      blue:
        number: exp_playfield-2-4-2
      white:
        number: exp_playfield-2-5-1

  l_pop_ring_a_2:
    tags: lights_b, lights_pf, lights_pop_ring_a
    channels:
      red:
        number: exp_playfield-2-5-2
      green:
        number: exp_playfield-2-5-0
      blue:
        number: exp_playfield-2-6-1
      white:
        number: exp_playfield-2-6-0

  l_pop_ring_a_3:
    tags: lights_a, lights_pf, lights_pop_ring_a
    channels:
      red:
        number: exp_playfield-2-7-1
      green:
        number: exp_playfield-2-6-2
      blue:
        number: exp_playfield-2-7-0
      white:
        number: exp_playfield-2-7-2

  l_pop_ring_a_4:
    tags: lights_b, lights_pf, lights_pop_ring_a
    channels:
      red:
        number: exp_playfield-2-8-0
      green:
        number: exp_playfield-2-8-1
      blue:
        number: exp_playfield-2-8-2
      white:
        number: exp_playfield-2-9-1

  l_pop_ring_a_5:
    tags: lights_a, lights_pf, lights_pop_ring_a
    channels:
      red:
        number: exp_playfield-2-9-2
      green:
        number: exp_playfield-2-9-0
      blue:
        number: exp_playfield-2-10-1
      white:
        number: exp_playfield-2-10-0

  l_pop_ring_a_6:
    tags: lights_b, lights_pf, lights_pop_ring_a
    channels:
      red:
        number: exp_playfield-2-11-1
      green:
        number: exp_playfield-2-10-2
      blue:
        number: exp_playfield-2-11-0
      white:
        number: exp_playfield-2-11-2

  l_pop_ring_a_7:
    tags: lights_a, lights_pf, lights_pop_ring_a
    channels:
      red:
        number: exp_playfield-2-12-0
      green:
        number: exp_playfield-2-12-1
      blue:
        number: exp_playfield-2-12-2
      white:
        number: exp_playfield-2-13-1

  l_pop_ring_a_8:
    tags: lights_b, lights_pf, lights_pop_ring_a
    channels:
      red:
        number: exp_playfield-2-13-2
      green:
        number: exp_playfield-2-13-0
      blue:
        number: exp_playfield-2-14-1
      white:
        number: exp_playfield-2-14-0

  # Ring B
  l_pop_ring_b_1:
    tags: lights_a, lights_pf, lights_pop_ring_b
    channels:
      red:
        number: exp_playfield-2-14-2
      green:
        number: exp_playfield-2-15-0
      blue:
        number: exp_playfield-2-15-1
      white:
        number: exp_playfield-2-16-0

  l_pop_ring_b_2:
    tags: lights_b, lights_pf, lights_pop_ring_b
    channels:
      red:
        number: exp_playfield-2-16-1
      green:
        number: exp_playfield-2-15-2
      blue:
        number: exp_playfield-2-17-0
      white:
        number: exp_playfield-2-16-2

  l_pop_ring_b_3:
    tags: lights_a, lights_pf, lights_pop_ring_b
    channels:
      red:
        number: exp_playfield-2-18-0
      green:
        number: exp_playfield-2-17-1
      blue:
        number: exp_playfield-2-17-2
      white:
        number: exp_playfield-2-18-1

  l_pop_ring_b_4:
    tags: lights_b, lights_pf, lights_pop_ring_b
    channels:
      red:
        number: exp_playfield-2-18-2
      green:
        number: exp_playfield-2-19-0
      blue:
        number: exp_playfield-2-19-1
      white:
        number: exp_playfield-2-20-0

  l_pop_ring_b_5:
    tags: lights_a, lights_pf, lights_pop_ring_b
    channels:
      red:
        number: exp_playfield-2-20-1
      green:
        number: exp_playfield-2-19-2
      blue:
        number: exp_playfield-2-21-0
      white:
        number: exp_playfield-2-20-2

  l_pop_ring_b_6:
    tags: lights_b, lights_pf, lights_pop_ring_b
    channels:
      red:
        number: exp_playfield-2-22-0
      green:
        number: exp_playfield-2-21-1
      blue:
        number: exp_playfield-2-21-2
      white:
        number: exp_playfield-2-22-1

  l_pop_ring_b_7:
    tags: lights_a, lights_pf, lights_pop_ring_b
    channels:
      red:
        number: exp_playfield-2-22-2
      green:
        number: exp_playfield-2-23-0
      blue:
        number: exp_playfield-2-23-1
      white:
        number: exp_playfield-2-24-0

  l_pop_ring_b_8:
    tags: lights_b, lights_pf, lights_pop_ring_b
    channels:
      red:
        number: exp_playfield-2-24-1
      green:
        number: exp_playfield-2-23-2
      blue:
        number: exp_playfield-2-25-0
      white:
        number: exp_playfield-2-24-2

  # Ring C
  l_pop_ring_c_1:
    tags: lights_a, lights_pf, lights_pop_ring_c
    channels:
      red:
        number: exp_playfield-2-25-1
      green:
        number: exp_playfield-2-25-2
      blue:
        number: exp_playfield-2-26-0
      white:
        number: exp_playfield-2-26-2

  l_pop_ring_c_2:
    tags: lights_b, lights_pf, lights_pop_ring_c
    channels:
      red:
        number: exp_playfield-2-27-0
      green:
        number: exp_playfield-2-26-1
      blue:
        number: exp_playfield-2-27-2
      white:
        number: exp_playfield-2-27-1

  l_pop_ring_c_3:
    tags: lights_a, lights_pf, lights_pop_ring_c
    channels:
      red:
        number: exp_playfield-2-28-2
      green:
        number: exp_playfield-2-28-0
      blue:
        number: exp_playfield-2-28-1
      white:
        number: exp_playfield-2-29-0

  l_pop_ring_c_4:
    tags: lights_b, lights_pf, lights_pop_ring_c
    channels:
      red:
        number: exp_playfield-2-29-1
      green:
        number: exp_playfield-2-29-2
      blue:
        number: exp_playfield-2-30-0
      white:
        number: exp_playfield-2-30-2

  l_pop_ring_c_5:
    tags: lights_a, lights_pf, lights_pop_ring_c
    channels:
      red:
        number: exp_playfield-2-31-0
      green:
        number: exp_playfield-2-30-1
      blue:
        number: exp_playfield-2-31-2
      white:
        number: exp_playfield-2-31-1

  l_pop_ring_c_6:
    tags: lights_b, lights_pf, lights_pop_ring_c
    channels:
      red:
        number: exp_playfield-2-32-2
      green:
        number: exp_playfield-2-32-0
      blue:
        number: exp_playfield-2-32-1
      # white:
      #   number: exp_playfield-2-33-0

  l_pop_ring_c_7:
    tags: lights_a, lights_pf, lights_pop_ring_c
    platform: smart_virtual
    # channels:
    #   red:
    #     number: exp_playfield-2- +1
    #   green:
    #     number: exp_playfield-2- +1
    #   blue:
    #     number: exp_playfield-2- +1
    #   white:
    #     number: exp_playfield-2- +2

  l_pop_ring_c_8:
    tags: lights_b, lights_pf, lights_pop_ring_c
    platform: smart_virtual
    # channels:
    #   red:
    #     number: exp_playfield-2- +1
    #   green:
    #     number: exp_playfield-2- -2
    #   blue:
    #     number: exp_playfield-2- +4
    #   white:
    #     number: exp_playfield-2- -1
