#config_version=6

lights:
  # EXP String 1 - lower third
  l_pf_1:
    number: exp_playfield-1-1
    type: rgb
    tags: lights_2a, lights_pf, lights_ci, lights_lower_third
  l_pf_2:
    number: exp_playfield-1-2
    type: grb
    tags: lights_2b, lights_pf, lights_gi, lights_lower_third
