#config_version=6
# Load this instead of lights/minicab.yaml to provide virtual lights instead of physical ones
# because these lights are useful as flipper status checks in the base light player config

lights:
  # EXP String 2 - mini cab
  l_mini_cab_left_secondary:
    platform: smart_virtual
    tags: lights_2a, lights_3a, lights_4a, lights_5a, lights_cab

  l_mini_cab_left:
    platform: smart_virtual
    tags: lights_2b, lights_3b, lights_4b, lights_5b, lights_cab

  l_mini_cab_right:
    platform: smart_virtual
    tags: lights_2a, lights_3c, lights_4c, lights_5c, lights_cab

  l_mini_cab_right_secondary:
    platform: smart_virtual
    tags: lights_2b, lights_3b, lights_4d, lights_5e, lights_cab
