#config_version=6

mode:
  start_events: mode_start_pops_base
  stop_events: mode_stop_pops_base
  priority: 1510

variable_player:
  s_pop_left_active:
    score: 500 * current_player.playfield_multiplier
  s_pop_right_active:
    score: 500 * current_player.playfield_multiplier
  s_pop_center_active:
    score: 500 * current_player.playfield_multiplier

show_player:
  s_pop_left_active:
    pop_flash:
      key: pop_left_show
      action: play
      loops: 0
      show_tokens:
        light_prefix: l_pop_ring_a

  s_pop_right_active:
    pop_flash:
      key: pop_right_show
      action: play
      loops: 0
      show_tokens:
        light_prefix: l_pop_ring_b

  s_pop_center_active:
    pop_flash:
      key: pop_center_show
      action: play
      loops: 0
      show_tokens:
        light_prefix: l_pop_ring_c
