#config_version=6

mode:
  start_events: mode_start_pops_base
  stop_events: mode_stop_pops_base, ball_will_end
  priority: 1510

variable_player:
  base_pop_group_hit:
    score: 500 * current_player.playfield_multiplier

shot_profiles:
  base_pop_profile:
    states:
      - name: singleton

shots:
  base_pop_left:
    profile: base_pop_profile
    switch: s_pop_left
  base_pop_right:
    profile: base_pop_profile
    switch: s_pop_right
  base_pop_center:
    profile: base_pop_profile
    switch: s_pop_center

shot_groups:
  base_pop_group:
    shots:
      - base_pop_left
      - base_pop_right
      - base_pop_center

event_player:
  mode_pops_base_started: [enable_orbit_diverter]
  s_burn_standup_active: [activate_orbit_diverter]
  base_pop_group_hit: [dj_pop_pool]

show_player:
  base_pop_left_hit:
    pop_flash:
      key: pop_left_show
      action: play
      loops: 0
      show_tokens:
        light_prefix: l_pop_ring_a

  base_pop_right_hit:
    pop_flash:
      key: pop_right_show
      action: play
      loops: 0
      show_tokens:
        light_prefix: l_pop_ring_b

  base_pop_center_hit:
    pop_flash:
      key: pop_center_show
      action: play
      loops: 0
      show_tokens:
        light_prefix: l_pop_ring_c
