#config_version=6

mode:
  priority: 9999 #TODO, TBD but high
  start_events: mode_start_music_selection
  stop_events: mode_stop_music_selection, ball_will_end, service_mode_entered
  events_when_started: advance_carousel_to_current_track
  code: music_selection.MusicSelection

mode_settings:
  selectable_items:
    - music_1 # heavy instrumental
    - music_2 # chiptune
    - music_3 # 70s instrumental
    - music_4 # groove instrumental
    - music_5 # music box
    - music_6 # motown
  previous_item_events: reverse_music_selection_carousel
  next_item_events: advance_music_selection_carousel
  select_item_events: s_start_active

slide_player:
  mode_music_selection_started:
    music_selection:
      action: play
  mode_stop_music_selection.1:
    music_selection:
      action: remove
  remove_music_selection_slide:
    music_selection:
      action: remove

combo_switches:
  combo_both_flippers_hold:
    tag_1: left_flipper
    tag_2: right_flipper
    hold_time: 2s
    max_offset_time: 250ms

event_player:
  combo_both_flippers_hold_both: [music_controller_quiet]
  s_left_flipper_secondary_active{device.switches.s_plunger.state == 1}: [reverse_music_selection_carousel, reverse_current_track]
  s_right_flipper_secondary_active{device.switches.s_plunger.state == 1}: [advance_music_selection_carousel, advance_current_track]

  sw_playfield_active: # Active play immediately ends music selection
    - remove_music_selection_slide
    - mode_stop_music_selection
  playfield_active: # Active play immediately ends music selection
    - remove_music_selection_slide
    - mode_stop_music_selection

  music_selection_item_selected: # Carousel selection event
    - remove_music_selection_slide
    - mode_stop_music_selection

  music_track_finished: # Rare case - ball ejected into music selection and the song completes fully with no inputs #actually also happens with 0 duration tracks ending immediately
    - mode_stop_music_selection
