#config_version=6

mode:
  start_events: mode_start_burn_rollovers
  stop_events: mode_complete_burn_rollovers, mode_stop_burn_rollovers
  priority: 1400

variable_player:
  burn_group_lit_hit:
    score: 100 * current_player.playfield_multiplier
  burn_group_unlit_hit:
    score: 1000 * current_player.playfield_multiplier
  burn_group_lit_complete:
    score: 4000 * current_player.playfield_multiplier

event_player:
  burn_group_lit_complete:
    - mode_complete_burn_rollovers
    - increment_playfield_multiplier
    - mode_stop_pops_base
    - mode_start_pops_burnination
    - mode_start_burnination_rollovers

shot_profiles:
  rollover_profile:
    states:
      - name: 'unlit'
        show: 'off'
      - name: 'lit'
        show: 'lit_rollover'
        sync_ms: 50

shots:
  shot_burn_b:
    profile: rollover_profile
    switch: s_burn_b
    show_tokens:
      light: l_burn_b
  shot_burn_u:
    profile: rollover_profile
    switch: s_burn_u
    show_tokens:
      light: l_burn_u
  shot_burn_r:
    profile: rollover_profile
    switch: s_burn_r
    show_tokens:
      light: l_burn_r
  shot_burn_n:
    profile: rollover_profile
    switch: s_burn_n
    show_tokens:
      light: l_burn_n

shot_groups:
  burn_group:
    shots: shot_burn_b, shot_burn_u, shot_burn_r, shot_burn_n
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active
    reset_events: mode_burn_rollovers_started
