#config_version=6

mode:
  start_events: mode_start_burn_rollovers
  stop_events: mode_stop_burn_rollovers, ball_will_end
  priority: 1530

variable_player:
  burn_group_lit_hit:
    points: 100
    rollover_hits: 1
  burn_group_unlit_hit:
    points: 1000
    rollover_hits: 1
  burn_group_lit_complete:
    points: 4000

event_player:
  burn_group_unlit_hit: [dj_rollover_unlit_pool, burn_updated|1ms]
  burn_group_lit_hit: [dj_rollover_lit_pool]
  burn_group_lit_complete:
    - increment_playfield_multiplier
    - burnination_controller_begin
  s_left_flipper_active: [rotate_burn_left, burn_updated|1ms]
  s_right_flipper_active: [rotate_burn_right, burn_updated|1ms]
  mode_burn_rollovers_started: [burn_updated|1ms]
  burn_updated.1:
    widget_show_burn_letters:
      total_lit: {value: 0, type: int}
      b_lit: {value: False, type: bool}
      u_lit: {value: False, type: bool}
      r_lit: {value: False, type: bool}
      n_lit: {value: False, type: bool}

  burn_updated:
    widget_update_burn_letters:
      total_lit:
        value: device.shots.shot_burn_b.state + device.shots.shot_burn_u.state + device.shots.shot_burn_r.state + device.shots.shot_burn_n.state
        type: int
      b_lit:
        value: device.shots.shot_burn_b.state_name == 'lit'
        type: bool
      u_lit:
        value: device.shots.shot_burn_u.state_name == 'lit'
        type: bool
      r_lit:
        value: device.shots.shot_burn_r.state_name == 'lit'
        type: bool
      n_lit:
        value: device.shots.shot_burn_n.state_name == 'lit'
        type: bool

shot_profiles:
  rollover_profile:
    advance_on_hit: True
    states:
      - name: 'unlit'
        show: 'off'
      - name: 'lit'
        show: 'on_color'
        show_tokens:
          color: green
        sync_ms: 50

shots:
  shot_burn_b:
    profile: rollover_profile
    switch: s_burn_b
    show_tokens:
      light: l_burn_b
  shot_burn_u:
    profile: rollover_profile
    switch: s_burn_u
    show_tokens:
      light: l_burn_u
  shot_burn_r:
    profile: rollover_profile
    switch: s_burn_r
    show_tokens:
      light: l_burn_r
  shot_burn_n:
    profile: rollover_profile
    switch: s_burn_n
    show_tokens:
      light: l_burn_n

shot_groups:
  burn_group:
    shots: shot_burn_b, shot_burn_u, shot_burn_r, shot_burn_n
    rotate_left_events: rotate_burn_left
    rotate_right_events: rotate_burn_right
    reset_events: mode_burn_rollovers_started
