#config_version=6

mode:
  start_events: mode_start_queue_game_over_media, game_ending
  stop_events: mode_stop_queue_game_over_media
  use_wait_queue: true
  priority: 9099
  events_when_started: show_game_over_slide, dj_game_over
  stop_on_ball_end: False
  game_mode: False

timers:
  game_over_slide_timer:
    start_value: 5
    end_value: 0
    tick_interval: 1000ms
    direction: down
    start_running: true
    restart_on_complete: false
    control_events:
      - event: flipper_cradle
        action: jump
        value: 1

event_player:
  timer_game_over_slide_timer_complete: [mode_stop_queue_game_over_media]

slide_player:
  show_game_over_slide: game_over
