#config_version=6

mode:
  start_events: mode_start_captive_ball_base
  stop_events: mode_stop_captive_ball_base, ball_will_end
  priority: 1580
  events_when_started: captive_ball_target_dead

shot_profiles:
  captive_ball_base_profile:
    advance_on_hit: False
    states:
      - name: 'dead'
      - name: 'live'

shots:
  captive_ball_target:
    profile: captive_ball_base_profile
    switch: s_captive_ball_presence
    persist_enable: false
    start_enabled: true
    control_events:
      - events: captive_ball_target_dead
        state: 0
      - events: captive_ball_target_live
        state: 1

  captive_ball_combo:
    switch: s_captive_ball_presence
    profile: singleton_profile
    enable_events: enable_captive_ball_combo
    disable_events: disable_captive_ball_combo
    persist_enable: false
    start_enabled: false

timers:
  captive_ball_combo_timeout:
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 300ms #TODO dial in, probably shorter
    start_running: false
    restart_on_complete: false
    control_events:
    - event: timer_captive_ball_combo_timeout_restart
      action: restart

event_player:
  spinner_spinner_left_base_active: [enable_captive_ball_combo, timer_captive_ball_combo_timeout_restart]
  spinner_spinner_left_targeted_active: [enable_captive_ball_combo, timer_captive_ball_combo_timeout_restart]
  timer_captive_ball_combo_timeout_complete: [disable_captive_ball_combo]
  captive_ball_target_live_hit: [dj_captive_ball_pool]
  captive_ball_target_disabled_hit: [dj_captive_ball_weak_pool]

variable_player:
  reset_captive_ball_target_hits:
    captive_ball_target_hits:
      action: set
      int: 0
  captive_ball_target_live_hit:
    captive_ball_target_hits: 1
    points: 1250
  captive_ball_target_disabled_hit:
    points: 200
  captive_ball_combo_hit:
    score: 2500 # flat - should add to the target hit that is multiplied and credits the hit category

random_event_player:
  captive_ball_target_live_hit:
    force_all: true
    disable_random: true
    events:
      - spawn_progressive_spiral_1
      - spawn_progressive_spiral_2
      - spawn_progressive_spiral_3
      - spawn_progressive_spiral_4

show_player:
  captive_ball_target_live_hit:
    cottage_burn:
      action: play
      loops: 2
      key: captive_ring_show
      show_tokens:
        l1: l_captive_ball_ring_1
        l2: l_captive_ball_ring_2
        l3: l_captive_ball_ring_3
        l4: l_captive_ball_ring_4
        l5: l_captive_ball_ring_5
        l6: l_captive_ball_ring_6
        l7: l_captive_ball_ring_7
        l8: l_captive_ball_ring_8

  spawn_progressive_spiral_1:
    slots_progressive_spiral_in:
      key: progressive_slots_1
      loops: 0
      show_tokens:
        color: orange

  spawn_progressive_spiral_2:
    slots_progressive_spiral_in:
      key: progressive_slots_2
      loops: 0
      show_tokens:
        color: yellow

  spawn_progressive_spiral_3:
    slots_progressive_spiral_in:
      key: progressive_slots_3
      loops: 0
      show_tokens:
        color: white

  spawn_progressive_spiral_4:
    slots_progressive_spiral_in:
      key: progressive_slots_4
      loops: 0
      show_tokens:
        color: green
