#config_version=6

mode:
  start_events: mode_start_captive_ball_base
  stop_events: mode_cancel_captive_ball_base
  priority: 1600

shot_profiles:
  captive_ball_base_profile:
    advance_on_hit: false
    states:
      - name: 'live'
      - name: 'disabled'

shots:
  captive_ball_target:
    profile: captive_ball_base_profile
    switch: s_captive_ball_target
    control_events:
      - events: captive_ball_target_disable
        state: 1
      - events: captive_ball_target_enable
        state: 0

variable_player:
  reset_captive_ball_target_hits:
    captive_ball_target_hits:
      action: set
      int: 0
  captive_ball_target_live_hit:
    captive_ball_target_hits: 1
    score: 1250 * current_player.playfield_multiplier
  captive_ball_target_disabled_hit:
    score: 200 * current_player.playfield_multiplier

event_player:
  player_captive_ball_target_hits{current_player.captive_ball_target_hits > 4}:
    - mode_start_generated_slots
  player_captive_ball_target_hits{current_player.captive_ball_target_hits < 4}:
    - drop_target_bank_reset_slots

state_machines:
  captive_ball_manager:
    persist_state: false
    starting_state: qualifying_for_slots
    states:
      qualifying_for_slots:
        label: active
        events_when_started: captive_ball_target_enable
      slots_in_progress:
        label: complete
        events_when_started: captive_ball_target_disable
      paused:
        label: paused
        events_when_started: captive_ball_target_disable
    transitions:
      - source: qualifying_for_slots
        target: slots_in_progress
        events: mode_start_generated_slots
      - source: slots_in_progress
        target: qualifying_for_slots
        events: mode_generated_slots_stopped
        events_when_transitioning: reset_captive_ball_target_hits

      # Paused state in case another mode takeover wants to block slot qualification
      - source: qualifying_for_slots
        target: paused
        events:
      - source: paused
        target: qualifying_for_slots
        events:

light_player:
  "{device.state_machines.captive_ball_manager.state == 'qualifying_for_slots' and device.switches.s_captive_ball_presence.state == 0}":
    l_captive_ball_single: orange
  "{device.state_machines.captive_ball_manager.state == 'qualifying_for_slots' and device.switches.s_captive_ball_presence.state == 1}":
    l_captive_ball_single: 'off'
  "{device.state_machines.captive_ball_manager.state == 'slots_in_progress'}":
    l_captive_ball_single: '003399'

show_player:
  captive_ball_target_live_hit:
    cottage_burn:
      action: play
      loops: 2
      key: captive_ring_show
      show_tokens:
        l1: l_captive_ball_ring_1
        l2: l_captive_ball_ring_2
        l3: l_captive_ball_ring_3
        l4: l_captive_ball_ring_4
        l5: l_captive_ball_ring_5
        l6: l_captive_ball_ring_6
        l7: l_captive_ball_ring_7
        l8: l_captive_ball_ring_8
