#config_version=6
# Sound hooks because ducking is wonky on windows

---
mode:
  priority: 8080
  start_events: ball_started
  stop_events: mode_stop_generated_sound_hooks
sound_player:
  dj_pop_pool:
    pop_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_burnination_pop_hit_pool:
    burnination_pop_hit_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_multiplier_added_pool:
    multiplier_added_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_rollover_lit_pool:
    rollover_lit_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_rollover_unlit_pool:
    rollover_unlit_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_sling_pool:
    sling_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_sling_combo_pool:
    sling_combo_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_intros_pool:
    ball_intros_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_not_enough_credits_pool:
    not_enough_credits_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_end_good_pool:
    ball_end_good_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_end_average_pool:
    ball_end_average_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_end_poor_pool:
    ball_end_poor_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_tilt_warning_pool:
    tilt_warning_pool:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_cash:
    cash:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_theme_70s:
    theme_70s:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_theme_chiptune:
    theme_chiptune:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_theme_heavy_metal:
    theme_heavy_metal:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_theme_instrumental_heavy:
    theme_instrumental_heavy:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_theme_main:
    theme_main:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_at_max_players:
    at_max_players:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_burnination_background:
    burnination_background:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_burnination_pop_up_2:
    burnination_pop_up_2:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_burnination_pop_up_3:
    burnination_pop_up_3:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_burnination_pop_up_4:
    burnination_pop_up_4:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_burnination_pop_up_5:
    burnination_pop_up_5:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_burnination_mode_song:
    burnination_mode_song:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_burnination_rollover_on_target:
    burnination_rollover_on_target:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_cancel:
    cancel:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_cant_incdec_more:
    cant_incdec_more:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_click_bad:
    click_bad:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_click_good:
    click_good:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_decrement:
    decrement:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_high_voltage_disabled:
    high_voltage_disabled:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_high_voltage_enabled:
    high_voltage_enabled:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_increment:
    increment:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_at_launcher:
    ball_at_launcher:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_bootup:
    bootup:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_extra_ball_earned:
    extra_ball_earned:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_game_reset:
    game_reset:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_game_start:
    game_start:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_mpf:
    mpf:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_skill_shot_1_hit:
    skill_shot_1_hit:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_skill_shot_2_hit:
    skill_shot_2_hit:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_skill_shot_3_hit:
    skill_shot_3_hit:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_status_menu:
    status_menu:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_tilted:
    tilted:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_videlectrix:
    videlectrix:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_end_amazing:
    ball_end_amazing:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_end_zero:
    ball_end_zero:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_save_grace:
    ball_save_grace:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_save_sb:
    ball_save_sb:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_search_fail:
    ball_search_fail:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_search_start:
    ball_search_start:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_ball_search_success:
    ball_search_success:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_burnination_pop_completed:
    burnination_pop_completed:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_credit_added:
    credit_added:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_new_high_score:
    new_high_score:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_orbit_looped:
    orbit_looped:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s
  dj_spinner_complete_high:
    spinner_complete_high:
      ducking:
        bus: effects
        attack: 0
        attenuation: 0
        release_point: 0
        release: 0s

