#config_version=6

mode:
  start_events: mode_start_ramps_base
  stop_events: mode_stop_ramps_base, ball_will_end
  priority: 1540

shot_profiles:
  ramp_base_profile:
    advance_on_hit: False
    states:
      - name: 'live'

shots:
  shot_ramp_middle:
    profile: ramp_base_profile
    switch: s_wireform_s_top
  shot_ramp_right:
    profile: ramp_base_profile
    switch: s_wireform_right_top

variable_player:
  #Simple ramp scoring with counting
  shot_ramp_middle_live_hit:
    points: 3000
    ramp_hits: 1
  shot_ramp_right_live_hit:
    points: 5000
    ramp_hits: 1

event_player:
  mode_ramps_base_started: [enable_right_outlane_post_ramp_save]
  shot_ramp_middle_live_hit: [dj_TODO]
  shot_ramp_right_live_hit: [qualify_right_outlane_ramp_save, dj_TODO]
  qualify_right_outlane_ramp_save:
    - activate_right_outlane_post_ramp_save
    - enable_ball_save_right_wireform_save
    - enable_plunger_hold

show_player:
  shot_ramp_middle_live_hit:
    slots_spin_show:
      action: play
      loops: 3
  shot_ramp_right_live_hit:
    slots_diagonal_result_show:
      action: play
      loops: 3
