#config_version=6

autofire_coils:
  slingshot_left:
    ball_search_order: 221
    coil: c_left_sling
    switch: s_left_sling
    enable_events: ball_started, enable_slings
    disable_events: ball_will_end, service_mode_entered, disable_slings

  slingshot_right:
    ball_search_order: 222
    coil: c_right_sling
    switch: s_right_sling
    enable_events: ball_started, enable_slings
    disable_events: ball_will_end, service_mode_entered, disable_slings

  pop_left:
    ball_search_order: 253
    coil: c_pop_left
    switch: s_pop_left
  pop_right:
    ball_search_order: 251
    coil: c_pop_right
    switch: s_pop_right
  pop_center:
    ball_search_order: 252
    coil: c_pop_center
    switch: s_pop_center

#Flippers are just complex autofires
flippers:
  right_flipper:
    main_coil: c_flipper_right_full
    hold_coil: c_flipper_right_hold
    eos_switch: s_right_flipper_eos
    activation_switch: s_right_flipper
    enable_events: ball_started, enable_right_flipper
    disable_events: ball_will_end, service_mode_entered, disable_right_flipper
    use_eos: true

  left_flipper:
    main_coil: c_flipper_left_full
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    eos_switch: s_left_flipper_eos
    enable_events: ball_started, enable_left_flipper
    disable_events: ball_will_end, service_mode_entered, disable_left_flipper
    use_eos: true

  upper_flipper: #left flipper rotation
    ball_search_order: 200
    main_coil: c_flipper_upper_full
    hold_coil: c_flipper_upper_hold
    eos_switch: s_upper_flipper_eos
    activation_switch: s_left_flipper_secondary
    enable_events: ball_started, enable_upper_flipper
    disable_events: ball_will_end, service_mode_entered, disable_upper_flipper
#    use_eos: true
