#config_version=6

# As you add coils, you will define
# their name, number on the board, default_pulse. 

# Visit https://docs.missionpinball.org/en/latest/mechs/coils/ for additional information. 

coils:

# No coils for Expo lol 
  c_auto_plunger:
    platform: smart_virtual
    number: 3208-0
    default_pulse_ms: 12

  c_trough_eject:
    platform: smart_virtual
    number: 3208-1
    default_pulse_ms: 15


  c_flipper_right_full:
    number: 0804-0
    default_pulse_ms: 25

  c_flipper_right_hold:
    number: 0804-1
    default_hold_power: .5
    allow_enable: true

  c_right_sling:
    platform: smart_virtual
    number: 3208-4
    default_pulse_ms: 20


  c_left_sling:
    platform: smart_virtual
    number: 3208-5
    default_pulse_ms: 20

  c_flipper_left_hold:
    number: 0804-2
    default_hold_power: .5
    allow_enable: true

  c_flipper_left_full:
    number: 0804-3
    default_pulse_ms: 25
