#config_version=6

# As you add coils, you will define
# their name, number on the board, default_pulse. 

# Visit https://docs.missionpinball.org/en/latest/mechs/coils/ for additional information. 

coils:

#Board 3208 
  c_auto_plunger:
    number: 3208-0
    default_pulse_ms: settings.auto_plunger_coil_power

  c_trough_eject:
    number: 3208-1
    default_pulse_ms: settings.trough_eject_coil_power


  c_flipper_right_full:
    number: 3208-2
    default_pulse_ms: settings.flipper_main_coil_power

  c_flipper_right_hold:
    number: 3208-3
    default_hold_power: 0.5
    # default_hold_power: settings.flipper_hold_coil_power
    allow_enable: true

  c_right_sling:
    number: 3208-4
    default_pulse_ms: 20


  c_left_sling:
    number: 3208-5
    default_pulse_ms: 20

  c_flipper_left_hold:
    number: 3208-6
    default_hold_power: 0.5
    # default_hold_power: settings.flipper_hold_coil_power
    allow_enable: true

  c_flipper_left_full:
    number: 3208-7
    default_pulse_ms: settings.flipper_main_coil_power

# 1616
  c_gate_left:
    number: 1616-0
    default_pulse_ms: 10
    default_hold_power: 0.25
  c_gate_right:
    number: 1616-1
    default_pulse_ms: 10
    default_hold_power: 0.25
  c_saver_post:
    number: 1616-7
    allow_enable: true
    default_hold_power: .25 #TODO dial in
