#config_version=6

# As you add coils, you will define
# their name, number on the board, default_pulse. 

# Visit https://docs.missionpinball.org/en/latest/mechs/coils/ for additional information. 

coils:

#Board 3208 
  c_auto_plunger:
    number: 3208-0
    default_pulse_ms: 12
    default_hold_power: .125

  c_trough_eject:
    number: 3208-1
    default_pulse_ms: 15


  c_flipper_right_full:
    number: 3208-2
    default_pulse_ms: 25

  c_flipper_right_hold:
    number: 3208-3
    default_hold_power: .125
    allow_enable: true

  c_right_sling:
    number: 3208-4
    default_pulse_ms: 20


  c_left_sling:
    number: 3208-5
    default_pulse_ms: 20

  c_flipper_left_hold:
    number: 3208-6
    default_hold_power: .125
    allow_enable: true

  c_flipper_left_full:
    number: 3208-7
    default_pulse_ms: 25

#TODO
#Board 1616
#  c_flipper_mini_hold:
#    number: 1616-1
#    allow_enable: true
#  c_flipper_mini_full:
#    number: 1616-2

