#config_version=6

# As you add coils, you will define
# their name, number on the board, default_pulse. 

# Visit https://docs.missionpinball.org/en/latest/mechs/coils/ for additional information. 

coils:

#Board 3208
  # J4
  c_auto_plunger:
    number: 3208-0
    default_pulse_ms: settings.auto_plunger_coil_power

  c_trough_eject:
    number: 3208-1
    default_pulse_ms: settings.trough_eject_coil_power


  c_flipper_right_full:
    number: 3208-2
    default_pulse_ms: settings.flipper_main_coil_power

  c_flipper_right_hold:
    number: 3208-3
    default_hold_power: 0.5
    # default_hold_power: settings.flipper_hold_coil_power
    allow_enable: true

  c_right_sling:
    number: 3208-4
    default_pulse_ms: settings.slingshot_power

  c_left_sling:
    number: 3208-5
    default_pulse_ms: settings.slingshot_power

  c_flipper_left_hold:
    number: 3208-6
    default_hold_power: 0.5
    # default_hold_power: settings.flipper_hold_coil_power
    allow_enable: true

  c_flipper_left_full:
    number: 3208-7
    default_pulse_ms: settings.flipper_main_coil_power

# 1616
  # J3
  c_gate_left:
    number: 1616-0
    default_pulse_ms: settings.gate_power
    default_hold_power: 0.375
  c_gate_right:
    number: 1616-1
    default_pulse_ms: settings.gate_power
    default_hold_power: 0.375

  c_pop_right:
    number: 1616-4
    default_pulse_ms: settings.pop_bumper_power
  c_pop_center:
    number: 1616-5
    default_pulse_ms: settings.pop_bumper_power
  c_pop_left:
    number: 1616-6
    default_pulse_ms: settings.pop_bumper_power

  c_slot_bank_reset:
    number: 1616-7 #temp moved from blown up 13
    default_pulse_ms: 30
  c_slot_bank_right_drop:
    number: 1616-2
  c_slot_bank_center_drop:
    number: 1616-3
#  c_slot_bank_left_drop:
#    number: 1616-x #temp unavailable, maybe used at position 7 in the end

  # J4
  c_orbit_diverter_full:
    number: 1616-8
    default_pulse_ms: settings.diverter_flipper_power
    allow_enable: true
    default_hold_power: .125


  c_orbit_diverter_hold:
    number: 1616-9
    default_hold_power: .5
    allow_enable: true

  c_flipper_upper_full:
    number: 1616-10
    default_pulse_ms: 25

  c_flipper_upper_hold:
    number: 1616-11
    default_hold_power: .5
    allow_enable: true

  c_vuk:
    number: 1616-12
    default_pulse_ms: 32

  c_right_outlane_post:
    number: 1616-14
    allow_enable: true
    default_pulse_ms: 20
    default_hold_power: .375

  c_saver_post:
    number: 1616-15
    allow_enable: true
    default_pulse_ms: 20
    default_hold_power: .375

# 0024 drivers for LEDs
  # J1
  c_start_driver:
    number: 0024-2
    allow_enable: true

lights: #TODO move this to an env-specific light
  l_start:
    number: c_start_driver
    platform: drivers
    type: r

#dual_wound_coils: #TODO fix mpf crash when using dual wound coil
#  c_orbit_diverter_dual_coil:
#    hold_coil: c_orbit_diverter_hold
#    main_coil: c_orbit_diverter_full
#    eos_switch: s_orbit_diverter_eos

diverters:
  orbit_diverter:
    activate_events: activate_orbit_diverter
    deactivate_events: deactivate_orbit_diverter, disable_orbit_diverter, ball_ending
    enable_events: enable_orbit_diverter
    disable_events: disable_orbit_diverter, ball_ending
    activation_coil: c_orbit_diverter_full #c_orbit_diverter_dual_coil
    activation_switches:
    activation_time: 6s
    feeder_devices: bd_plunger, playfield
