#config_version=6

config:
  - fast.yaml
  - displays.yaml
  - machine.yaml
  - lights.yaml
  - coils.yaml
  - switches.yaml
  - keyboard.yaml
  - autofires.yaml
  - ball_devices.yaml
  - modes.yaml
  
player_vars:
  sling_hits:
    initial_value: 0


