#config_version=6

# This file is used by `mpf game` when no -c option is given.
# Usually this will be when testing on the CLI completely virtually,
# or while debugging in the cabinet long term
config:
  - env_cabinet.yaml
