#config_version=6

config:
  - settings.yaml
  - fast.yaml
  - displays.yaml
  - machine.yaml
  - lights/config.yaml
  - coils.yaml
  - switches.yaml
  - keyboard.yaml
  - autofires.yaml
  - ball_devices.yaml
  - modes.yaml
  - player_vars.yaml
  - future.yaml
