#config_version=6

diverters:
  div_left_controlled_ball_gate: #CCW orbit: left gate lifts via right orbital inbound
    activation_coil: c_gate_left
    type: hold
    activation_time: 3s
    enable_events: enable_lift_left_cbg
    disable_events: disable_lift_left_cbg, ball_ending
    activation_switches: s_right_orbit
    activate_events: activate_left_cbg
    deactivate_events: deactivate_left_cbg

  div_right_controlled_ball_gate: #CW orbit: right gate lifts via left orbital inbound
    activation_coil: c_gate_right
    type: hold
    activation_time: 3s
    enable_events: enable_lift_right_cbg
    disable_events: disable_lift_right_cbg, ball_ending
    activation_switches: s_left_orbit
    activate_events: activate_right_cbg
    deactivate_events: deactivate_right_cbg, disable_lift_right_cbg, ball_ending

  div_saver_post:
    activation_coil: c_saver_post
    type: hold
    activation_time: 10s
    enable_events: enable_saver_post
    disable_events: disable_saver_post, ball_ending
    activate_events: activate_saver_post
    deactivate_events: deactivate_saver_post, disable_saver_post, ball_ending

  div_right_controlled_ball_gate_alternative_profile: #demo for allowing a different configuration (eg action button or alternative trigger reasons to main config)
    activation_coil: c_gate_right
    type: hold
    activation_time: 5s
    enable_events: enable_lift_right_cbg_alt
    disable_events: disable_lift_right_cbg_alt, ball_ending
    activation_switches: s_left_orbit, s_start #no action button yet, so use start for platform consistency
    deactivation_switches: #TODO - probably needs to be on same platform as the coil
    activate_events: activate_right_cbg_alt
    deactivate_events: deactivate_right_cbg_alt, disable_lift_right_cbg_alt, ball_ending
