#config_version=6

fast:
  net:
    port: /dev/ttyACM0
    controller: neuron
    io_loop:

      "0804":
        model: FP-I/O-0804
        order: 1

  exp:
    port: /dev/ttyACM1
    boards:
      neuron:
        model: FP-EXP-2000
#      exp_playfield:
#        model: FP-EXP-0071
