#config_version=6

# Devices that exist in the plan but are not yet physically installed
#   lights are already in a separate file in the light subdir

switches:
  #For coils
  s_pop_left:
    number: 801
    platform: smart_virtual

  s_pop_right:
    number: 802
    platform: smart_virtual
  s_pop_center:
    number: 803
    platform: smart_virtual

  s_vuk_presence:
    number: 804
    platform: smart_virtual
    type: 'NC'

  s_upper_sling:
    number: 805
    platform: smart_virtual

  s_upper_flipper_eos:
    number: 806
    platform: smart_virtual
    type: 'NC' #maybe nc

  #Targets
  s_drop_left_down: #TODO learn how drop switching works (are there two?)
    number: 807
    platform: smart_virtual

  #Rollovers
  s_burn_b:
    number: 808
    platform: smart_virtual
  s_burn_u:
    number: 809
    platform: smart_virtual
  s_burn_r:
    number: 810
    platform: smart_virtual
  s_burn_n:
    number: 811
    platform: smart_virtual

  #Spinners
  s_spinner_left:
    number: 812
    platform: smart_virtual
  s_spinner_right:
    number: 813
    platform: smart_virtual

  #Passthrough optos
  s_left_orbit:
    number: 814
    platform: smart_virtual
  s_right_orbit:
    number: 815
    platform: smart_virtual
  s_horseshoe:
    number: 816
    platform: smart_virtual

  s_wireform_s_entry:
    number: 817
    platform: smart_virtual
  s_wireform_s_exit:
    number: 818
    platform: smart_virtual
  s_wireform_left_top:
    number: 819
    platform: smart_virtual
  s_wireform_right_top:
    number: 820
    platform: smart_virtual

  s_drop_bank_left:
    number: 821
    platform: smart_virtual
  s_drop_bank_center:
    number: 822
    platform: smart_virtual
  s_drop_bank_right:
    number: 823
    platform: smart_virtual

coils:
  c_pop_left:
    number: 3001
    platform: smart_virtual
  c_pop_right:
    number: 3002
    platform: smart_virtual
  c_pop_center:
    number: 3003
    platform: smart_virtual

  c_vuk:
    number: 3004
    platform: smart_virtual
    default_pulse_ms: 20 #TODO dial in

  c_upper_sling:
    number: 3005
    platform: smart_virtual

  c_gate_left:
    number: 3006
    platform: smart_virtual
    default_pulse_ms: 10
    default_hold_power: 0.25
  c_gate_right:
    number: 3007
    platform: smart_virtual
    default_pulse_ms: 10
    default_hold_power: 0.25

  c_drop_left_reset:
    number: 3008
    platform: smart_virtual
  c_drop_left_knockdown:
    default_pulse_ms: 10 #TODO dial in
    number: 3009
    platform: smart_virtual

  c_saver_post:
    number: 3010
    platform: smart_virtual
    allow_enable: true
    default_hold_power: .25 #TODO dial in

  c_flipper_upper_hold:
    number: 3011
    platform: smart_virtual
    default_hold_power: .5
    allow_enable: true

  c_flipper_upper_full:
    number: 3012
    platform: smart_virtual
    default_pulse_ms: 25

  c_slot_bank_reset:
    number: 3013
    platform: smart_virtual

ball_devices:
  bd_vuk:
    ball_switches: s_vuk_presence
    eject_coil: c_vuk
    eject_timeouts: 1s

autofire_coils:
  pop_left:
    coil: c_pop_left
    switch: s_pop_left
  pop_right:
    coil: c_pop_right
    switch: s_pop_right
  pop_center:
    coil: c_pop_center
    switch: s_pop_center

  slingshot_upper:
    coil: c_upper_sling
    switch: s_upper_sling


flippers:
  upper_flipper:
    main_coil: c_flipper_upper_full
    hold_coil: c_flipper_upper_hold
    eos_switch: s_upper_flipper_eos
    activation_switch: #s_mini_flipper #TODO this is from real hardware
    enable_events: ball_started, enableAutofire #, machine_reset_phase_3 #P3 for testing
    disable_events: ball_will_end, service_mode_entered, disableAutofire
    use_eos: true

drop_targets:
  dt_left:
    switch: s_drop_bank_left
  dt_center:
    switch: s_drop_bank_center
  dt_right:
    switch: s_drop_bank_right

drop_target_banks:
  slots_target_bank:
    drop_targets: dt_left, dt_center, dt_right
    reset_coils: c_slot_bank_reset
    reset_events: drop_target_bank_reset_slots, machine_reset_phase_3, ball_starting #TODO do I really need to declare the default pair?
    reset_on_complete: #No
