#config_version=6

# Devices that exist in the plan but are not yet physically installed
#   lights are already in a separate file in the light subdir
#   switches are in switches dir

coils:
  c_saver_post:
    platform: smart_virtual
    number: 111
    allow_enable: true
    # default_pulse_ms: settings.saver_post_power
    # default_hold_power: .375
