#config_version=6

# Devices that exist in the plan but are not yet physically installed
#   lights are already in a separate file in the light subdir
#   switches are in switches dir

# coils: #Empty for now!
