#config_version=6
---
diverters:
  div_right_controlled_ball_gate:
    activation_coil: c_gate_right
    type: hold
    activation_time: 3s
    enable_events: enable_right_controlled_ball_gate
    disable_events: disable_right_controlled_ball_gate,ball_ending
    activate_events: activate_right_controlled_ball_gate
    deactivate_events: deactivate_right_controlled_ball_gate,disable_right_controlled_ball_gate,ball_ending
    activation_switches: s_left_orbit_outer
  div_right_controlled_ball_gate_alternative_profile:
    activation_coil: c_gate_right
    type: hold
    activation_time: 6s
    enable_events: enable_right_controlled_ball_gate_alternative_profile
    disable_events: disable_right_controlled_ball_gate_alternative_profile,ball_ending
    activate_events: activate_right_controlled_ball_gate_alternative_profile
    deactivate_events: deactivate_right_controlled_ball_gate_alternative_profile,disable_right_controlled_ball_gate_alternative_profile,ball_ending
    activation_switches: s_left_orbit_outer
  div_left_controlled_ball_gate:
    activation_coil: c_gate_left
    type: hold
    activation_time: 3s
    enable_events: enable_left_controlled_ball_gate
    disable_events: disable_left_controlled_ball_gate,ball_ending
    activate_events: activate_left_controlled_ball_gate
    deactivate_events: deactivate_left_controlled_ball_gate,disable_left_controlled_ball_gate,ball_ending
    activation_switches: s_right_orbit_outer
  div_saver_post:
    activation_coil: c_saver_post
    type: hold
    activation_time: 10s
    enable_events: enable_saver_post
    disable_events: disable_saver_post,ball_ending
    activate_events: activate_saver_post
    deactivate_events: deactivate_saver_post,disable_saver_post,ball_ending
  div_right_outlane_post:
    activation_coil: c_right_outlane_post
    type: hold
    activation_time: 3s
    enable_events: enable_right_outlane_post
    disable_events: disable_right_outlane_post,ball_ending
    activate_events: activate_right_outlane_post
    deactivate_events: deactivate_right_outlane_post,disable_right_outlane_post,ball_ending
    activation_switches: s_right_outer_lane
  div_right_outlane_post_ramp_save:
    activation_coil: c_right_outlane_post
    type: hold
    activation_time: 7s
    enable_events: enable_right_outlane_post_ramp_save
    disable_events: disable_right_outlane_post_ramp_save,ball_ending
    activate_events: activate_right_outlane_post_ramp_save
    deactivate_events: deactivate_right_outlane_post_ramp_save,disable_right_outlane_post_ramp_save,ball_ending
    targets_when_active: bd_plunger
    targets_when_inactive: bd_trough

