#config_version=6
---
sound_player:
  dj_pop_pool: pop_pool
  dj_burnination_pop_hit_pool: burnination_pop_hit_pool
  dj_multiplier_added_pool: multiplier_added_pool
  dj_bonus_multiplier_added_pool: bonus_multiplier_added_pool
  dj_rollover_lit_pool: rollover_lit_pool
  dj_rollover_unlit_pool: rollover_unlit_pool
  dj_sling_pool: sling_pool
  dj_sling_combo_pool: sling_combo_pool
  dj_not_enough_credits_pool: not_enough_credits_pool
  dj_cash: cash
  dj_at_max_players: at_max_players
  dj_burnination_pop_up_1: burnination_pop_up_1
  dj_burnination_pop_up_2: burnination_pop_up_2
  dj_burnination_pop_up_3: burnination_pop_up_3
  dj_burnination_pop_up_4: burnination_pop_up_4
  dj_burnination_pop_up_5: burnination_pop_up_5
  dj_burnination_rollover_on_target: burnination_rollover_on_target
  dj_cancel: cancel
  dj_cant_incdec_more: cant_incdec_more
  dj_click_bad: click_bad
  dj_click_good: click_good
  dj_decrement: decrement
  dj_high_voltage_disabled: high_voltage_disabled
  dj_high_voltage_enabled: high_voltage_enabled
  dj_increment: increment
  dj_attract_music_pool:
    attract_music_pool:
      bus: music
      events_when_stopped: music_track_finished
  dj_theme_70s:
    theme_70s:
      bus: music
      events_when_stopped: music_track_finished
  dj_theme_chiptune:
    theme_chiptune:
      bus: music
      events_when_stopped: music_track_finished
  dj_theme_heavy_metal:
    theme_heavy_metal:
      bus: music
      events_when_stopped: music_track_finished
  dj_theme_instrumental_heavy:
    theme_instrumental_heavy:
      bus: music
      events_when_stopped: music_track_finished
  dj_theme_instrumental_steel:
    theme_instrumental_steel:
      bus: music
      events_when_stopped: music_track_finished
  dj_theme_motown:
    theme_motown:
      bus: music
      events_when_stopped: music_track_finished
  dj_theme_music_box:
    theme_music_box:
      bus: music
      events_when_stopped: music_track_finished
  dj_theme_main:
    theme_main:
      bus: music
      events_when_stopped: special_music_finished
  dj_burnination_mode_song:
    burnination_mode_song:
      bus: music
      events_when_stopped: special_music_finished
  dj_burnination_background:
    burnination_background:
      bus: music
  dj_extra_ball_earned:
    extra_ball_earned:
      bus: music
  dj_game_reset:
    game_reset:
      bus: music
  dj_mpf:
    mpf:
      bus: music
  dj_videlectrix:
    videlectrix:
      bus: music
  dj_bootup:
    bootup:
      bus: music
  dj_status_menu:
    status_menu:
      bus: music
  dj_tilted:
    tilted:
      bus: music
  dj_music_stop:
    music_stop:
      bus: music
  dj_stop_burnination_background:
    burnination_background:
      bus: music
      action: stop
  dj_stop_burnination_mode_song:
    burnination_mode_song:
      bus: music
      action: stop
      events_when_stopped: special_music_finished
  dj_ball_intros_pool:
    ball_intros_pool:
      bus: voice
  dj_ball_at_launcher:
    ball_at_launcher:
      bus: voice
  dj_game_start:
    game_start:
      bus: voice
  dj_game_over:
    game_over:
      bus: voice
  dj_ball_end_good_pool:
    ball_end_good_pool:
      bus: voice
      events_when_stopped: dj_end_quip_complete
  dj_ball_end_average_pool:
    ball_end_average_pool:
      bus: voice
      events_when_stopped: dj_end_quip_complete
  dj_ball_end_poor_pool:
    ball_end_poor_pool:
      bus: voice
      events_when_stopped: dj_end_quip_complete
  dj_tilt_warning_pool:
    tilt_warning_pool:
      bus: voice
  dj_skill_shot_1_hit:
    skill_shot_1_hit:
      bus: voice
  dj_skill_shot_2_hit:
    skill_shot_2_hit:
      bus: voice
  dj_skill_shot_3_hit:
    skill_shot_3_hit:
      bus: voice
  dj_ball_end_amazing:
    ball_end_amazing:
      bus: voice
      events_when_stopped: dj_end_quip_complete
  dj_ball_end_zero:
    ball_end_zero:
      bus: voice
      events_when_stopped: dj_end_quip_complete
  dj_ball_save_grace:
    ball_save_grace:
      bus: voice
  dj_ball_save_sb:
    ball_save_sb:
      bus: voice
  dj_ball_search_fail:
    ball_search_fail:
      bus: voice
  dj_ball_search_start:
    ball_search_start:
      bus: voice
  dj_ball_search_success:
    ball_search_success:
      bus: voice
  dj_burnination_pop_completed:
    burnination_pop_completed:
      bus: voice
  dj_credit_added:
    credit_added:
      bus: voice
  dj_new_high_score:
    new_high_score:
      bus: voice
  dj_orbit_looped:
    orbit_looped:
      bus: voice
  dj_spinner_complete_high:
    spinner_complete_high:
      bus: voice

