#config_version=6
---
sound_player:
  dj_pop_pool:
    pop_pool:
      bus: effects
  dj_burnination_pop_hit_pool:
    burnination_pop_hit_pool:
      bus: effects
  dj_multiplier_added_pool:
    multiplier_added_pool:
      bus: effects
  dj_rollover_lit_pool:
    rollover_lit_pool:
      bus: effects
  dj_rollover_unlit_pool:
    rollover_unlit_pool:
      bus: effects
  dj_sling_pool:
    sling_pool:
      bus: effects
  dj_sling_combo_pool:
    sling_combo_pool:
      bus: effects
  dj_not_enough_credits_pool:
    not_enough_credits_pool:
      bus: effects
  dj_cash:
    cash:
      bus: effects
  dj_at_max_players:
    at_max_players:
      bus: effects
  dj_burnination_pop_up_1:
    burnination_pop_up_1:
      bus: effects
  dj_burnination_pop_up_2:
    burnination_pop_up_2:
      bus: effects
  dj_burnination_pop_up_3:
    burnination_pop_up_3:
      bus: effects
  dj_burnination_pop_up_4:
    burnination_pop_up_4:
      bus: effects
  dj_burnination_pop_up_5:
    burnination_pop_up_5:
      bus: effects
  dj_burnination_rollover_on_target:
    burnination_rollover_on_target:
      bus: effects
  dj_cancel:
    cancel:
      bus: effects
  dj_cant_incdec_more:
    cant_incdec_more:
      bus: effects
  dj_click_bad:
    click_bad:
      bus: effects
  dj_click_good:
    click_good:
      bus: effects
  dj_decrement:
    decrement:
      bus: effects
  dj_high_voltage_disabled:
    high_voltage_disabled:
      bus: effects
  dj_high_voltage_enabled:
    high_voltage_enabled:
      bus: effects
  dj_increment:
    increment:
      bus: effects
  dj_ball_intros_pool:
    ball_intros_pool:
      bus: music
  dj_theme_70s:
    theme_70s:
      bus: music
  dj_theme_chiptune:
    theme_chiptune:
      bus: music
  dj_theme_heavy_metal:
    theme_heavy_metal:
      bus: music
  dj_theme_instrumental_heavy:
    theme_instrumental_heavy:
      bus: music
  dj_theme_instrumental_steel:
    theme_instrumental_steel:
      bus: music
  dj_theme_main:
    theme_main:
      bus: music
  dj_burnination_mode_song:
    burnination_mode_song:
      bus: music
  dj_burnination_background:
    burnination_background:
      bus: music
  dj_ball_at_launcher:
    ball_at_launcher:
      bus: music
  dj_extra_ball_earned:
    extra_ball_earned:
      bus: music
  dj_game_reset:
    game_reset:
      bus: music
  dj_game_start:
    game_start:
      bus: music
  dj_mpf:
    mpf:
      bus: music
  dj_videlectrix:
    videlectrix:
      bus: music
  dj_bootup:
    bootup:
      bus: music
  dj_status_menu:
    status_menu:
      bus: music
  dj_tilted:
    tilted:
      bus: music
  dj_stop_burnination_background:
    burnination_background:
      bus: music
      action: stop
  dj_stop_burnination_mode_song:
    burnination_mode_song:
      bus: music
      action: stop
  dj_ball_end_good_pool:
    ball_end_good_pool:
      bus: voice
      events_when_stopped: dj_end_quip_complete
  dj_ball_end_average_pool:
    ball_end_average_pool:
      bus: voice
      events_when_stopped: dj_end_quip_complete
  dj_ball_end_poor_pool:
    ball_end_poor_pool:
      bus: voice
      events_when_stopped: dj_end_quip_complete
  dj_tilt_warning_pool:
    tilt_warning_pool:
      bus: voice
  dj_skill_shot_1_hit:
    skill_shot_1_hit:
      bus: voice
  dj_skill_shot_2_hit:
    skill_shot_2_hit:
      bus: voice
  dj_skill_shot_3_hit:
    skill_shot_3_hit:
      bus: voice
  dj_ball_end_amazing:
    ball_end_amazing:
      bus: voice
      events_when_stopped: dj_end_quip_complete
  dj_ball_end_zero:
    ball_end_zero:
      bus: voice
      events_when_stopped: dj_end_quip_complete
  dj_ball_save_grace:
    ball_save_grace:
      bus: voice
  dj_ball_save_sb:
    ball_save_sb:
      bus: voice
  dj_ball_search_fail:
    ball_search_fail:
      bus: voice
  dj_ball_search_start:
    ball_search_start:
      bus: voice
  dj_ball_search_success:
    ball_search_success:
      bus: voice
  dj_burnination_pop_completed:
    burnination_pop_completed:
      bus: voice
  dj_credit_added:
    credit_added:
      bus: voice
  dj_new_high_score:
    new_high_score:
      bus: voice
  dj_orbit_looped:
    orbit_looped:
      bus: voice
  dj_spinner_complete_high:
    spinner_complete_high:
      bus: voice

