#config_version=6
---
flasher_player:
  ss_elbow_downwards_hit:
    gl_ss_elbow_downwards:
      ms: 400ms
      color: purple
  ss_elbow_upwards_hit:
    gl_ss_elbow_upwards:
      ms: 400ms
      color: purple
  ss_horseshoe_clockwise_hit:
    gl_ss_horseshoe_clockwise:
      ms: 400ms
      color: purple
  ss_horseshoe_widdershins_hit:
    gl_ss_horseshoe_widdershins:
      ms: 400ms
      color: purple
  ss_left_orbit_open_hit:
    gl_ss_left_orbit_open:
      ms: 400ms
      color: purple
  ss_left_orbit_closed_hit:
    gl_ss_left_orbit_closed:
      ms: 400ms
      color: purple
  ss_right_orbit_open_hit:
    gl_ss_right_orbit_open:
      ms: 400ms
      color: purple
  ss_right_orbit_closed_hit:
    gl_ss_right_orbit_closed:
      ms: 400ms
      color: purple
  ss_right_ramp_summit_hit:
    gl_ss_right_ramp_summit:
      ms: 400ms
      color: purple
  ss_right_ramp_travel_hit:
    gl_ss_right_ramp_travel:
      ms: 400ms
      color: purple
  ss_right_outlane_escape_hit:
    gl_ss_right_outlane_escape:
      ms: 400ms
      color: purple
  ss_s_ramp_summit_hit:
    gl_ss_s_ramp_summit:
      ms: 400ms
      color: purple
  ss_s_ramp_travel_hit:
    gl_ss_s_ramp_travel:
      ms: 400ms
      color: purple
  ss_subway_travel_hit:
    gl_ss_subway_travel:
      ms: 400ms
      color: purple

