#config_version=6
---
show_player:
  ss_elbow_downwards_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_elbow_downwards_hook
      show_tokens:
        light: gl_ss_elbow_downwards
        color: purple
  ss_elbow_upwards_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_elbow_upwards_hook
      show_tokens:
        light: gl_ss_elbow_upwards
        color: purple
  ss_horseshoe_clockwise_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_horseshoe_clockwise_hook
      show_tokens:
        light: gl_ss_horseshoe_clockwise
        color: purple
  ss_horseshoe_widdershins_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_horseshoe_widdershins_hook
      show_tokens:
        light: gl_ss_horseshoe_widdershins
        color: purple
  ss_left_orbit_open_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_left_orbit_open_hook
      show_tokens:
        light: gl_ss_left_orbit_open
        color: purple
  ss_left_orbit_closed_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_left_orbit_closed_hook
      show_tokens:
        light: gl_ss_left_orbit_closed
        color: purple
  ss_right_orbit_open_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_right_orbit_open_hook
      show_tokens:
        light: gl_ss_right_orbit_open
        color: purple
  ss_right_orbit_closed_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_right_orbit_closed_hook
      show_tokens:
        light: gl_ss_right_orbit_closed
        color: purple
  ss_right_ramp_summit_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_right_ramp_summit_hook
      show_tokens:
        light: gl_ss_right_ramp_summit
        color: purple
  ss_right_ramp_travel_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_right_ramp_travel_hook
      show_tokens:
        light: gl_ss_right_ramp_travel
        color: purple
  ss_right_outlane_escape_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_right_outlane_escape_hook
      show_tokens:
        light: gl_ss_right_outlane_escape
        color: purple
  ss_s_ramp_summit_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_s_ramp_summit_hook
      show_tokens:
        light: gl_ss_s_ramp_summit
        color: purple
  ss_s_ramp_travel_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_s_ramp_travel_hook
      show_tokens:
        light: gl_ss_s_ramp_travel
        color: purple
  ss_subway_travel_hit:
    one_hundred_ms_flash:
      loops: 5
      key: ss_subway_travel_hook
      show_tokens:
        light: gl_ss_subway_travel
        color: purple

