#config_version=6

keyboard:
  z:
    switch: s_left_flipper
  x:
    switch: s_right_flipper
  ' ':
    switch: s_mini_flipper
  a:
    switch: s_left_sling
  s:
    switch: s_right_sling
  q:
    switch: s_start
  1:
    switch: s_left_outer_lane
  2:
    switch: s_left_inner_lane
  3:
    switch: s_right_inner_lane
  4:
    switch: s_right_outer_lane
  5:
    switch: s_plunger


  8:
    switch: s_trough_ball_3
    toggle: true
  9:
    switch: s_trough_ball_2
    toggle: true
  0:
    switch: s_trough_ball_1
    toggle: true
