#config_version=6

light_settings:
  default_fade_ms: 40

# led name can be anything you want, 
# the number is the board its on playfield,
# port 1, led 1 in the chain.
# For the 2nd led, it would be number: playfield-1-2

lights:
  # EXP String 1 - lower third
  l_pf_1:
    number: exp_playfield-1-1
    type: rgb
    tags: lights_a, lights_pf, lights_ci, lights_all
  l_pf_2:
    number: exp_playfield-1-2
    type: grb
    tags: lights_b, lights_pf, lights_gi, lights_all

  # EXP String 2 - mini cab
  l_mini_cab_mini:
    number: exp_playfield-2-1
    type: rgb
    tags: lights_a, lights_cab, lights_all

  l_mini_cab_left:
    number: exp_playfield-2-2
    type: rgb
    tags: lights_b, lights_cab, lights_all

  l_mini_cab_right:
    number: exp_playfield-2-3
    type: rgb
    tags: lights_a, lights_cab, lights_all
