#config_version=6

# led name can be anything you want, 
# the number is the board its on playfield,
# port 1, led 1 in the chain.
# For the 2nd led, it would be number: playfield-1-2

lights:
  l_demo_1:
    number: exp_playfield-1-1
    type: rgb
  l_demo_2:
    number: exp_playfield-1-2
    type: grb

  l_mini_cab_mini:
    number: exp_playfield-2-1
    type: rgb
  l_mini_cab_left:
    number: exp_playfield-2-2
    type: rgb
  l_mini_cab_right:
    number: exp_playfield-2-3
    type: rgb
