#config_version=6

modes:
  - attract
  - base
  - burn_rollovers
  - burnination_rollovers
  - lower_lanes_base
  - pops_base
  - pops_burnination
  - pops_burninated
  - slings_base
  - skillshot_base
