#config_version=6

modes:
  - attract
  - base
  - high_score
  - music_selection
  - music_controller
  - backbox_controller
  # - bonus #GSPF bonus off for now since nothing scores into it
  - code_base
  - priority_shows
  - ball_saves
  - skillshot_base
  - lower_lanes_base
  - ramps_base
  - slings_base
  - slings_dead
  - burn_rollovers
  - burnination_controller
  - burnination_rollovers
  - pops_base
  - pops_burnination
  - pops_burninated
  - spinners_base
  - captive_ball_base
  - slots_controller
  - drops_base
  - targets_base
  - tilt #base+override
  - queue_end_quip
  - service #builtin

  # and dont forget the modes in generated_modes.yaml
