#config_version=6

modes:
  - attract
  - base
  - backbox_controller
  - code_base
  - priority_shows
  - ball_saves
  - skillshot_base
  - lower_lanes_base
  - slings_base
  - slings_dead
  - burn_rollovers
  - burnination_controller
  - burnination_rollovers
  - pops_base
  - pops_burnination
  - pops_burninated
  - spinners_base
  - captive_ball_base
  - slots_controller
  - tilt #builtin
  - queue_end_quip

  # and dont forget the modes in generated_modes.yaml
