#config_version=6

modes:
  - attract
  - base
  - priority_shows
  - ball_saves
  - skillshot_base
  - lower_lanes_base
  - slings_base
  - slings_dead
  - burn_rollovers
  - burnination_rollovers
  - pops_base
  - pops_burnination
  - pops_burninated
