#config_version=6

lights:
  # EXP String 1 - lower third
  l_pf_1:
    number: exp_playfield-1-1
    type: rgb
    tags: lights_a, lights_pf, lights_ci
  l_pf_2:
    number: exp_playfield-1-2
    type: grb
    tags: lights_b, lights_pf, lights_gi

  # Cobrapin star post ring - RGB, no hax needed
  l_star_ring_a_1:
    number: exp_playfield-1-3
    type: rgb
    tags: lights_a, lights_pf, lights_star_ring_a
  l_star_ring_a_2:
    number: exp_playfield-1-4
    type: rgb
    tags: lights_b, lights_pf, lights_star_ring_a
  l_star_ring_a_3:
    number: exp_playfield-1-5
    type: rgb
    tags: lights_a, lights_pf, lights_star_ring_a
  l_star_ring_a_4:
    number: exp_playfield-1-6
    type: rgb
    tags: lights_b, lights_pf, lights_star_ring_a
  l_star_ring_a_5:
    number: exp_playfield-1-7
    type: rgb
    tags: lights_a, lights_pf, lights_star_ring_a
  l_star_ring_a_6:
    number: exp_playfield-1-8
    type: rgb
    tags: lights_b, lights_pf, lights_star_ring_a
  l_star_ring_a_7:
    number: exp_playfield-1-9
    type: rgb
    tags: lights_a, lights_pf, lights_star_ring_a
  l_star_ring_a_8:
    number: exp_playfield-1-10
    type: rgb
    tags: lights_b, lights_pf, lights_star_ring_a

