#config_version=6

player_vars:
  ball_start_time:
    initial_value: 0
    value_type: float
  ball_end_time:
    initial_value: -1
    value_type: float

  points: # These represent scoring before modifiers are applied (and some scoring may bypass points)
    initial_value: 0
    value_type: int

  previous_ball_score:
    initial_value: 0
    value_type: int
  ball_score:
    initial_value: 0
    value_type: int

  playfield_multiplier:
    initial_value: 1
    value_type: int

  # Automatically hooked into by bonus mode behavior
  bonus_multiplier:
    initial_value: 1
    value_type: int

  # Skill shots
  total_skillshot_successes:
    initial_value: 0

  skillshot_of_an_artist_successes:
    initial_value: 0

  skillshot_2_successes:
    initial_value: 0

  skillshot_3_successes:
    initial_value: 0

  # misc features that count
  sling_hits:
    initial_value: 0
  spinner_spins:
    initial_value: 0
  cheat_multiball_spins_left_to_qualify:
    initial_value: 30 #settings.cheat_multiball_spins_to_qualify
  half_spinner_spins: # this counts to 1 to save a half spin, and 2 to reset and increment a spinner spin instead
    initial_value: 0

  ramp_hits:
    initial_value: 0
  loop_hits:
    initial_value: 0
  orbit_hits:
    initial_value: 0
  target_hits:
    initial_value: 0
  rollover_hits:
    initial_value: 0
  capture_hits:
    initial_value: 0
  pop_hits:
    initial_value: 0
  power_hits: #Combination of pop and sling for bonus calculation
    initial_value: 0

  captive_ball_target_hits:
    initial_value: 0

  # pops_burnination mode behaviors:
  pop_left_fire_level:
    initial_value: 0

  pop_right_fire_level:
    initial_value: 0

  pop_center_fire_level:
    initial_value: 0

  burnination_points:
    initial_value: 0
