#config_version=6

player_vars:
  previous_ball_score:
    initial_value: 0
    value_type: int
  ball_score:
    initial_value: 0
    value_type: int

  playfield_multiplier:
    initial_value: 1
    value_type: int

  bonus_multiplier:
    initial_value: 1
    value_type: int

  # Skill shots
  total_skillshot_successes:
    initial_value: 0

  skillshot_of_an_artist_successes:
    initial_value: 0

  skillshot_2_successes:
    initial_value: 0

  skillshot_3_successes:
    initial_value: 0

  # misc features that count
  sling_hits:
    initial_value: 0
  spinner_spins:
    initial_value: 0
  half_spinner_spins: # this counts to 1 to save a half spin, and 2 to reset and increment a spinner spin instead
    initial_value: 0

  ramp_hits: #Only has right ramp counting #Needs: s ramp
    initial_value: 0
  loop_hits: #Not counting any orbits or loops yet #Needs: left outer orbit, right outer orbit, top loop, right loop
    initial_value: 0
  target_hits: #Not counting any yet #Needs: drops, rollover lane center, TBD others
    initial_value: 0
  rollover_hits: #Not counting any yet #Needs: top lanes, inlanes, outlanes?
    initial_value: 0
  capture_hits: #Not counting any yet #Needs: vuk, TBD left capture spot
    initial_value: 0
  pop_hits: #Not counting any yet #Needs: all three pops lol
    initial_value: 0

  captive_ball_target_hits:
    initial_value: 0

  # pops_burnination mode behaviors:
  pop_left_fire_level:
    initial_value: 0

  pop_right_fire_level:
    initial_value: 0

  pop_center_fire_level:
    initial_value: 0
