#config_version=6

player_vars:
  previous_ball_score:
    initial_value: 0
    value_type: int
  ball_score:
    initial_value: 0
    value_type: int

  playfield_multiplier:
    initial_value: 1
    value_type: int

  # Skill shots
  total_skillshot_successes:
    initial_value: 0
    value_type: int

  skillshot_of_an_artist_successes:
    initial_value: 0
    value_type: int

  skillshot_2_successes:
    initial_value: 0
    value_type: int

  skillshot_3_successes:
    initial_value: 0
    value_type: int

  # misc features that count
  sling_hits:
    initial_value: 0
  spinner_spins:
    initial_value: 0
  captive_ball_target_hits:
    initial_value: 0

  # pops_burnination mode behaviors:
  pop_left_fire_level:
    initial_value: 0
    value_type: int

  pop_right_fire_level:
    initial_value: 0
    value_type: int

  pop_center_fire_level:
    initial_value: 0
    value_type: int
