#config_version=6

settings:
  ball_search_enabled:
    sort: 200
    label: Ball Search Enabled?
    values:
      0: "Disabled"
      1: "Enabled"
    default: 0
    key_type: int


  flipper_main_coil_power:
    sort: 151
    label: Flipper main power
    key_type: int
    default: 24
    values:
      12: '12 ms'
      15: '15 ms'
      18: '18 ms'
      20: '20 ms'
      24: '24 ms (default)'
      28: '28 ms'
      32: '32 ms'
      36: '36 ms'
      40: '40 ms'

  # flipper_hold_coil_power: #Coil::default_hold_power doesn't support template variables
  #   sort: 152
  #   label: Flipper hold power (%)
  #   key_type: float
  #   default: 0.5
  #   values:
  #     0.125: '1/8'
  #     0.25: '1/4'
  #     0.375: '3/8'
  #     0.5: '1/2 (default)'
  #     0.625: '5/8'
  #     0.75: '3/4'
  #     0.875: '7/8'
  #     1: 'Full'

  upper_flipper_main_coil_power:
    sort: 153
    label: Upper flipper main power
    key_type: int
    default: 24
    values:
      12: '12 ms'
      15: '15 ms'
      18: '18 ms'
      20: '20 ms'
      24: '24 ms (default)'
      28: '28 ms'
      32: '32 ms'
      36: '36 ms'
      40: '40 ms'

  auto_plunger_coil_power:
    sort: 155
    label: Auto launch power
    key_type: int
    default: 18
    values:
      9: '9 ms'
      12: '12 ms'
      15: '15 ms'
      18: '18 ms (default)'
      21: '21 ms'
      24: '24 ms'
      28: '28 ms'
      32: '32 ms'
      36: '36 ms'
      40: '40 ms'

  trough_eject_coil_power:
    sort: 156
    label: Trough ball eject power
    key_type: int
    default: 20
    values:
      12: '12 ms'
      15: '15 ms'
      18: '18 ms'
      20: '20 ms (default)'
      24: '24 ms'
      28: '28 ms'
      32: '32 ms'
      36: '36 ms'
      40: '40 ms'

  slingshot_power:
    sort: 157
    label: Slingshot power
    key_type: int
    default: 12
    values:
      9: '9 ms'
      12: '12 ms (default)'
      15: '15 ms'
      18: '18 ms'
      21: '21 ms'
      24: '24 ms'

  pop_bumper_power:
    sort: 158
    label: Pop bumper power
    key_type: int
    default: 14
    values:
      8: '8 ms'
      11: '11 ms'
      14: '14 ms (default)'
      18: '18 ms'
      20: '20 ms'
      25: '25 ms'
      30: '30 ms'

  gate_power:
    sort: 159
    label: Controlled ball gate pulse power
    key_type: int
    default: 24
    values:
      12: '12 ms'
      16: '16 ms'
      20: '20 ms'
      24: '24 ms (default)'
      30: '30 ms'
      35: '35 ms'

  diverter_flipper_power:
    sort: 160
    label: Upper diverter (flipper) pulse power
    key_type: int
    default: 25
    values:
      12: '12 ms'
      15: '15 ms'
      20: '20 ms'
      25: '25 ms (default)'
      30: '30 ms'
      35: '35 ms'

  slot_bank_reset_power:
    sort: 161
    label: Slot (three-target) bank reset power
    key_type: int
    default: 30
    values:
      18: '18 ms'
      24: '24 ms'
      30: '30 ms (default)'
      35: '35 ms'
      40: '40 ms'

  slot_bank_knockdown_power:
    sort: 162
    label: Slot (three-target) bank single-target knockdown power
    key_type: int
    default: 18
    values:
      14: '14 ms'
      18: '18 ms (default)'
      22: '22 ms'
      26: '26 ms'
      30: '30 ms'

  vuk_power:
    sort: 163
    label: Right side VUK eject power
    key_type: int
    default: 25
    values:
      15: '15 ms'
      20: '20 ms'
      25: '25 ms (default)'
      30: '30 ms'
      35: '35 ms'

  outlane_post_power:
    sort: 163
    label: Right outlane post pulse power
    key_type: int
    default: 20
    values:
      15: '15 ms'
      20: '20 ms (default)'
      25: '25 ms'
      30: '30 ms'

  saver_post_power:
    sort: 163
    label: Center save post pulse power
    key_type: int
    default: 20
    values:
      15: '15 ms'
      20: '20 ms (default)'
      25: '25 ms'
      30: '30 ms'

  burnination_fire_level_one:
    sort: 301
    label: Burnination mode - target fire level one
    key_type: int
    default: 5
    values:
      4: '4'
      6: '6 (default)'
      8: '8'
      10: '10'
  burnination_fire_level_two:
    sort: 302
    label: Burnination mode - target fire level two
    key_type: int
    default: 10
    values:
      7: '7'
      10: '10 (default)'
      12: '12'
      15: '15'
      18: '18'
  burnination_fire_level_goal:
    sort: 304
    label: Burnination mode - target fire level per-pop
    key_type: int
    default: 20
    values:
      12: '12'
      16: '16'
      20: '20 (default)'
      25: '25'
      30: '30'

  burnination_pop_hit_increment:
    sort: 305
    label: Burnination mode - levels added per pop hit
    key_type: int
    default: 3
    values:
      1: '1'
      2: '2'
      3: '3 (default)'
      4: '4'
      5: '5'
  burnination_rollover_ontarget_increment:
    sort: 306
    label: Burnination mode - levels added per on-target rollover hit
    key_type: int
    default: 5
    values:
      0: '0'
      1: '1'
      2: '2'
      3: '3'
      4: '4'
      5: '5 (default)'
      6: '6'
  burnination_rollover_offtarget_increment:
    sort: 307
    label: Burnination mode - levels added per off-target rollover hit
    key_type: int
    default: 1
    values:
      0: '0'
      1: '1 (default)'
      2: '2'
      3: '3'
      4: '4'

  burnination_timer_seconds:
    sort: 310
    label: Burnination mode - overall length
    key_type: int
    default: 35
    values:
      20: '20 seconds'
      25: '25 seconds'
      30: '30 seconds'
      35: '35 seconds (default)'
      40: '40 seconds'
      45: '45 seconds'

  burnination_pop_countdown_seconds:
    sort: 311
    label: Burnination mode - seconds per pop burndown reduction
    key_type: int
    default: 4
    values:
      3: '3 seconds'
      4: '4 seconds (default)'
      5: '5 seconds'
      6: '6 seconds'
      7: '7 seconds'

  warnings_to_tilt:
    label: "Tilt on warning number:"
    values:
      0: "Tilt Disabled"
      1: "1"
      2: "2"
      3: "3 (default)"
      5: "5"
      10: "10"
    default: 3
    key_type: int
    sort: 401
  tilt_settle_time:
    label: Time to wait on tilt to settle bob
    values:
      3000: "3s"
      5000: "5s (default)"
      8000: "8s"
    default: 5000
    key_type: int
    sort: 402
  tilt_multiple_hit_window:
    label: Tilt Sensitivity
    values:
      150: "sensitive"
      300: "default"
      500: "insensitive"
      8000: "very insensitive"
    default: 300
    key_type: int
    sort: 403
