#config_version=6
# This is a generated file!
# 2024-08-31 03:37:05 -0700
---
mode:
  priority: 131
  start_events: ball_started
show_player:
  mode_generated_example_started:
    generated_show_a:
      action: play

