#config_version=6

#TODO this is fake for now, but a ruby harness should be able to regenerate it
mode:
  start_events: ball_started
  priority: 131

show_player:
  mode_generated_example_started:
    generated_show_a:
      action: play
