#config_version=6
# This is the example mode!

---
mode:
  priority: 1310
  start_events: ball_started
  stop_events: mode_stop_generated_example, ball_will_end
show_player:
  mode_generated_example_started:
    example_show_a:
      action: play
    speedup_spin_show:
      action: play
      show_tokens:
        color: teal
        ring_prefix: gl_ring_a

