#config_version=6
# This is the example mode!
# 2024-09-02 02:28:24 -0700
---
mode:
  priority: 131
  start_events: ball_started
show_player:
  mode_generated_example_started:
    example_show_a:
      action: play

