#config_version=6

mode:
  start_events: mode_start_slings_base
  stop_events: mode_stop_slings_base, ball_will_end
  priority: 1520

shot_profiles:
  sling_base_profile:
    advance_on_hit: False
    states:
      - name: 'live'

shots:
  shot_sling_left_base:
    profile: sling_base_profile
    switch: s_left_sling
  shot_sling_right_base:
    profile: sling_base_profile
    switch: s_right_sling

variable_player:
  #Simple sling scoring with sling counter
  #Left scores less because plunge to left is common
  shot_sling_left_base_hit:
    score: 25 * current_player.playfield_multiplier
    sling_hits: 1
    power_hits: 1
  shot_sling_right_base_hit:
    score: 50 * current_player.playfield_multiplier
    sling_hits: 1
    power_hits: 1

  #Hooks for sling sequence pairs
  #Sequence starting with left scores less because plunge start
  slings_l2r_hit:
    score: 250 * current_player.playfield_multiplier
  slings_r2l_hit:
    score: 555 * current_player.playfield_multiplier

sequence_shots:
  slings_l2r:
    event_sequence:
      - shot_sling_left_base_hit
      - shot_sling_right_base_hit
    sequence_timeout: 400ms
  slings_r2l:
    event_sequence:
      - shot_sling_right_base_hit
      - shot_sling_left_base_hit
    sequence_timeout: 400ms

event_player:
  shot_sling_left_base_hit: [dj_sling_pool]
  shot_sling_right_base_hit: [dj_sling_pool]
  slings_l2r_hit: [dj_sling_combo_pool]
  slings_r2l_hit: [dj_sling_combo_pool]

show_player:
  slings_l2r_hit:
    cottage_burn:
      action: play
      loops: 2
      key: l2r_star_a_burn
      show_tokens:
        l1: l_sling_post_ring_left_1
        l2: l_sling_post_ring_left_2
        l3: l_sling_post_ring_left_3
        l4: l_sling_post_ring_left_4
        l5: l_sling_post_ring_left_5
        l6: l_sling_post_ring_left_6
        l7: l_sling_post_ring_left_7
        l8: l_sling_post_ring_left_8

  slings_r2l_hit:
    cottage_burn:
      action: play
      loops: 2
      key: r2l_dome_a_burn
      show_tokens:
        l1: l_sling_post_ring_right_8
        l2: l_sling_post_ring_right_7
        l3: l_sling_post_ring_right_6
        l4: l_sling_post_ring_right_5
        l5: l_sling_post_ring_right_4
        l6: l_sling_post_ring_right_3
        l7: l_sling_post_ring_right_2
        l8: l_sling_post_ring_right_1
