#config_version=6

mode:
  start_events: mode_start_skillshot_base
  events_when_started: restart_skill_shots
  stop_events: mode_complete_skillshot_base, mode_fail_skillshot_base, ball_will_end
  priority: 3100

timers:
  skill_shot_timeout:
    start_value: 8
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: false
    control_events:
      - action: start
        event: balldevice_bd_plunger_ball_eject_success
      - action: stop
        event: skillshots_group_hit

variable_player:
  skillshot_of_an_artist_hitme_hit:
    score: 20000 + current_player.total_skillshot_successes * 12500
    total_skillshot_successes: 1
    skillshot_of_an_artist_successes: 1
    rollover_hits: 5

  skillshot_2_hitme_hit:
    score: 10000 + current_player.total_skillshot_successes * 7500
    total_skillshot_successes: 1
    skillshot_2_successes: 1
    capture_hits: 3

  skillshot_3_hitme_hit:
    score: 15000 + current_player.total_skillshot_successes * 1000
    total_skillshot_successes: 1
    skillshot_3_successes: 1
    spinner_spins: 10

event_player:
  mode_skillshot_base_started:
    - enable_orbit_diverter_skillshot
    - activate_orbit_diverter_skillshot
  timer_skill_shot_timeout_complete:
    - mode_fail_skillshot_base
  skillshot_of_an_artist_hitme_hit:
    - disable_skill_2
    - disable_skill_3
    - dj_skill_shot_1_hit|1s
  skillshot_2_hitme_hit:
    - disable_skill_1
    - disable_skill_3
    - dj_skill_shot_2_hit|1s
  skillshot_3_hitme_hit:
    - disable_skill_1
    - disable_skill_2
    - dj_skill_shot_3_hit|1s

  skillshots_group_hitme_hit:
    - skillshot_addaball_qualified
    - increment_playfield_multiplier
    - priority_show_skillshot_success
    - mode_complete_skillshot_base

shot_profiles:
  skill_shot_profile:
    advance_on_hit: False
    block: True
    states:
      - name: disabled
        show: on_color
        show_tokens:
          color: orange
      - name: hitme
        show: flash_color
        show_tokens:
          color: purple
      - name: completed
        show: flash_color
        show_tokens:
          color: purple
        speed: 10

shots:
  skillshot_of_an_artist:
    profile: skill_shot_profile
    switch: s_left_outer_lane
    advance_events: skillshot_of_an_artist_hitme_hit
    control_events:
      - events: restart_skill_shots
        state: 1
      - events: disable_skill_1
        state: 0
    show_tokens:
      light: l_majesty_6

  skillshot_2:
    profile: skill_shot_profile
    switch: s_subway_entrance
    advance_events: skillshot_2_hitme_hit
    control_events:
      - events: restart_skill_shots
        state: 1
      - events: disable_skill_2
        state: 0
    show_tokens:
      light: l_majesty_2

  skillshot_3:
    profile: skill_shot_profile
    switches: s_spinner_right
    advance_events: skillshot_3_hitme_hit
    control_events:
      - events: restart_skill_shots
        state: 1
      - events: disable_skill_3
        state: 0
    show_tokens:
      light: l_majesty_1

shot_groups:
  skillshots_group:
    shots: skillshot_of_an_artist, skillshot_2, skillshot_3
