#config_version=6

mode:
  start_events: ball_started
  stop_events: end_skillshot_base
  priority: 301

timers:
  skill_shot_timeout:
    start_value: 8
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: false
    control_events:
      - action: start
        event: balldevice_bd_plunger_ball_eject_success
      - action: stop
        event: skillshots_group_hit

event_player:
  timer_skill_shot_timeout_complete:
    - end_skillshot_base
  skillshot_of_an_artist_hitme_hit:
    - increment_playfield_multiplier
    - abort_skill_2
    - abort_skill_3
  skillshot_2_hitme_hit:
    - abort_skill_1
    - abort_skill_3
  skillshot_3_hitme_hit:
    - abort_skill_1
    - abort_skill_2

show_player:
  skillshots_group_hitme_hit:
    skillshot_success:
      action: play
      loops: 2
      events_when_completed: end_skillshot_base

shot_profiles:
  skill_shot_profile:
    advance_on_hit: false
    block: true
    states:
      - name: 'hitme'
        show: flash_color
        show_tokens:
          color: purple
      - name: 'completed'
        show: flash_color
        show_tokens:
          color: purple
        speed: 10
      - name: 'aborted'
        show: on_color
        show_tokens:
          color: orange

shots:
  skillshot_of_an_artist:
    profile: skill_shot_profile
    switch: s_spinner_left
    advance_events: skillshot_of_an_artist_hitme_hit
    control_events:
      - events: abort_skill_1
        state: 2
    show_tokens:
      light: l_majesty_6

  skillshot_2:
    profile: skill_shot_profile
    switch: s_spinner_right
    advance_events: skillshot_2_hitme_hit
    control_events:
      - events: abort_skill_2
        state: 2
    show_tokens:
      light: l_majesty_2

  skillshot_3:
    profile: skill_shot_profile
    switches: s_burn_b, s_burn_u, s_burn_r, s_burn_n
    advance_events: skillshot_3_hitme_hit
    control_events:
      - events: abort_skill_3
        state: 2
    show_tokens:
      light: l_majesty_1

shot_groups:
  skillshots_group:
    shots: skillshot_of_an_artist, skillshot_2, skillshot_3
    reset_events: ball_started
