#config_version=6

tilt:
  warnings_to_tilt: settings.warnings_to_tilt
  settle_time: settings.tilt_settle_time
  multiple_hit_window: settings.tilt_multiple_hit_window

slide_player:
  _overwrite: True
  tilt_warning_1:
    tilt_warning_1:
      expire: 1s
  tilt_warning_2:
    tilt_warning_2:
      expire: 1s
  tilt: tilt

  tilt_clear:
    tilt_warning_1:
      action: remove
    tilt_warning_2:
      action: remove
    tilt:
      action: remove

show_player:
  tilt_warning_1:
    flash_color:
      key: gi_flash
      action: play
      loops: 2
      speed: 5
      show_tokens:
        lights: lights_gi
        color: yellow

  tilt_warning_2:
    flash_color:
      key: gi_flash
      action: play
      loops: 3
      speed: 7
      show_tokens:
        lights: lights_gi
        color: orange

  tilt:
    flash_color:
      key: gi_flash
      action: play
      loops: 1
      speed: 2
      show_tokens:
        lights: lights_gi
        color: red
