#config_version=6

mode:
  start_events: mode_start_spinners_base
  stop_events: mode_stop_spinners_base, ball_will_end
  priority: 1710 #TODO

variable_player:
  base_spinner_hit:
    score: 10 * current_player.playfield_multiplier
    spinner_spins: 1
  targeted_spinner_hit:
    score: 50 * current_player.playfield_multiplier
    spinner_spins: 1

event_player:
  spinner_spinner_left_base_hit: [base_spinner_hit]
  spinner_spinner_right_base_hit: [base_spinner_hit]
  spinner_spinner_left_targeted_hit: [targeted_spinner_hit]
  spinner_spinner_right_targeted_hit: [targeted_spinner_hit]

light_player:
  "{device.switches.s_spinner_left.state == 0}":
    l_spinner_left_flasher: off
  "{device.switches.s_spinner_left.state == 1}":
    l_spinner_left_flasher: green
  "{device.switches.s_spinner_right.state == 0}":
    l_spinner_right_flasher: off
  "{device.switches.s_spinner_right.state == 1}":
    l_spinner_right_flasher: green

state_machines:
  left_spinner_state:
    persist_state: false
    states:
      start:
        label: start
        events_when_started:
          - disable_spinner_left_targeted
          - enable_spinner_left_base
      left_targeted:
        label: left targeted
        events_when_started:
          - disable_spinner_left_base
          - enable_spinner_left_targeted
        show_when_active:
          show: on
          show_tokens:
            light: l_spinner_left_indicator
    transitions:
      - source: start
        target: left_targeted
        events: spinner_controller_set_left_target
      - source: left_targeted
        target: start
        events: spinner_controller_unset_left_target

  right_spinner_state:
    persist_state: false
    states:
      start:
        label: start
        events_when_started:
          - disable_spinner_right_targeted
          - enable_spinner_right_base
      right_targeted:
        label: right targeted
        events_when_started:
          - disable_spinner_right_base
          - enable_spinner_right_targeted
        show_when_active:
          show: on
          show_tokens:
            light: l_spinner_right_indicator
    transitions:
      - source: start
        target: right_targeted
        events: spinner_controller_set_right_target
      - source: right_targeted
        target: start
        events: spinner_controller_unset_right_target
