#config_version=6

mode:
  start_events: mode_start_spinners_base
  stop_events: mode_stop_spinners_base, ball_will_end
  priority: 1590

variable_player:
  base_spinner_hit:
    score: 10 * current_player.playfield_multiplier
    spinner_spins: 1
    cheat_multiball_spins_left_to_qualify: -1
  targeted_spinner_hit:
    score: 50 * current_player.playfield_multiplier
    spinner_spins: 1
    cheat_multiball_spins_left_to_qualify: -1

  reset_cheat_multiball_qualifying_spins:
    cheat_multiball_spins_left_to_qualify:
      action: set
      int: 30 #settings.cheat_multiball_spins_to_qualify #TODO doesnt support templates?

  block_cheat_multiball_qualifying_spins:
    cheat_multiball_spins_left_to_qualify:
      action: set
      int: 99

  base_spinner_half_hit: 
    half_spinner_spins: 1

  targeted_spinner_half_hit: 
    half_spinner_spins: 1

  spinner_spinner_right_base_inactive:
    half_spinner_spins:
      int: 0
      action: set

  spinner_spinner_right_targeted_inactive:
    half_spinner_spins:
      int: 0
      action: set

  exchange_half_spinner:
    half_spinner_spins: -2

event_player:
  base_spinner_half_hit{current_player.half_spinner_spins >= 1}: [base_spinner_hit, exchange_half_spinner]
  targeted_spinner_half_hit{current_player.half_spinner_spins >= 1}: [targeted_spinner_hit, exchange_half_spinner]

  spinner_spinner_left_base_hit: [base_spinner_hit]
  spinner_spinner_left_targeted_hit: [targeted_spinner_hit]
  spinner_spinner_right_base_hit: [base_spinner_half_hit]
  spinner_spinner_right_targeted_hit: [targeted_spinner_half_hit]

  player_cheat_multiball_spins_left_to_qualify{value<=0}:
    - block_cheat_multiball_qualifying_spins
    - cheat_multiball_qualified

flasher_player:
  s_spinner_left_active:
    l_spinner_left_flasher:
      color: green
      ms: 100ms
    gi_sling_left_top:
      color: green
      ms: 100ms
  s_spinner_right_active:
    l_spinner_right_flasher:
      color: green
      ms: 100ms
    gi_sling_right_top:
      color: green
      ms: 100ms

state_machines:
  left_spinner_state:
    persist_state: false
    states:
      start:
        label: start
        events_when_started:
          - disable_spinner_left_targeted
          - enable_spinner_left_base
      left_targeted:
        label: left targeted
        events_when_started:
          - disable_spinner_left_base
          - enable_spinner_left_targeted
        show_when_active:
          show: on
          show_tokens:
            light: l_spinner_left_indicator
    transitions:
      - source: start
        target: left_targeted
        events: spinner_controller_set_left_target
      - source: left_targeted
        target: start
        events: spinner_controller_unset_left_target

  right_spinner_state:
    persist_state: false
    states:
      start:
        label: start
        events_when_started:
          - disable_spinner_right_targeted
          - enable_spinner_right_base
      right_targeted:
        label: right targeted
        events_when_started:
          - disable_spinner_right_base
          - enable_spinner_right_targeted
        show_when_active:
          show: on
          show_tokens:
            light: l_spinner_right_indicator
    transitions:
      - source: start
        target: right_targeted
        events: spinner_controller_set_right_target
      - source: right_targeted
        target: start
        events: spinner_controller_unset_right_target
