#config_version=6

mode:
  start_events: mode_start_burnination_controller
  stop_events: mode_stop_burnination_controller, ball_will_end
  priority: 7005

timers:
  #Mode time limit timer
  burnination_countdown:
    start_value: settings.burnination_timer_seconds
    end_value: 0
    direction: down
    start_running: false
    restart_on_complete: false
    control_events:
      - action: stop
        event: burnination_countdown_stop
      - action: restart
        event: burnination_countdown_restart
      - action: add
        value: settings.burnination_pop_hit_add_time
        event: increment_burnination_time_remaining

event_player:
  timer_burnination_countdown_complete:
    - burnination_controller_fail

  # When player variables change, test mode completion
  player_pop_left_fire_level:
    - check_burnination_complete
  player_pop_right_fire_level:
    - check_burnination_complete
  player_pop_center_fire_level:
    - check_burnination_complete

  check_burnination_complete{current_player.pop_left_fire_level > settings.burnination_fire_level_goal and current_player.pop_right_fire_level > settings.burnination_fire_level_goal and current_player.pop_center_fire_level > settings.burnination_fire_level_goal}:
    - burnination_controller_complete

widget_player:
  widget_hide_burn_letters:
    burn_letters:
      action: remove
  widget_show_burn_letters:
    burn_letters:
      slide: base
  widget_update_burn_letters:
    burn_letters:
      action: update

state_machines:
  burnination_state:
    persist_state: false
    states:
      start:
        label: inactive
        events_when_started:
          - mode_start_burn_rollovers
          - mode_start_pops_base
      burnination:
        label: burnination
        events_when_started:
          - mode_stop_pops_base
          - mode_start_pops_burnination
          - mode_stop_burn_rollovers
          - mode_start_burnination_rollovers
          - burnination_countdown_restart
          - burnination_multiball_qualified
          - dj_burnination_mode_song
          - widget_hide_burn_letters
      done:
        label: complete
        events_when_started:
          - dj_stop_burnination_mode_song
          - dj_burnination_background
          - burnination_countdown_stop
          - increment_playfield_multiplier
          - mode_stop_burnination_rollovers
          - mode_start_pops_burninated
          - mode_complete_pops_burnination
      failed:
        label: failed
        events_when_started:
          - dj_stop_burnination_mode_song
          - burnination_countdown_stop
          - mode_start_pops_base
          - mode_stop_burnination_rollovers
          - mode_start_burn_rollovers
          - mode_fail_pops_burnination
    transitions:
      - source: start
        target: burnination
        events: burnination_controller_begin
      - source: burnination
        target: done
        events: burnination_controller_complete
      - source: burnination
        target: failed
        events: burnination_controller_fail
