#config_version=6

mode:
  start_events: mode_start_slots_controller
  stop_events: mode_stop_slots_controller, ball_will_end
  priority: 7015

state_machines:
  slots_manager:
    persist_state: false
    starting_state: setup
    states:
      setup:
        label: setup #needed for the playfield_active transition to avoid early hits
        events_when_started: captive_ball_target_dead
      qualifying:
        label: qualifying
        events_when_started: delayed_captive_ball_target_live, mode_stop_generated_slots, mode_start_drops_base
      playing_slots:
        label: playing slots
        events_when_started: captive_ball_target_disable, mode_stop_drops_base, mode_start_generated_slots, dj_ball_intros_pool
    transitions:
      - source: setup
        target: qualifying
        events: playfield_active
      - source: qualifying
        target: playing_slots
        events: slots_manager_play
      - source: playing_slots
        target: qualifying
        events: slots_manager_stop
        events_when_transitioning: reset_captive_ball_target_hits
      - source: qualifying
        target: qualifying
        events: slots_manager_reset_bank
        events_when_transitioning: slots_target_bank_full_reset

event_player:
  delayed_captive_ball_target_live:
    - captive_ball_target_live|1ms
  mode_slots_controller_started:
    - mode_start_captive_ball_base

  player_captive_ball_target_hits{current_player.captive_ball_target_hits > 4}:
    - slots_manager_play
  player_captive_ball_target_hits{current_player.captive_ball_target_hits < 4}:
    - slots_manager_reset_bank

light_player:
  "{device.state_machines.slots_manager.state == 'qualifying' and device.switches.s_captive_ball_presence.state == 0}":
    l_captive_ball_single: orange
  "{device.state_machines.slots_manager.state == 'qualifying' and device.switches.s_captive_ball_presence.state == 1}":
    l_captive_ball_single: 'off'
  "{device.state_machines.slots_manager.state == 'playing_slots'}":
    l_captive_ball_single: '003399'
